require("dotenv").config({ path: "./.env.local" });
const mongoose = require("mongoose");

const MONGODB_URI = process.env.MONGODB_URI;
if (!MONGODB_URI) { console.error("No MONGODB_URI"); process.exit(1); }

const PhoneSchema = new mongoose.Schema({}, { strict: false });
const BrandSchema = new mongoose.Schema({}, { strict: false });

async function run() {
  await mongoose.connect(MONGODB_URI);
  console.log("Connected to MongoDB");

  const Phone = mongoose.models.Phone || mongoose.model("Phone", PhoneSchema);
  const Brand = mongoose.models.Brand || mongoose.model("Brand", BrandSchema);

  const apple = await Brand.findOne({ name: /apple/i }).lean();
  const bid = apple._id;

  const missingPhones = [
    {
      name: "iPhone 15 Plus",
      slug: "iphone-15-plus",
      brand_id: bid,
      is_published: true,
      is_official: true,
      release_date: "2023-09-22",
      colors: ["Black", "Blue", "Green", "Yellow", "Pink"],
      phone_variants: "128GB, 256GB, 512GB",
      price_bdt: 115000,
      price_official: 115000,
      price_unofficial: 95000,
      chipset_highlight: "Apple A16 Bionic (4nm)",
      camera_highlight: "48MP Main + 12MP Ultra Wide",
      display_highlight: "6.7\" Dynamic Island OLED",
      battery_highlight: "4,383 mAh (Excellent battery life)",
      processor: "Apple A16 Bionic",
      ram_variants: "6 GB",
      storage_variants: "128 GB, 256 GB, 512 GB",
      display_type: "Super Retina XDR OLED",
      screen_size: "6.7 inches",
      resolution: "2796 × 1290 pixels",
      cam_count: "Dual",
      cam_main_sensor: "48 MP, f/1.6, Sensor-shift OIS",
      cam_ultrawide: "12 MP, f/2.4",
      cam_ois: "Yes",
      has_5g: true,
      usb_type: "USB-C",
      sensor_fingerprint: "Face ID",
      has_nfc: true,
      update_policy: "Approx 5-7 years of software updates",
      ai_features: ["Siri with on-device dictation", "Visual Look Up", "No Apple Intelligence"],
      antutu_score: 1000000,
      geekbench_score: "Single: ~1,880 / Multi: ~5,350 (Geekbench 5)",
      fabrication: "4 nm",
      cooling_system: "Passive cooling"
    },
    {
      name: "iPhone 15 Pro",
      slug: "iphone-15-pro",
      brand_id: bid,
      is_published: true,
      is_official: true,
      release_date: "2023-09-22",
      colors: ["Black Titanium", "White Titanium", "Blue Titanium", "Natural Titanium"],
      phone_variants: "128GB, 256GB, 512GB, 1TB",
      price_bdt: 145000,
      price_official: 145000,
      price_unofficial: 120000,
      chipset_highlight: "Apple A17 Pro (3nm)",
      camera_highlight: "48MP Main + 12MP UW + 12MP Tele (3x Zoom)",
      display_highlight: "6.1\" Dynamic Island 120Hz OLED",
      battery_highlight: "3,274 mAh",
      processor: "Apple A17 Pro",
      ram_variants: "8 GB",
      storage_variants: "128 GB, 256 GB, 512 GB, 1 TB",
      display_type: "LTPO Super Retina XDR OLED",
      screen_size: "6.1 inches",
      resolution: "2556 × 1179 pixels",
      refresh_rate: "120 Hz",
      cam_count: "Triple",
      cam_main_sensor: "48 MP, f/1.78, Sensor-shift OIS",
      cam_ultrawide: "12 MP, f/2.2",
      cam_telephoto: "12 MP, f/2.8, 3x optical zoom",
      cam_ois: "Dual OIS",
      has_5g: true,
      usb_type: "USB-C (USB 3)",
      sensor_fingerprint: "Face ID",
      has_nfc: true,
      update_policy: "Approx 5-7 years (Long Term Update Promise)",
      ai_features: [
        "Apple Intelligence fully supported",
        "Generative AI Image Editor (Clean Up)",
        "Realtime Live Interpreter",
        "Next-Gen AI Voice Assistant"
      ],
      antutu_score: 1450000,
      geekbench_score: "Single: ~2,850 / Multi: ~7,000 (Geekbench 6)",
      fabrication: "3 nm",
      cooling_system: "Passive cooling, graphite sheets"
    },
    {
      name: "iPhone 16 Plus",
      slug: "iphone-16-plus",
      brand_id: bid,
      is_published: true,
      is_official: true,
      release_date: "2024-09-20",
      colors: ["Black", "White", "Pink", "Teal", "Ultramarine"],
      phone_variants: "128GB, 256GB, 512GB",
      price_bdt: 125000,
      price_official: 125000,
      price_unofficial: 105000,
      chipset_highlight: "Apple A18 (3nm)",
      camera_highlight: "48MP Fusion + 12MP Ultra Wide (Camera Control)",
      display_highlight: "6.7\" Super Retina XDR OLED",
      battery_highlight: "4,674 mAh (Massive battery life)",
      processor: "Apple A18",
      ram_variants: "8 GB",
      storage_variants: "128 GB, 256 GB, 512 GB",
      display_type: "Super Retina XDR OLED",
      screen_size: "6.7 inches",
      resolution: "2796 × 1290 pixels",
      cam_count: "Dual",
      cam_main_sensor: "48 MP, f/1.6, Sensor-shift OIS",
      cam_ultrawide: "12 MP, f/2.2",
      cam_ois: "Yes",
      has_5g: true,
      usb_type: "USB-C",
      sensor_fingerprint: "Face ID",
      has_nfc: true,
      update_policy: "Long Term Update Promise",
      ai_features: [
        "Apple Intelligence fully supported",
        "Generative AI Image Editor",
        "Next-Gen AI Voice Assistant",
        "Visual Intelligence via Camera Control"
      ],
      antutu_score: 1650000,
      geekbench_score: "Single: ~3,100 / Multi: ~7,600 (Geekbench 6)",
      fabrication: "3 nm",
      cooling_system: "New internal thermal architecture"
    },
    {
      name: "iPhone 16 Pro",
      slug: "iphone-16-pro",
      brand_id: bid,
      is_published: true,
      is_official: true,
      release_date: "2024-09-20",
      colors: ["Black Titanium", "White Titanium", "Natural Titanium", "Desert Titanium"],
      phone_variants: "128GB, 256GB, 512GB, 1TB",
      price_bdt: 155000,
      price_official: 155000,
      price_unofficial: 130000,
      chipset_highlight: "Apple A18 Pro (3nm)",
      camera_highlight: "48MP Main + 48MP UW + 12MP Tele (5x Zoom)",
      display_highlight: "6.3\" ProMotion 120Hz OLED",
      battery_highlight: "3,582 mAh",
      processor: "Apple A18 Pro",
      ram_variants: "8 GB",
      storage_variants: "128 GB, 256 GB, 512 GB, 1 TB",
      display_type: "LTPO Super Retina XDR OLED",
      screen_size: "6.3 inches",
      resolution: "2622 × 1206 pixels",
      refresh_rate: "120 Hz",
      cam_count: "Triple",
      cam_main_sensor: "48 MP, f/1.78, Sensor-shift OIS",
      cam_ultrawide: "48 MP, f/2.2",
      cam_telephoto: "12 MP, f/2.8, 5x optical zoom",
      cam_ois: "Dual OIS",
      has_5g: true,
      usb_type: "USB-C (USB 3)",
      sensor_fingerprint: "Face ID",
      has_nfc: true,
      update_policy: "Long Term Update Promise",
      ai_features: [
        "Apple Intelligence fully supported",
        "Generative AI Image Editor",
        "Next-Gen AI Voice Assistant",
        "Visual Intelligence via Camera Control"
      ],
      antutu_score: 1750000,
      geekbench_score: "Single: ~3,400 / Multi: ~8,300 (Geekbench 6)",
      fabrication: "3 nm",
      cooling_system: "Graphene thermal sheets"
    },
    {
      name: "iPhone 16e",
      slug: "iphone-16e",
      brand_id: bid,
      is_published: true,
      is_official: true,
      release_date: "2025-02-15",
      colors: ["Black", "White", "Blue"],
      phone_variants: "128GB, 256GB",
      price_bdt: 85000,
      price_official: 85000,
      price_unofficial: 70000,
      chipset_highlight: "Apple A18 (3nm)",
      camera_highlight: "48MP Fusion Camera",
      display_highlight: "6.1\" Super Retina XDR OLED",
      battery_highlight: "Decent all-day battery",
      processor: "Apple A18",
      ram_variants: "8 GB",
      storage_variants: "128 GB, 256 GB",
      display_type: "Super Retina XDR OLED",
      screen_size: "6.1 inches",
      resolution: "2556 × 1179 pixels",
      cam_count: "Single",
      cam_main_sensor: "48 MP, f/1.6, OIS",
      cam_ois: "Yes",
      has_5g: true,
      usb_type: "USB-C",
      sensor_fingerprint: "Face ID",
      has_nfc: true,
      update_policy: "Long Term Update Promise",
      ai_features: ["Apple Intelligence fully supported", "Gen AI Image Editor"],
      antutu_score: 1600000,
      geekbench_score: "Single: ~3,100 / Multi: ~7,400 (Geekbench 6)",
      fabrication: "3 nm",
      cooling_system: "Standard passive cooling"
    },
    {
      name: "iPhone 17",
      slug: "iphone-17",
      brand_id: bid,
      is_published: true,
      is_official: true,
      release_date: "2025-09-19",
      colors: ["Black", "White", "Blue", "Green", "Pink"],
      phone_variants: "128GB, 256GB, 512GB",
      price_bdt: 110000,
      price_official: 110000,
      price_unofficial: 90000,
      chipset_highlight: "Apple A19 (3nm)",
      camera_highlight: "48MP Dual Fusion Camera",
      display_highlight: "6.3\" ProMotion 120Hz OLED",
      battery_highlight: "Improved battery life",
      processor: "Apple A19",
      ram_variants: "8 GB",
      storage_variants: "128 GB, 256 GB, 512 GB",
      display_type: "Super Retina XDR OLED with ProMotion",
      screen_size: "6.3 inches",
      resolution: "2622 × 1206 pixels (approx)",
      refresh_rate: "120 Hz",
      cam_count: "Dual",
      cam_main_sensor: "48 MP, f/1.6, OIS",
      cam_ultrawide: "48 MP, f/2.2",
      cam_ois: "Yes",
      has_5g: true,
      usb_type: "USB-C",
      sensor_fingerprint: "Face ID",
      has_nfc: true,
      update_policy: "Long Term Update Promise",
      ai_features: ["Apple Intelligence supported", "Next-Gen AI Voice Assistant"],
      antutu_score: 1900000,
      geekbench_score: "Single: ~3,500 / Multi: ~8,800 (Geekbench 6)",
      fabrication: "3 nm",
      cooling_system: "Improved thermal design"
    },
    {
      name: "iPhone 17 Pro",
      slug: "iphone-17-pro",
      brand_id: bid,
      is_published: true,
      is_official: true,
      release_date: "2025-09-19",
      colors: ["Black Titanium", "White Titanium", "Natural Titanium"],
      phone_variants: "256GB, 512GB, 1TB",
      price_bdt: 165000,
      price_official: 165000,
      price_unofficial: 135000,
      chipset_highlight: "Apple A19 Pro (3nm)",
      camera_highlight: "Triple 48MP System",
      display_highlight: "6.3\" ProMotion 120Hz OLED",
      battery_highlight: "Vapor chamber cooling battery",
      processor: "Apple A19 Pro",
      ram_variants: "12 GB",
      storage_variants: "256 GB, 512 GB, 1 TB",
      display_type: "LTPO Super Retina XDR OLED",
      screen_size: "6.3 inches",
      resolution: "2622 × 1206 pixels",
      refresh_rate: "120 Hz",
      cam_count: "Triple",
      cam_main_sensor: "48 MP, f/1.78, OIS",
      cam_ultrawide: "48 MP, f/2.2",
      cam_telephoto: "48 MP, OIS",
      cam_ois: "Triple OIS",
      has_5g: true,
      usb_type: "USB-C (USB 3)",
      sensor_fingerprint: "Face ID",
      has_nfc: true,
      update_policy: "Long Term Update Promise",
      ai_features: ["Advanced Apple Intelligence", "Next-Gen AI Voice Assistant"],
      antutu_score: 2100000,
      geekbench_score: "Single: ~3,700 / Multi: ~9,200 (Geekbench 6)",
      fabrication: "3 nm",
      cooling_system: "Vapor chamber cooling"
    }
  ];

  for (const p of missingPhones) {
    const exists = await Phone.findOne({ slug: p.slug });
    if (exists) {
      await Phone.updateOne({ slug: p.slug }, { $set: p });
      console.log(`Updated: ${p.name}`);
    } else {
      await Phone.create(p);
      console.log(`Created: ${p.name}`);
    }
  }

  await mongoose.disconnect();
  console.log("Done. All missing iPhones added.");
}

run().catch(e => { console.error(e); process.exit(1); });
