const brandId = "6a075ca13ffb4fd85e744f2e";
const phones = [
  {
    name: "Realme 12 5G",
    slug: "realme-12-5g",
    brand_id: brandId,
    phone_status: "released",
    upcoming: false,
    is_published: true,
    is_featured: false,
    release_date: "March 6, 2024",
    release_date_parsed: new Date("2024-03-06"),
    launch_year: 2024,
    price_usd: 205,
    weight: "188 g",
    dimensions: "165.6 x 76.1 x 7.7 mm",
    build_material: "Glass front, plastic frame, plastic back",
    water_resistance: "IP54 dust and splash resistant",
    ip_rating: "IP54",
    sim_type: "Dual SIM (Nano-SIM, dual stand-by)",
    made_in: "China",
    phone_variants: "6GB/128GB, 8GB/128GB",
    colors: "Twilight Purple, Woodland Green",
    display_type: "IPS LCD",
    screen_size: "6.72 inches",
    resolution: "1080 x 2400 pixels",
    refresh_rate: "120Hz",
    brightness: "950 nits (peak)",
    hdr: "No",
    protection: "Tempered Glass",
    pixel_density: "392 ppi",
    processor: "MediaTek Dimensity 6100+ (6 nm)",
    cpu: "Octa-core (2x2.2 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)",
    gpu: "Mali-G57 MC2",
    fabrication: "6nm",
    ram_variants: "6GB, 8GB",
    storage_variants: "128GB",
    storage_type: "UFS 2.2",
    geekbench_score: "1900 (Multi-Core)",
    cooling_system: "Graphite cooling",
    cam_count: "Dual",
    cam_main_sensor: "108 MP, f/1.8, 24mm (wide), 1/1.67\", 3x in-sensor zoom",
    cam_ultrawide: "No",
    cam_telephoto: "No",
    cam_macro: "2 MP, f/2.4, (depth)",
    cam_ois: "No",
    cam_flash: "LED flash",
    cam_video: "1080p@30fps",
    cam_front_resolution: "8 MP, f/2.0, 26mm (wide)",
    cam_front_hdr: "No",
    cam_front_portrait: "Yes",
    cam_front_video: "1080p@30fps",
    battery_capacity: "5000 mAh",
    charging_wired: "45W wired",
    charging_wireless: "No",
    charging_reverse: "No",
    charger_included: "Yes",
    usb_type: "USB Type-C 2.0",
    wifi_version: "Wi-Fi 802.11 a/b/g/n/ac",
    bluetooth_version: "5.2, A2DP, LE",
    has_nfc: "No",
    gps_specs: "GPS, GLONASS, GALILEO, BDS",
    has_ir_blaster: "No",
    has_audio_jack: "Yes",
    usb_version: "2.0",
    has_5g: "Yes",
    network: "GSM / HSPA / LTE / 5G",
    sensor_fingerprint: "Side-mounted",
    has_gyroscope: "Yes",
    has_compass: "Yes",
    has_accelerometer: "Yes",
    has_face_unlock: "Yes",
    android_version: "Android 14",
    ui_version: "Realme UI 5.0",
    update_policy: "2 Years OS Updates",
    ai_features: "Dynamic Button functionality",
    chipset_highlight: "MediaTek Dimensity 6100+ for stable everyday 5G",
    camera_highlight: "108MP primary camera with 3x in-sensor zoom",
    display_highlight: "120Hz IPS LCD reaching up to 950 nits peak brightness",
    battery_highlight: "5000mAh paired with efficient 45W fast charging",
    meta_title: "Realme 12 5G Features, Specs & Price",
    meta_description: "Explore the Realme 12 5G featuring a 108MP camera, 120Hz display, and Dimensity 6100+. View complete specifications and pricing.",
    seo_overview: "The Realme 12 5G attempts to bring the high-resolution 108MP camera experience to a budget-friendly 5G tier. It utilizes in-sensor zoom to provide quality 3x magnification shots without needing a dedicated telephoto lens. The phone runs on the power-efficient MediaTek Dimensity 6100+ chipset and offers a bright 120Hz LCD screen. Adding quirky features like the customizable Dynamic Button gives it a unique flair among competitors in its price segment.",
    verdict: "A solid lower mid-range choice if your primary requirement is a high-megapixel camera and reliable 5G connectivity without spending a fortune."
  },
  {
    name: "Realme 12x 5G",
    slug: "realme-12x-5g",
    brand_id: brandId,
    phone_status: "released",
    upcoming: false,
    is_published: true,
    is_featured: false,
    release_date: "March 21, 2024",
    release_date_parsed: new Date("2024-03-21"),
    launch_year: 2024,
    price_usd: 145,
    weight: "190 g",
    dimensions: "165.6 x 76.1 x 7.9 mm",
    build_material: "Glass front, plastic frame, plastic back",
    water_resistance: "IP54 dust and splash resistant",
    ip_rating: "IP54",
    sim_type: "Dual SIM (Nano-SIM, dual stand-by)",
    made_in: "China",
    phone_variants: "4GB/128GB, 6GB/128GB, 8GB/128GB",
    colors: "Twilight Purple, Woodland Green",
    display_type: "IPS LCD",
    screen_size: "6.72 inches",
    resolution: "1080 x 2400 pixels",
    refresh_rate: "120Hz",
    brightness: "950 nits (peak)",
    hdr: "No",
    protection: "Panda Glass",
    pixel_density: "392 ppi",
    processor: "MediaTek Dimensity 6100+ (6 nm)",
    cpu: "Octa-core (2x2.2 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)",
    gpu: "Mali-G57 MC2",
    fabrication: "6nm",
    ram_variants: "4GB, 6GB, 8GB",
    storage_variants: "128GB",
    storage_type: "UFS 2.2",
    geekbench_score: "1900 (Multi-Core)",
    cooling_system: "VC Cooling System",
    cam_count: "Dual",
    cam_main_sensor: "50 MP, f/1.8, 26mm (wide), 1/2.76\"",
    cam_ultrawide: "No",
    cam_telephoto: "No",
    cam_macro: "2 MP, f/2.4, (depth)",
    cam_ois: "No",
    cam_flash: "LED flash",
    cam_video: "1080p@30fps",
    cam_front_resolution: "8 MP, f/2.0, 26mm (wide)",
    cam_front_hdr: "No",
    cam_front_portrait: "Yes",
    cam_front_video: "1080p@30fps",
    battery_capacity: "5000 mAh",
    charging_wired: "45W wired",
    charging_wireless: "No",
    charging_reverse: "No",
    charger_included: "Yes",
    usb_type: "USB Type-C 2.0",
    wifi_version: "Wi-Fi 802.11 a/b/g/n/ac",
    bluetooth_version: "5.3, A2DP, LE",
    has_nfc: "No",
    gps_specs: "GPS, GLONASS, GALILEO, BDS",
    has_ir_blaster: "No",
    has_audio_jack: "Yes",
    usb_version: "2.0",
    has_5g: "Yes",
    network: "GSM / HSPA / LTE / 5G",
    sensor_fingerprint: "Side-mounted",
    has_gyroscope: "Yes",
    has_compass: "Yes",
    has_accelerometer: "Yes",
    has_face_unlock: "Yes",
    android_version: "Android 14",
    ui_version: "Realme UI 5.0",
    update_policy: "2 Years OS Updates",
    ai_features: "Air Gestures",
    chipset_highlight: "Dimensity 6100+ delivering reliable entry-level 5G",
    camera_highlight: "50MP AI primary camera for everyday snaps",
    display_highlight: "120Hz smooth LCD display with bright outdoor visibility",
    battery_highlight: "5000mAh battery paired with fast 45W charging",
    meta_title: "Realme 12x 5G Specs, Price & Features",
    meta_description: "View full specs for the Realme 12x 5G. A budget-friendly 5G device with a 120Hz display, 50MP camera, and 45W charging.",
    seo_overview: "The Realme 12x 5G acts as the entry ticket to the Realme 12 series, focusing on providing essential features at the lowest possible price point while maintaining 5G support. It cuts back on the camera megapixel count compared to its siblings, utilizing a standard 50MP shooter. However, it retains the snappy 120Hz display, VC cooling, and fast 45W charging, making it surprisingly capable for an entry-level smartphone.",
    verdict: "Perfect for users on a strict budget who want a fast-charging, smooth-display 5G phone but don't care much for high-end photography."
  },
  {
    name: "Realme C65",
    slug: "realme-c65",
    brand_id: brandId,
    phone_status: "released",
    upcoming: false,
    is_published: true,
    is_featured: false,
    release_date: "April 4, 2024",
    release_date_parsed: new Date("2024-04-04"),
    launch_year: 2024,
    price_usd: 150,
    weight: "185 g",
    dimensions: "164.6 x 76.1 x 7.6 mm",
    build_material: "Glass front, plastic frame, plastic back",
    water_resistance: "IP54 dust and splash resistant",
    ip_rating: "IP54",
    sim_type: "Dual SIM (Nano-SIM, dual stand-by)",
    made_in: "China",
    phone_variants: "6GB/128GB, 8GB/128GB, 8GB/256GB",
    colors: "Purple Nebula, Black Milky Way",
    display_type: "IPS LCD",
    screen_size: "6.67 inches",
    resolution: "720 x 1604 pixels",
    refresh_rate: "90Hz",
    brightness: "625 nits (peak)",
    hdr: "No",
    protection: "Panda Glass",
    pixel_density: "264 ppi",
    processor: "MediaTek Helio G85 (12nm)",
    cpu: "Octa-core (2x2.0 GHz Cortex-A75 & 6x1.8 GHz Cortex-A55)",
    gpu: "Mali-G52 MC2",
    fabrication: "12nm",
    ram_variants: "6GB, 8GB",
    storage_variants: "128GB, 256GB",
    storage_type: "eMMC 5.1",
    geekbench_score: "1400 (Multi-Core)",
    cooling_system: "Basic graphite sheet",
    cam_count: "Dual",
    cam_main_sensor: "50 MP, f/1.8, (wide), PDAF",
    cam_ultrawide: "No",
    cam_telephoto: "No",
    cam_macro: "2 MP, f/2.4, (depth)",
    cam_ois: "No",
    cam_flash: "LED flash",
    cam_video: "1080p@30fps",
    cam_front_resolution: "8 MP, f/2.0, (wide)",
    cam_front_hdr: "No",
    cam_front_portrait: "Yes",
    cam_front_video: "1080p@30fps",
    battery_capacity: "5000 mAh",
    charging_wired: "45W wired",
    charging_wireless: "No",
    charging_reverse: "No",
    charger_included: "Yes",
    usb_type: "USB Type-C 2.0",
    wifi_version: "Wi-Fi 802.11 a/b/g/n/ac",
    bluetooth_version: "5.0, A2DP, LE",
    has_nfc: "No",
    gps_specs: "GPS, GLONASS, GALILEO, BDS",
    has_ir_blaster: "No",
    has_audio_jack: "Yes",
    usb_version: "2.0",
    has_5g: "No",
    network: "GSM / HSPA / LTE",
    sensor_fingerprint: "Side-mounted",
    has_gyroscope: "Yes",
    has_compass: "Yes",
    has_accelerometer: "Yes",
    has_face_unlock: "Yes",
    android_version: "Android 14",
    ui_version: "Realme UI 5.0",
    update_policy: "2 Years OS Updates",
    ai_features: "Mini Capsule 2.0",
    chipset_highlight: "MediaTek Helio G85 for basic daily tasks",
    camera_highlight: "50MP AI primary camera",
    display_highlight: "90Hz Eye Comfort Display",
    battery_highlight: "5000mAh battery with 45W fast charging support",
    meta_title: "Realme C65 Specs, Features & Price",
    meta_description: "Discover Realme C65 features. A budget 4G phone with a 90Hz display, 50MP camera, Helio G85 chipset, and 45W fast charging.",
    seo_overview: "The Realme C65 is targeted at the entry-level market, prioritizing long battery life, fast charging, and a visually pleasing design. While its Helio G85 chipset and 720p display are basic by modern standards, the phone compensates with its snappy 45W charging—a rarity at this ultra-budget price tier. The 50MP main camera does an adequate job for social media snaps in good lighting.",
    verdict: "An acceptable choice for light users and children, primarily notable for bringing 45W fast charging to a very low price bracket."
  },
  {
    name: "Realme C63",
    slug: "realme-c63",
    brand_id: brandId,
    phone_status: "released",
    upcoming: false,
    is_published: true,
    is_featured: false,
    release_date: "June 5, 2024",
    release_date_parsed: new Date("2024-06-05"),
    launch_year: 2024,
    price_usd: 130,
    weight: "189 g",
    dimensions: "167.3 x 76.7 x 7.7 mm",
    build_material: "Glass front, vegan leather or plastic back, plastic frame",
    water_resistance: "IP54 dust and splash resistant",
    ip_rating: "IP54",
    sim_type: "Dual SIM (Nano-SIM, dual stand-by)",
    made_in: "China",
    phone_variants: "6GB/128GB, 8GB/128GB, 8GB/256GB",
    colors: "Leather Blue, Jade Green",
    display_type: "IPS LCD",
    screen_size: "6.75 inches",
    resolution: "720 x 1600 pixels",
    refresh_rate: "90Hz",
    brightness: "560 nits (peak)",
    hdr: "No",
    protection: "Reinforced Glass",
    pixel_density: "260 ppi",
    processor: "Unisoc Tiger T612 (12 nm)",
    cpu: "Octa-core (2x1.8 GHz Cortex-A75 & 6x1.8 GHz Cortex-A55)",
    gpu: "Mali-G57",
    fabrication: "12nm",
    ram_variants: "6GB, 8GB",
    storage_variants: "128GB, 256GB",
    storage_type: "eMMC 5.1",
    geekbench_score: "1250 (Multi-Core)",
    cooling_system: "Basic thermal management",
    cam_count: "Dual",
    cam_main_sensor: "50 MP, f/1.8, (wide), PDAF",
    cam_ultrawide: "No",
    cam_telephoto: "No",
    cam_macro: "Auxiliary lens",
    cam_ois: "No",
    cam_flash: "LED flash",
    cam_video: "1080p@30fps",
    cam_front_resolution: "8 MP, f/2.0, (wide)",
    cam_front_hdr: "No",
    cam_front_portrait: "Yes",
    cam_front_video: "720p@30fps",
    battery_capacity: "5000 mAh",
    charging_wired: "45W wired",
    charging_wireless: "No",
    charging_reverse: "No",
    charger_included: "Yes",
    usb_type: "USB Type-C 2.0",
    wifi_version: "Wi-Fi 802.11 a/b/g/n/ac",
    bluetooth_version: "5.0, A2DP, LE",
    has_nfc: "No",
    gps_specs: "GPS, GLONASS, GALILEO, BDS",
    has_ir_blaster: "No",
    has_audio_jack: "Yes",
    usb_version: "2.0",
    has_5g: "No",
    network: "GSM / HSPA / LTE",
    sensor_fingerprint: "Side-mounted",
    has_gyroscope: "Yes",
    has_compass: "Yes",
    has_accelerometer: "Yes",
    has_face_unlock: "Yes",
    android_version: "Android 14",
    ui_version: "Realme UI 5.0",
    update_policy: "2 Years OS Updates",
    ai_features: "Mini Capsule 2.0, Air Gestures",
    chipset_highlight: "Unisoc T612 for essential daily functions",
    camera_highlight: "50MP primary camera",
    display_highlight: "Large 6.75-inch 90Hz HD+ display",
    battery_highlight: "5000mAh battery with 45W fast charging",
    meta_title: "Realme C63 Specs, Features & Price",
    meta_description: "Explore the Realme C63 with vegan leather back, 45W charging, and 90Hz display. View complete details and specs.",
    seo_overview: "The Realme C63 introduces a touch of luxury to the ultra-budget segment with its vegan leather back option, a design element usually reserved for pricier phones. Internally, it is very basic, relying on the Unisoc T612 and a 720p display. Like the C65, its main attraction is the inclusion of 45W fast charging paired with a 5000mAh battery, ensuring you are rarely left without power.",
    verdict: "If you prioritize a premium look and feel with fast charging over display sharpness and gaming performance, the Realme C63 is an interesting ultra-budget option."
  },
  {
    name: "Realme C61",
    slug: "realme-c61",
    brand_id: brandId,
    phone_status: "released",
    upcoming: false,
    is_published: true,
    is_featured: false,
    release_date: "June 28, 2024",
    release_date_parsed: new Date("2024-06-28"),
    launch_year: 2024,
    price_usd: 110,
    weight: "188 g",
    dimensions: "167.3 x 76.7 x 7.8 mm",
    build_material: "Glass front, plastic frame, plastic back",
    water_resistance: "IP54 dust and splash resistant",
    ip_rating: "IP54",
    sim_type: "Dual SIM (Nano-SIM, dual stand-by)",
    made_in: "China",
    phone_variants: "4GB/64GB, 4GB/128GB, 6GB/128GB",
    colors: "Safari Green, Marble Black",
    display_type: "IPS LCD",
    screen_size: "6.74 inches",
    resolution: "720 x 1600 pixels",
    refresh_rate: "90Hz",
    brightness: "560 nits (peak)",
    hdr: "No",
    protection: "Reinforced Glass",
    pixel_density: "260 ppi",
    processor: "Unisoc Tiger T612 (12 nm)",
    cpu: "Octa-core (2x1.8 GHz Cortex-A75 & 6x1.8 GHz Cortex-A55)",
    gpu: "Mali-G57",
    fabrication: "12nm",
    ram_variants: "4GB, 6GB",
    storage_variants: "64GB, 128GB",
    storage_type: "eMMC 5.1",
    geekbench_score: "1200 (Multi-Core)",
    cooling_system: "Basic thermal management",
    cam_count: "Dual",
    cam_main_sensor: "32 MP, f/1.8, (wide), PDAF",
    cam_ultrawide: "No",
    cam_telephoto: "No",
    cam_macro: "Auxiliary lens",
    cam_ois: "No",
    cam_flash: "LED flash",
    cam_video: "1080p@30fps",
    cam_front_resolution: "5 MP, f/2.2, (wide)",
    cam_front_hdr: "No",
    cam_front_portrait: "Yes",
    cam_front_video: "720p@30fps",
    battery_capacity: "5000 mAh",
    charging_wired: "15W wired",
    charging_wireless: "No",
    charging_reverse: "No",
    charger_included: "Yes",
    usb_type: "USB Type-C 2.0",
    wifi_version: "Wi-Fi 802.11 a/b/g/n/ac",
    bluetooth_version: "5.0, A2DP, LE",
    has_nfc: "No",
    gps_specs: "GPS, GLONASS, GALILEO, BDS",
    has_ir_blaster: "No",
    has_audio_jack: "Yes",
    usb_version: "2.0",
    has_5g: "No",
    network: "GSM / HSPA / LTE",
    sensor_fingerprint: "Side-mounted",
    has_gyroscope: "Yes",
    has_compass: "Yes",
    has_accelerometer: "Yes",
    has_face_unlock: "Yes",
    android_version: "Android 14",
    ui_version: "Realme UI 5.0",
    update_policy: "2 Years OS Updates",
    ai_features: "Mini Capsule",
    chipset_highlight: "Unisoc T612 for basic smartphone tasks",
    camera_highlight: "32MP primary camera",
    display_highlight: "6.74-inch 90Hz display",
    battery_highlight: "5000mAh battery offering multi-day longevity",
    meta_title: "Realme C61 Specs, Features & Price",
    meta_description: "Realme C61 specifications, including Unisoc T612, 32MP camera, and 5000mAh battery. Learn more about this affordable entry-level phone.",
    seo_overview: "The Realme C61 strips down the smartphone experience to the bare essentials, aimed purely at users looking for the most affordable device available. It uses a basic Unisoc chipset, a 32MP camera, and standard 15W charging. While it doesn't boast impressive specs, its 5000mAh battery provides excellent longevity due to the low-power components.",
    verdict: "An absolute entry-level device suitable only for those who need a basic smartphone for calling, texting, and light web browsing."
  },
  {
    name: "Realme Narzo 70 Pro 5G",
    slug: "realme-narzo-70-pro-5g",
    brand_id: brandId,
    phone_status: "released",
    upcoming: false,
    is_published: true,
    is_featured: false,
    release_date: "March 19, 2024",
    release_date_parsed: new Date("2024-03-19"),
    launch_year: 2024,
    price_usd: 240,
    weight: "195 g",
    dimensions: "163.0 x 75.5 x 8.0 mm",
    build_material: "Glass front, glass back, plastic frame",
    water_resistance: "IP54 dust and splash resistant",
    ip_rating: "IP54",
    sim_type: "Dual SIM (Nano-SIM, dual stand-by)",
    made_in: "China",
    phone_variants: "8GB/128GB, 8GB/256GB",
    colors: "Glass Green, Glass Gold",
    display_type: "AMOLED",
    screen_size: "6.67 inches",
    resolution: "1080 x 2400 pixels",
    refresh_rate: "120Hz",
    brightness: "2000 nits (peak)",
    hdr: "HDR10+",
    protection: "Tempered Glass",
    pixel_density: "395 ppi",
    processor: "MediaTek Dimensity 7050 (6 nm)",
    cpu: "Octa-core (2x2.6 GHz Cortex-A78 & 6x2.0 GHz Cortex-A55)",
    gpu: "Mali-G68 MC4",
    fabrication: "6nm",
    ram_variants: "8GB",
    storage_variants: "128GB, 256GB",
    storage_type: "UFS 2.2",
    geekbench_score: "2350 (Multi-Core)",
    cooling_system: "3D VC Cooling System",
    cam_count: "Triple",
    cam_main_sensor: "50 MP, f/1.88, 24mm (wide), 1/1.56\", OIS",
    cam_ultrawide: "8 MP, f/2.2, 16mm, 112˚ (ultrawide)",
    cam_telephoto: "No",
    cam_macro: "2 MP, f/2.4, (macro)",
    cam_ois: "Yes",
    cam_flash: "LED flash",
    cam_video: "1080p@30/60fps",
    cam_front_resolution: "16 MP, f/2.4, (wide)",
    cam_front_hdr: "Yes",
    cam_front_portrait: "Yes",
    cam_front_video: "1080p@30fps",
    battery_capacity: "5000 mAh",
    charging_wired: "67W wired",
    charging_wireless: "No",
    charging_reverse: "No",
    charger_included: "Yes",
    usb_type: "USB Type-C 2.0",
    wifi_version: "Wi-Fi 802.11 a/b/g/n/ac/6",
    bluetooth_version: "5.2, A2DP, LE",
    has_nfc: "No",
    gps_specs: "GPS, GLONASS, GALILEO, BDS, QZSS",
    has_ir_blaster: "No",
    has_audio_jack: "Yes",
    usb_version: "2.0",
    has_5g: "Yes",
    network: "GSM / HSPA / LTE / 5G",
    sensor_fingerprint: "Under display, optical",
    has_gyroscope: "Yes",
    has_compass: "Yes",
    has_accelerometer: "Yes",
    has_face_unlock: "Yes",
    android_version: "Android 14",
    ui_version: "Realme UI 5.0",
    update_policy: "2 Years OS Updates",
    ai_features: "Air Gestures",
    chipset_highlight: "Dimensity 7050 for smooth gaming and daily tasks",
    camera_highlight: "50MP Sony IMX890 OIS Camera",
    display_highlight: "120Hz AMOLED hitting 2000 nits peak brightness",
    battery_highlight: "5000mAh battery with 67W SuperVOOC charge",
    meta_title: "Realme Narzo 70 Pro 5G Specs, Features & Price",
    meta_description: "Explore Realme Narzo 70 Pro 5G specifications. Equipped with a Sony IMX890 OIS camera, Dimensity 7050, and a 120Hz AMOLED display.",
    seo_overview: "The Realme Narzo 70 Pro 5G is a surprisingly powerful offering in the budget-friendly segment, highlighting its 50MP Sony IMX890 primary sensor with OIS—a flagship-grade sensor rarely found at this price point. It also offers a premium glass back design and an incredibly bright 120Hz AMOLED display. Powered by the Dimensity 7050, it easily handles regular tasks and moderate gaming, making it highly competitive.",
    verdict: "A superb value-for-money smartphone, heavily recommended for those who want flagship-level primary camera performance and a great display on a budget."
  },
  {
    name: "Realme Narzo 70x 5G",
    slug: "realme-narzo-70x-5g",
    brand_id: brandId,
    phone_status: "released",
    upcoming: false,
    is_published: true,
    is_featured: false,
    release_date: "April 24, 2024",
    release_date_parsed: new Date("2024-04-24"),
    launch_year: 2024,
    price_usd: 155,
    weight: "188 g",
    dimensions: "165.6 x 76.1 x 7.7 mm",
    build_material: "Glass front, plastic frame, plastic back",
    water_resistance: "IP54 dust and splash resistant",
    ip_rating: "IP54",
    sim_type: "Dual SIM (Nano-SIM, dual stand-by)",
    made_in: "China",
    phone_variants: "4GB/128GB, 6GB/128GB, 8GB/128GB",
    colors: "Ice Blue, Forest Green",
    display_type: "IPS LCD",
    screen_size: "6.72 inches",
    resolution: "1080 x 2400 pixels",
    refresh_rate: "120Hz",
    brightness: "950 nits (peak)",
    hdr: "No",
    protection: "Panda Glass",
    pixel_density: "392 ppi",
    processor: "MediaTek Dimensity 6100+ (6 nm)",
    cpu: "Octa-core (2x2.2 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)",
    gpu: "Mali-G57 MC2",
    fabrication: "6nm",
    ram_variants: "4GB, 6GB, 8GB",
    storage_variants: "128GB",
    storage_type: "UFS 2.2",
    geekbench_score: "1900 (Multi-Core)",
    cooling_system: "VC Cooling System",
    cam_count: "Dual",
    cam_main_sensor: "50 MP, f/1.8, 26mm (wide), 1/2.76\", PDAF",
    cam_ultrawide: "No",
    cam_telephoto: "No",
    cam_macro: "2 MP, f/2.4, (depth)",
    cam_ois: "No",
    cam_flash: "LED flash",
    cam_video: "1080p@30fps",
    cam_front_resolution: "8 MP, f/2.0, (wide)",
    cam_front_hdr: "No",
    cam_front_portrait: "Yes",
    cam_front_video: "1080p@30fps",
    battery_capacity: "5000 mAh",
    charging_wired: "45W wired",
    charging_wireless: "No",
    charging_reverse: "No",
    charger_included: "Yes",
    usb_type: "USB Type-C 2.0",
    wifi_version: "Wi-Fi 802.11 a/b/g/n/ac",
    bluetooth_version: "5.3, A2DP, LE",
    has_nfc: "No",
    gps_specs: "GPS, GLONASS, GALILEO, BDS",
    has_ir_blaster: "No",
    has_audio_jack: "Yes",
    usb_version: "2.0",
    has_5g: "Yes",
    network: "GSM / HSPA / LTE / 5G",
    sensor_fingerprint: "Side-mounted",
    has_gyroscope: "Yes",
    has_compass: "Yes",
    has_accelerometer: "Yes",
    has_face_unlock: "Yes",
    android_version: "Android 14",
    ui_version: "Realme UI 5.0",
    update_policy: "2 Years OS Updates",
    ai_features: "Mini Capsule 2.0",
    chipset_highlight: "Dimensity 6100+ for stable 5G",
    camera_highlight: "50MP AI primary camera",
    display_highlight: "120Hz smooth LCD display",
    battery_highlight: "5000mAh battery with 45W charging",
    meta_title: "Realme Narzo 70x 5G Specs, Price & Features",
    meta_description: "View full specs for the Realme Narzo 70x 5G. A budget 5G phone with a 120Hz display, 50MP camera, and fast 45W charging.",
    seo_overview: "The Realme Narzo 70x 5G is a rebranded cousin of the Realme 12x 5G, offering virtually identical specs under a different design aesthetic aimed primarily at online markets. It delivers dependable entry-level 5G connectivity via the Dimensity 6100+, features a smooth 120Hz LCD screen, and includes a fast 45W charger in the box—maintaining strong value for budget-conscious buyers.",
    verdict: "A solid entry-level 5G device that shines through its high refresh rate display and fast charging, ideal for those on a tight budget."
  },
  {
    name: "Realme P1 Pro 5G",
    slug: "realme-p1-pro-5g",
    brand_id: brandId,
    phone_status: "released",
    upcoming: false,
    is_published: true,
    is_featured: false,
    release_date: "April 15, 2024",
    release_date_parsed: new Date("2024-04-15"),
    launch_year: 2024,
    price_usd: 260,
    weight: "184 g",
    dimensions: "161.5 x 74.0 x 8.4 mm",
    build_material: "Glass front, plastic frame, plastic back",
    water_resistance: "IP65 dust/water resistant",
    ip_rating: "IP65",
    sim_type: "Dual SIM (Nano-SIM, dual stand-by)",
    made_in: "China",
    phone_variants: "8GB/128GB, 8GB/256GB",
    colors: "Phoenix Red, Parrot Blue",
    display_type: "AMOLED",
    screen_size: "6.7 inches",
    resolution: "1080 x 2412 pixels",
    refresh_rate: "120Hz",
    brightness: "950 nits (peak)",
    hdr: "No",
    protection: "Reinforced Glass",
    pixel_density: "394 ppi",
    processor: "Qualcomm Snapdragon 6 Gen 1 (4 nm)",
    cpu: "Octa-core (4x2.2 GHz Cortex-A78 & 4x1.8 GHz Cortex-A55)",
    gpu: "Adreno 710",
    fabrication: "4nm",
    ram_variants: "8GB",
    storage_variants: "128GB, 256GB",
    storage_type: "UFS 3.1",
    geekbench_score: "2750 (Multi-Core)",
    cooling_system: "3D VC Cooling",
    cam_count: "Dual",
    cam_main_sensor: "50 MP, f/1.8, 26mm (wide), 1/1.95\", OIS",
    cam_ultrawide: "8 MP, f/2.2, 16mm, 112˚ (ultrawide)",
    cam_telephoto: "No",
    cam_macro: "No",
    cam_ois: "Yes",
    cam_flash: "LED flash",
    cam_video: "4K@30fps, 1080p@30/60/120fps",
    cam_front_resolution: "16 MP, f/2.4, 22mm (wide)",
    cam_front_hdr: "Yes",
    cam_front_portrait: "Yes",
    cam_front_video: "1080p@30fps",
    battery_capacity: "5000 mAh",
    charging_wired: "45W wired",
    charging_wireless: "No",
    charging_reverse: "No",
    charger_included: "Yes",
    usb_type: "USB Type-C 2.0",
    wifi_version: "Wi-Fi 802.11 a/b/g/n/ac/6",
    bluetooth_version: "5.2, A2DP, LE",
    has_nfc: "Yes",
    gps_specs: "GPS, GLONASS, GALILEO, BDS, QZSS",
    has_ir_blaster: "No",
    has_audio_jack: "No",
    usb_version: "2.0",
    has_5g: "Yes",
    network: "GSM / HSPA / LTE / 5G",
    sensor_fingerprint: "Under display, optical",
    has_gyroscope: "Yes",
    has_compass: "Yes",
    has_accelerometer: "Yes",
    has_face_unlock: "Yes",
    android_version: "Android 14",
    ui_version: "Realme UI 5.0",
    update_policy: "3 Years OS Updates",
    ai_features: "Rainwater Smart Touch",
    chipset_highlight: "Snapdragon 6 Gen 1 for fluid processing",
    camera_highlight: "50MP Sony LYT-600 OIS camera",
    display_highlight: "Curved AMOLED 120Hz Display",
    battery_highlight: "5000mAh battery with 45W charging",
    meta_title: "Realme P1 Pro 5G Features, Specs & Price",
    meta_description: "Realme P1 Pro 5G specs including curved AMOLED, Snapdragon 6 Gen 1, and 50MP OIS camera. Find out more about this stylish phone.",
    seo_overview: "The Realme P1 Pro 5G is part of a series focused aggressively on providing powerful performance at a lower mid-range price. It features a striking curved AMOLED display and is powered by the capable Snapdragon 6 Gen 1. The 50MP primary camera includes OIS for stable photography, while the phone's design stands out with its unique color options and IP65 rating.",
    verdict: "A beautifully designed curved-display phone that balances solid performance with a good camera, offering excellent value in its price tier."
  },
  {
    name: "Realme P1 5G",
    slug: "realme-p1-5g",
    brand_id: brandId,
    phone_status: "released",
    upcoming: false,
    is_published: true,
    is_featured: false,
    release_date: "April 15, 2024",
    release_date_parsed: new Date("2024-04-15"),
    launch_year: 2024,
    price_usd: 190,
    weight: "188 g",
    dimensions: "163.0 x 75.5 x 8.0 mm",
    build_material: "Glass front, plastic frame, plastic back",
    water_resistance: "IP54 dust and splash resistant",
    ip_rating: "IP54",
    sim_type: "Dual SIM (Nano-SIM, dual stand-by)",
    made_in: "China",
    phone_variants: "6GB/128GB, 8GB/128GB, 8GB/256GB",
    colors: "Phoenix Red, Peacock Green",
    display_type: "AMOLED",
    screen_size: "6.67 inches",
    resolution: "1080 x 2400 pixels",
    refresh_rate: "120Hz",
    brightness: "2000 nits (peak)",
    hdr: "No",
    protection: "Tempered Glass",
    pixel_density: "395 ppi",
    processor: "MediaTek Dimensity 7050 (6 nm)",
    cpu: "Octa-core (2x2.6 GHz Cortex-A78 & 6x2.0 GHz Cortex-A55)",
    gpu: "Mali-G68 MC4",
    fabrication: "6nm",
    ram_variants: "6GB, 8GB",
    storage_variants: "128GB, 256GB",
    storage_type: "UFS 2.2",
    geekbench_score: "2350 (Multi-Core)",
    cooling_system: "3D VC Cooling",
    cam_count: "Dual",
    cam_main_sensor: "50 MP, f/1.8, 27mm (wide), 1/2.76\", PDAF",
    cam_ultrawide: "No",
    cam_telephoto: "No",
    cam_macro: "2 MP, f/2.4, (depth)",
    cam_ois: "No",
    cam_flash: "LED flash",
    cam_video: "1080p@30fps",
    cam_front_resolution: "16 MP, f/2.4, 24mm (wide)",
    cam_front_hdr: "No",
    cam_front_portrait: "Yes",
    cam_front_video: "1080p@30fps",
    battery_capacity: "5000 mAh",
    charging_wired: "45W wired",
    charging_wireless: "No",
    charging_reverse: "No",
    charger_included: "Yes",
    usb_type: "USB Type-C 2.0",
    wifi_version: "Wi-Fi 802.11 a/b/g/n/ac/6",
    bluetooth_version: "5.2, A2DP, LE",
    has_nfc: "No",
    gps_specs: "GPS, GLONASS, GALILEO, BDS, QZSS",
    has_ir_blaster: "No",
    has_audio_jack: "Yes",
    usb_version: "2.0",
    has_5g: "Yes",
    network: "GSM / HSPA / LTE / 5G",
    sensor_fingerprint: "Under display, optical",
    has_gyroscope: "Yes",
    has_compass: "Yes",
    has_accelerometer: "Yes",
    has_face_unlock: "Yes",
    android_version: "Android 14",
    ui_version: "Realme UI 5.0",
    update_policy: "2 Years OS Updates",
    ai_features: "Rainwater Smart Touch",
    chipset_highlight: "Dimensity 7050 for impressive budget performance",
    camera_highlight: "50MP AI main camera",
    display_highlight: "120Hz flat AMOLED reaching 2000 nits peak brightness",
    battery_highlight: "5000mAh battery with 45W fast charging",
    meta_title: "Realme P1 5G Specs, Features & Price",
    meta_description: "Discover the Realme P1 5G. Featuring a fast Dimensity 7050 chip, 120Hz AMOLED, and 45W charging. Ideal for budget gamers.",
    seo_overview: "The Realme P1 5G aims to disrupt the budget gaming segment by offering the powerful Dimensity 7050 chipset and a remarkably bright 120Hz AMOLED display at a very accessible price point. While its camera setup is fairly basic, it utilizes a 3D VC cooling system to maintain high performance during gaming sessions. It's a performance-first device with a unique, eye-catching design.",
    verdict: "Highly recommended for budget-conscious gamers who prioritize processor power and display quality over advanced camera features."
  }
];

import fs from 'fs';
fs.writeFileSync('realme_data_2.json', JSON.stringify(phones, null, 2));
