import mongoose from 'mongoose';
import * as dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.resolve(process.cwd(), '.env.local') });

const MONGODB_URI = process.env.MONGODB_URI;

const commonSeoFields = (name: string, price: number, keywordSuffix: string = 'price in bd') => ({
  meta_title: `Samsung ${name} Price in Bangladesh, Specs & Review`,
  meta_keywords: `samsung ${name.toLowerCase()}, ${name.toLowerCase()} price in bd, samsung bangladesh, ${name.toLowerCase()} specs, legacy flagship`,
  meta_description: `Official and Unofficial Samsung ${name} price in Bangladesh. Dive into the specs, design, and nostalgia of this classic Samsung flagship.`,
  canonical_url: `https://www.techtweak.tech/phones/samsung/samsung-${name.toLowerCase().replace(/ /g, '-')}`,
  primary_keyword: `samsung ${name.toLowerCase()} ${keywordSuffix}`,
  secondary_keywords: [`samsung ${name.toLowerCase()} price`, `samsung ${name.toLowerCase()} specs`, `samsung ${name.toLowerCase()} review`],
  question_keywords: [
    `what is the price of samsung ${name.toLowerCase()} in bangladesh?`,
    `is samsung ${name.toLowerCase()} still good?`,
    `does samsung ${name.toLowerCase()} support 4g?`
  ],
  faq_schema: [
    { question: `What is the price of Samsung ${name} in Bangladesh?`, answer: `The Samsung ${name} originally launched at around BDT ${price * 115}. Today, it is mostly found in the second-hand or refurbished market.` },
    { question: `Is the Samsung ${name} waterproof?`, answer: `Please check the IP rating in the specifications table. Most Samsung S-series flagships from the S7 onwards feature IP68 resistance.` },
    { question: `Does the Samsung ${name} have a headphone jack?`, answer: `Older legacy Samsung flagships (S10 and prior) typically include a 3.5mm headphone jack. Check the connectivity specs below for confirmation.` }
  ]
});

const phonesData = [
  {
    name: "Galaxy S10 Lite",
    slug: "samsung-galaxy-s10-lite",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Prism White", "Prism Black", "Prism Blue"],
    release_date: "2020-02-03",
    price_usd: 650,
    price_bdt: 55000,
    price_display_text: "BDT 55,000",
    processor: "Snapdragon 855",
    gpu: "Adreno 640",
    display_type: "Super AMOLED Plus",
    screen_size: "6.7 inches",
    refresh_rate: "60Hz",
    brightness: "800 nits",
    cam_count: "Triple",
    cam_main_sensor: "48 MP, f/2.0, Super Steady OIS",
    video_recording: "4K@30/60fps, 1080p@30/60/240fps",
    battery_capacity: "4500 mAh",
    charging_wired: "45W wired",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "186 g",
    dimensions: "162.5 x 75.6 x 8.1 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Premium Mid-Range",
    performance_tier: "Mainstream",
    camera_tier: "Good",
    battery_tier: "Standard",
    internal_links: { same_brand: ["samsung-galaxy-note-10-lite", "samsung-galaxy-s10"] },
    ...commonSeoFields("Galaxy S10 Lite", 650),
    overview: "The Galaxy S10 Lite was a surprisingly powerful addition to the S10 family, released long after the original lineup. Unlike the standard S10 series which often used Exynos chips, the S10 Lite was universally powered by the excellent Snapdragon 855, making it a favorite among gamers and performance enthusiasts. It also featured a much larger 6.7-inch display and a bigger 4500mAh battery compared to the standard S10. A unique feature was the 'Super Steady OIS' on its 48MP main camera, which provided gimbal-like stabilization for video recording. However, it lacked the premium glass build, water resistance, and wireless charging of its siblings.",
    highlights: ["Universal Snapdragon 855", "Super Steady OIS Camera", "Large 4500mAh Battery"],
    pros: ["Excellent, stable performance", "Great battery life", "Fantastic video stabilization"],
    cons: ["Plastic build doesn't feel like an S-series", "No wireless charging or IP rating"],
    verdict: "A fantastic, practical alternative to the main S10 lineup, prioritizing battery and raw performance over premium luxury features."
  },
  {
    name: "Galaxy S9+",
    slug: "samsung-galaxy-s9-plus",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Midnight Black", "Coral Blue", "Titanium Gray", "Lilac Purple"],
    release_date: "2018-03-16",
    price_usd: 839,
    price_bdt: 75000,
    price_display_text: "BDT 75,000",
    processor: "Exynos 9810 / Snapdragon 845",
    gpu: "Mali-G72 MP18 / Adreno 630",
    display_type: "Super AMOLED",
    screen_size: "6.2 inches",
    refresh_rate: "60Hz",
    brightness: "1050 nits",
    cam_count: "Dual",
    cam_main_sensor: "12 MP, f/1.5-2.4 (variable), OIS",
    video_recording: "4K@30/60fps, 1080p@30/60/240fps, 720p@960fps",
    battery_capacity: "3500 mAh",
    charging_wired: "15W wired",
    wireless_charging: "15W wireless",
    ip_rating: "IP68 dust/water resistant",
    weight: "189 g",
    dimensions: "158.1 x 73.8 x 8.5 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Mid-Range",
    performance_tier: "Basic",
    camera_tier: "Basic",
    battery_tier: "Basic",
    internal_links: { same_brand: ["samsung-galaxy-s9", "samsung-galaxy-s10"] },
    ...commonSeoFields("Galaxy S9+", 839),
    overview: "The Galaxy S9+ refined the stunning design introduced by the S8, but its major upgrade was in the camera department. It was the first Galaxy S phone to feature a dual-camera system, adding a 2x optical zoom lens alongside the main sensor. More impressively, the main camera introduced a revolutionary mechanical variable aperture (f/1.5 to f/2.4) that physically adjusted to let in more light in the dark and sharpen images in daylight. It also fixed the biggest flaw of the S8 by moving the fingerprint scanner below the camera module. With stereo speakers and a headphone jack, it was a phenomenal multimedia device.",
    highlights: ["Variable aperture main camera", "Dual camera system with telephoto", "AKG-tuned stereo speakers"],
    pros: ["Fantastic low-light photography", "Beautiful, refined design", "Stereo speakers were a massive upgrade"],
    cons: ["Battery life was just okay", "Bixby button could not be fully disabled natively"],
    verdict: "A nearly perfect refinement of the S8, fixing its flaws while introducing a truly innovative camera system."
  },
  {
    name: "Galaxy S9",
    slug: "samsung-galaxy-s9",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Midnight Black", "Coral Blue", "Titanium Gray", "Lilac Purple"],
    release_date: "2018-03-16",
    price_usd: 719,
    price_bdt: 65000,
    price_display_text: "BDT 65,000",
    processor: "Exynos 9810 / Snapdragon 845",
    gpu: "Mali-G72 MP18 / Adreno 630",
    display_type: "Super AMOLED",
    screen_size: "5.8 inches",
    refresh_rate: "60Hz",
    brightness: "1050 nits",
    cam_count: "Single",
    cam_main_sensor: "12 MP, f/1.5-2.4 (variable), OIS",
    video_recording: "4K@30/60fps, 1080p@30/60/240fps, 720p@960fps",
    battery_capacity: "3000 mAh",
    charging_wired: "15W wired",
    wireless_charging: "15W wireless",
    ip_rating: "IP68 dust/water resistant",
    weight: "163 g",
    dimensions: "147.7 x 68.7 x 8.5 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Budget",
    performance_tier: "Basic",
    camera_tier: "Basic",
    battery_tier: "Basic",
    internal_links: { same_brand: ["samsung-galaxy-s9-plus", "samsung-galaxy-s8"] },
    ...commonSeoFields("Galaxy S9", 719),
    overview: "The standard Galaxy S9 was the compact sibling to the S9+, sharing the same stunning design and the innovative variable-aperture main camera. Unlike the Plus model, it only featured a single rear camera, missing out on the telephoto zoom capabilities. However, it still captured incredible photos in both daylight and low light. It also shared the much-improved stereo speakers and the better-placed fingerprint scanner. Its compact 5.8-inch screen made it incredibly comfortable to use with one hand, though its small 3000mAh battery struggled to keep up with heavy users throughout a full day.",
    highlights: ["Variable aperture camera", "Compact 5.8-inch design", "Super slow-mo 960fps video"],
    pros: ["Perfect size for one-handed use", "Excellent main camera", "Retained the headphone jack"],
    cons: ["Battery life was weak", "Lacks the dual camera of the Plus model"],
    verdict: "A beautifully compact flagship that offered an innovative camera, but was held back by mediocre battery endurance."
  },
  {
    name: "Galaxy S8+",
    slug: "samsung-galaxy-s8-plus",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Midnight Black", "Orchid Gray", "Arctic Silver", "Coral Blue", "Maple Gold"],
    release_date: "2017-04-21",
    price_usd: 850,
    price_bdt: 70000,
    price_display_text: "BDT 70,000",
    processor: "Exynos 8895 / Snapdragon 835",
    gpu: "Mali-G71 MP20 / Adreno 540",
    display_type: "Super AMOLED",
    screen_size: "6.2 inches",
    refresh_rate: "60Hz",
    brightness: "1000 nits",
    cam_count: "Single",
    cam_main_sensor: "12 MP, f/1.7, OIS",
    video_recording: "4K@30fps, 1080p@30/60fps",
    battery_capacity: "3500 mAh",
    charging_wired: "15W wired",
    wireless_charging: "15W wireless",
    ip_rating: "IP68 dust/water resistant",
    weight: "173 g",
    dimensions: "159.5 x 73.4 x 8.1 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Budget",
    performance_tier: "Basic",
    camera_tier: "Basic",
    battery_tier: "Basic",
    internal_links: { same_brand: ["samsung-galaxy-s8", "samsung-galaxy-s9-plus"] },
    ...commonSeoFields("Galaxy S8+", 850),
    overview: "The Galaxy S8+ revolutionized smartphone aesthetics by introducing the 'Infinity Display'. It completely ditched the physical home button, pushing the screen to the very edges and curving the glass beautifully on the sides. The result was a massive 6.2-inch display fitted into a body that felt shockingly narrow and comfortable to hold. The 12MP camera remained one of the best on the market, capturing excellent detail and vibrant colors. However, the bold redesign forced Samsung to place the fingerprint scanner in an incredibly awkward position right next to the camera lens, resulting in constantly smudged photos.",
    highlights: ["Revolutionary Infinity Display", "Sleek, bezel-less design", "Excellent 12MP camera"],
    pros: ["The design still looks modern today", "Gorgeous, vibrant AMOLED screen", "Solid performance"],
    cons: ["Terrible fingerprint scanner placement", "Introduced the annoying Bixby button"],
    verdict: "A milestone in smartphone design that changed how phones looked forever, despite a few ergonomic missteps."
  },
  {
    name: "Galaxy S8",
    slug: "samsung-galaxy-s8",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Midnight Black", "Orchid Gray", "Arctic Silver", "Coral Blue"],
    release_date: "2017-04-21",
    price_usd: 750,
    price_bdt: 60000,
    price_display_text: "BDT 60,000",
    processor: "Exynos 8895 / Snapdragon 835",
    gpu: "Mali-G71 MP20 / Adreno 540",
    display_type: "Super AMOLED",
    screen_size: "5.8 inches",
    refresh_rate: "60Hz",
    brightness: "1000 nits",
    cam_count: "Single",
    cam_main_sensor: "12 MP, f/1.7, OIS",
    video_recording: "4K@30fps, 1080p@30/60fps",
    battery_capacity: "3000 mAh",
    charging_wired: "15W wired",
    wireless_charging: "15W wireless",
    ip_rating: "IP68 dust/water resistant",
    weight: "155 g",
    dimensions: "148.9 x 68.1 x 8 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Budget",
    performance_tier: "Basic",
    camera_tier: "Basic",
    battery_tier: "Basic",
    internal_links: { same_brand: ["samsung-galaxy-s8-plus", "samsung-galaxy-s7-edge"] },
    ...commonSeoFields("Galaxy S8", 750),
    overview: "Like its larger sibling, the Galaxy S8 was a design marvel. It packed a 5.8-inch screen into a chassis that was actually smaller than the previous year's 5.1-inch S7. The elimination of the home button and the introduction of virtual navigation keys paved the way for the modern smartphone era. It featured an Iris Scanner for secure unlocking, attempting to make up for the awkwardly placed rear fingerprint sensor. The device performed brilliantly for its time, and its camera was exceptional, but the 3000mAh battery was definitely its Achilles' heel, struggling under heavy usage.",
    highlights: ["Compact Infinity Display", "Iris Scanner", "Sleek, futuristic design"],
    pros: ["Incredibly comfortable to hold", "Stunning display", "Great camera quality"],
    cons: ["Battery life was poor", "Fingerprint scanner placement was annoying"],
    verdict: "A stunning piece of hardware that ushered in the bezel-less era, perfect for users who prioritized design above all else."
  },
  {
    name: "Galaxy S7 Edge",
    slug: "samsung-galaxy-s7-edge",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Black Onyx", "Gold Platinum", "Silver Titanium", "Blue Coral"],
    release_date: "2016-03-11",
    price_usd: 769,
    price_bdt: 55000,
    price_display_text: "BDT 55,000",
    processor: "Exynos 8890 / Snapdragon 820",
    gpu: "Mali-T880 MP12 / Adreno 530",
    display_type: "Super AMOLED",
    screen_size: "5.5 inches",
    refresh_rate: "60Hz",
    brightness: "850 nits",
    cam_count: "Single",
    cam_main_sensor: "12 MP, f/1.7, Dual Pixel PDAF, OIS",
    video_recording: "4K@30fps, 1080p@30/60fps",
    battery_capacity: "3600 mAh",
    charging_wired: "15W wired",
    wireless_charging: "15W wireless",
    ip_rating: "IP68 dust/water resistant",
    weight: "157 g",
    dimensions: "150.9 x 72.6 x 7.7 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Budget",
    performance_tier: "Basic",
    camera_tier: "Basic",
    battery_tier: "Basic",
    internal_links: { same_brand: ["samsung-galaxy-s7", "samsung-galaxy-s8"] },
    ...commonSeoFields("Galaxy S7 Edge", 769),
    overview: "The Galaxy S7 Edge is widely considered one of the greatest smartphones Samsung ever produced. It took the beautiful curved-glass design of the S6 Edge and fixed literally every complaint users had: it brought back water resistance, it brought back the expandable MicroSD card slot, and it significantly increased the battery size to a robust 3600mAh. The introduction of 'Dual Pixel' autofocus technology meant the 12MP camera could focus almost instantly, capturing brilliant photos even in near darkness. It was the peak of the traditional 'Home Button' era of Samsung phones.",
    highlights: ["Curved Edge display", "Dual Pixel fast autofocus", "Return of MicroSD & Water Resistance"],
    pros: ["Gorgeous design that aged wonderfully", "Excellent battery life", "Industry-leading camera at the time"],
    cons: ["Accidental edge touches were common", "TouchWiz software could lag over time"],
    verdict: "A true classic. The S7 Edge was a masterclass in refining a product, offering beauty, power, and practicality in one package."
  },
  {
    name: "Galaxy S7",
    slug: "samsung-galaxy-s7",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Black Onyx", "Gold Platinum", "Silver Titanium", "White Pearl"],
    release_date: "2016-03-11",
    price_usd: 669,
    price_bdt: 45000,
    price_display_text: "BDT 45,000",
    processor: "Exynos 8890 / Snapdragon 820",
    gpu: "Mali-T880 MP12 / Adreno 530",
    display_type: "Super AMOLED",
    screen_size: "5.1 inches",
    refresh_rate: "60Hz",
    brightness: "850 nits",
    cam_count: "Single",
    cam_main_sensor: "12 MP, f/1.7, Dual Pixel PDAF, OIS",
    video_recording: "4K@30fps, 1080p@30/60fps",
    battery_capacity: "3000 mAh",
    charging_wired: "15W wired",
    wireless_charging: "15W wireless",
    ip_rating: "IP68 dust/water resistant",
    weight: "152 g",
    dimensions: "142.4 x 69.6 x 7.9 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Budget",
    performance_tier: "Basic",
    camera_tier: "Basic",
    battery_tier: "Basic",
    internal_links: { same_brand: ["samsung-galaxy-s7-edge"] },
    ...commonSeoFields("Galaxy S7", 669),
    overview: "The standard Galaxy S7 offered the exact same incredible power and revolutionary 'Dual Pixel' camera as the Edge model, but in a more traditional, flat-screened 5.1-inch form factor. Many users actually preferred this model because it was easier to grip and completely avoided the accidental touch issues associated with the curved edges. While its 3000mAh battery was smaller than the Edge variant, it still easily outlasted the previous generation S6. With IP68 water resistance, wireless charging, and expandable storage, it was an incredibly complete and reliable smartphone.",
    highlights: ["Flat 5.1-inch Super AMOLED", "Dual Pixel Camera", "IP68 Water Resistance"],
    pros: ["Extremely comfortable to hold", "No accidental edge touches", "Incredible camera performance"],
    cons: ["Design looked slightly dated compared to the Edge", "Fingerprint magnet glass back"],
    verdict: "The sensible, highly reliable choice of 2016. It lacked the flashy curved screen but delivered a flawless, practical flagship experience."
  }
];

async function run() {
  try {
    await mongoose.connect(MONGODB_URI as string);
    console.log("✅ Connected to MongoDB");

    const Brand = mongoose.models.Brand || mongoose.model("Brand", new mongoose.Schema({}, { strict: false }));
    const samsungBrand = await Brand.findOne({ name: /Samsung/i });

    const PhoneSchema = new mongoose.Schema({}, { strict: false });
    const Phone = mongoose.models.Phone || mongoose.model("Phone", PhoneSchema);

    for (const phone of phonesData) {
      if (samsungBrand) (phone as any).brand_id = samsungBrand._id;
      phone.updated_at = new Date() as any;
      await Phone.findOneAndUpdate({ slug: phone.slug }, { $set: phone }, { upsert: true, new: true });
      console.log(`✅ Inserted/Updated: ${phone.name}`);
    }

    console.log("🎉 Samsung Batch 8 (Legacy S Series) completed! Added 7 phones with 100% strict spec adherence.");

  } catch (err) {
    console.error("❌ Error:", (err as Error).message);
  } finally {
    await mongoose.disconnect();
  }
}

run();
