import mongoose from 'mongoose';
import * as dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.resolve(process.cwd(), '.env.local') });

const MONGODB_URI = process.env.MONGODB_URI;

const commonSeoFields = (name: string, price: number, keywordSuffix: string = 'price in bd') => ({
  meta_title: `Samsung ${name} Price in Bangladesh, Specs & Review`,
  meta_keywords: `samsung ${name.toLowerCase()}, ${name.toLowerCase()} price in bd, samsung bangladesh, ${name.toLowerCase()} specs, big battery phone`,
  meta_description: `Official and Unofficial Samsung ${name} price in Bangladesh. Discover its massive battery life, super AMOLED display, and complete technical specifications.`,
  canonical_url: `https://www.techtweak.tech/phones/samsung/samsung-${name.toLowerCase().replace(/ /g, '-')}`,
  primary_keyword: `samsung ${name.toLowerCase()} ${keywordSuffix}`,
  secondary_keywords: [`samsung ${name.toLowerCase()} price`, `samsung ${name.toLowerCase()} specs`, `samsung ${name.toLowerCase()} battery test`],
  question_keywords: [
    `what is the price of samsung ${name.toLowerCase()} in bangladesh?`,
    `does samsung ${name.toLowerCase()} have a super amoled display?`,
    `what is the battery capacity of samsung ${name.toLowerCase()}?`
  ],
  faq_schema: [
    { question: `What is the price of Samsung ${name} in Bangladesh?`, answer: `The original expected launch price of the Samsung ${name} in Bangladesh was around BDT ${price * 115}. Check local listings for current used market prices.` },
    { question: `Does the Samsung ${name} support fast charging?`, answer: `Yes, M-series phones typically support at least 15W fast charging, with higher-end models supporting 25W. See the full specs below.` },
    { question: `Is the Samsung ${name} good for gaming?`, answer: `While not specifically built for heavy gaming, its massive battery and decent mid-range processor make it capable of prolonged casual gaming sessions.` }
  ]
});

const phonesData = [
  {
    name: "Galaxy M51",
    slug: "samsung-galaxy-m51",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Celestial Black", "Electric Blue", "White"],
    release_date: "2020-09-11",
    price_usd: 350,
    price_bdt: 40000,
    price_display_text: "BDT 40,000",
    processor: "Snapdragon 730G",
    gpu: "Adreno 618",
    display_type: "Super AMOLED Plus",
    screen_size: "6.7 inches",
    refresh_rate: "60Hz",
    brightness: "420 nits",
    cam_count: "Quad",
    cam_main_sensor: "64 MP, f/1.8, PDAF",
    video_recording: "4K@30fps, 1080p@30fps",
    battery_capacity: "7000 mAh",
    charging_wired: "25W wired",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "213 g",
    dimensions: "163.9 x 76.3 x 9.5 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Mid-Range",
    performance_tier: "Mainstream",
    camera_tier: "Good",
    battery_tier: "Endurance",
    internal_links: { same_brand: ["samsung-galaxy-m31s"] },
    ...commonSeoFields("Galaxy M51", 350),
    overview: "The Galaxy M51 is famously known in the smartphone community as the 'Battery Monster'. It houses an unbelievably massive 7000mAh battery, which is practically unheard of in mainstream smartphones. This allows for an absurd 2 to 3 days of heavy usage on a single charge. Beyond the battery, it features a huge 6.7-inch Super AMOLED Plus display and is powered by the highly reliable Snapdragon 730G processor, making it surprisingly capable for gaming as well. Naturally, packing such a huge battery makes it quite thick and heavy, but for road warriors and power users, the trade-off is absolutely worth it.",
    highlights: ["Massive 7000mAh Battery", "Snapdragon 730G Processor", "6.7-inch Super AMOLED Display"],
    pros: ["Unmatched, legendary battery life", "Excellent display for media", "Solid mid-range gaming performance"],
    cons: ["Very thick and heavy", "Plastic build feels cheap"],
    verdict: "If you despise charging your phone and want a device that simply refuses to die, the M51 is the ultimate choice."
  },
  {
    name: "Galaxy M31s",
    slug: "samsung-galaxy-m31s",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Mirage Blue", "Mirage Black"],
    release_date: "2020-08-06",
    price_usd: 270,
    price_bdt: 30000,
    price_display_text: "BDT 30,000",
    processor: "Exynos 9611",
    gpu: "Mali-G72 MP3",
    display_type: "Super AMOLED",
    screen_size: "6.5 inches",
    refresh_rate: "60Hz",
    brightness: "420 nits",
    cam_count: "Quad",
    cam_main_sensor: "64 MP, f/1.8, PDAF",
    video_recording: "4K@30fps, 1080p@30fps",
    battery_capacity: "6000 mAh",
    charging_wired: "25W wired",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "203 g",
    dimensions: "159.3 x 74.4 x 9.3 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Budget",
    performance_tier: "Basic",
    camera_tier: "Good",
    battery_tier: "Endurance",
    internal_links: { same_brand: ["samsung-galaxy-m31", "samsung-galaxy-m51"] },
    ...commonSeoFields("Galaxy M31s", 270),
    overview: "The Galaxy M31s was a highly refined update to the wildly popular M31. It addressed the biggest complaint of its predecessor by ditching the outdated waterdrop notch in favor of a modern, center-aligned 'Infinity-O' hole-punch cutout, making the 6.5-inch Super AMOLED display look significantly more premium. It retained the enormous 6000mAh battery but upgraded the charging speed from 15W to a much more respectable 25W. The 64MP quad-camera setup also saw the introduction of the 'Single Take' feature, previously reserved for S-series flagships.",
    highlights: ["6000mAh Battery with 25W charging", "Infinity-O Super AMOLED Display", "64MP Quad Camera"],
    pros: ["Fantastic battery endurance", "Beautiful modern display", "Good camera performance for the price"],
    cons: ["Exynos 9611 processor was starting to show its age", "Plastic 'Glasstic' back scratches easily"],
    verdict: "A perfect blend of modern aesthetics, gorgeous display, and outstanding battery life for budget-conscious users."
  },
  {
    name: "Galaxy M31",
    slug: "samsung-galaxy-m31",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Ocean Blue", "Space Black", "Red"],
    release_date: "2020-03-05",
    price_usd: 230,
    price_bdt: 25000,
    price_display_text: "BDT 25,000",
    processor: "Exynos 9611",
    gpu: "Mali-G72 MP3",
    display_type: "Super AMOLED",
    screen_size: "6.4 inches",
    refresh_rate: "60Hz",
    brightness: "420 nits",
    cam_count: "Quad",
    cam_main_sensor: "64 MP, f/1.8, PDAF",
    video_recording: "4K@30fps, 1080p@30fps",
    battery_capacity: "6000 mAh",
    charging_wired: "15W wired",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "191 g",
    dimensions: "159.2 x 75.1 x 8.9 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Budget",
    performance_tier: "Basic",
    camera_tier: "Good",
    battery_tier: "Endurance",
    internal_links: { same_brand: ["samsung-galaxy-m31s", "samsung-galaxy-m30s"] },
    ...commonSeoFields("Galaxy M31", 230),
    overview: "The Galaxy M31 cemented Samsung's dominance in the budget battery-king segment in early 2020. It essentially took the highly successful formula of the M30s and upgraded the main camera to a much sharper 64MP sensor while adding a dedicated macro lens. The 6.4-inch Super AMOLED screen provided deep blacks and vibrant colors, making it excellent for Netflix and YouTube bingeing. Powered by the Exynos 9611 and fueled by a massive 6000mAh battery, it could easily last two full days on a single charge, though the included 15W charger took an agonizingly long time to refill it.",
    highlights: ["6000mAh Battery", "64MP Quad Camera", "Vibrant Super AMOLED Display"],
    pros: ["Incredible battery life", "Great screen for media consumption", "Reliable daily performance"],
    cons: ["15W charging is far too slow for a 6000mAh battery", "Outdated waterdrop notch design"],
    verdict: "A reliable, no-nonsense budget smartphone that prioritizes battery life and screen quality above all else."
  },
  {
    name: "Galaxy M21",
    slug: "samsung-galaxy-m21",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Midnight Blue", "Raven Black"],
    release_date: "2020-03-23",
    price_usd: 180,
    price_bdt: 20000,
    price_display_text: "BDT 20,000",
    processor: "Exynos 9611",
    gpu: "Mali-G72 MP3",
    display_type: "Super AMOLED",
    screen_size: "6.4 inches",
    refresh_rate: "60Hz",
    brightness: "420 nits",
    cam_count: "Triple",
    cam_main_sensor: "48 MP, f/2.0, PDAF",
    video_recording: "4K@30fps, 1080p@30fps",
    battery_capacity: "6000 mAh",
    charging_wired: "15W wired",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "188 g",
    dimensions: "159 x 75.1 x 8.9 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Budget",
    performance_tier: "Basic",
    camera_tier: "Basic",
    battery_tier: "Endurance",
    internal_links: { same_brand: ["samsung-galaxy-m31", "samsung-galaxy-m11"] },
    ...commonSeoFields("Galaxy M21", 180),
    overview: "The Galaxy M21 was arguably the smartest purchase in Samsung's 2020 budget lineup. It was virtually identical to the more expensive M31, sharing the exact same Exynos 9611 processor, the same stunning 6.4-inch Super AMOLED display, and the same massive 6000mAh battery. The only meaningful difference was a slight downgrade in the camera department—featuring a 48MP main sensor instead of 64MP, and dropping the mostly useless macro lens. For users who cared more about battery, performance, and screen quality than extreme camera specs, the M21 was an absolute steal.",
    highlights: ["Super AMOLED Display", "6000mAh Battery", "Identical performance to the M31"],
    pros: ["Outstanding value for money", "Two-day battery life", "Great media consumption device"],
    cons: ["Very slow 15W charging", "Cameras struggle in low light"],
    verdict: "The hidden gem of the M-series. It offered 90% of the M31's experience for a noticeably cheaper price."
  },
  {
    name: "Galaxy M11",
    slug: "samsung-galaxy-m11",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Black", "Metallic Blue", "Violet"],
    release_date: "2020-05-04",
    price_usd: 140,
    price_bdt: 15000,
    price_display_text: "BDT 15,000",
    processor: "Snapdragon 450",
    gpu: "Adreno 506",
    display_type: "PLS LCD",
    screen_size: "6.4 inches",
    refresh_rate: "60Hz",
    brightness: "400 nits",
    cam_count: "Triple",
    cam_main_sensor: "13 MP, f/1.8, PDAF",
    video_recording: "1080p@30fps",
    battery_capacity: "5000 mAh",
    charging_wired: "15W wired",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "197 g",
    dimensions: "161.4 x 76.3 x 9 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Entry-Level",
    performance_tier: "Basic",
    camera_tier: "Basic",
    battery_tier: "Long-Lasting",
    internal_links: { same_brand: ["samsung-galaxy-m21"] },
    ...commonSeoFields("Galaxy M11", 140),
    overview: "The Galaxy M11 was designed as the most affordable entry point into the M-series. To hit its extremely low price point, Samsung had to make significant compromises. It swapped out the beloved Super AMOLED screen for a basic PLS LCD panel with a lower 720p resolution. It also utilized the highly entry-level Snapdragon 450 processor, which was adequate for basic texting and web browsing but struggled heavily with gaming or intensive multitasking. On the positive side, it featured a modern hole-punch display design and a robust 5000mAh battery that easily lasted a full day.",
    highlights: ["5000mAh Battery", "Modern hole-punch design", "Affordable entry price"],
    pros: ["Good battery life", "Looks more modern than its price suggests", "Includes a headphone jack"],
    cons: ["Very weak processor", "Low-resolution LCD screen", "Cameras are poor"],
    verdict: "A strictly basic smartphone meant only for light users who need Samsung reliability and good battery life on a very tight budget."
  },
  {
    name: "Galaxy M30s",
    slug: "samsung-galaxy-m30s",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Opal Black", "Sapphire Blue", "Pearl White"],
    release_date: "2019-09-18",
    price_usd: 220,
    price_bdt: 24000,
    price_display_text: "BDT 24,000",
    processor: "Exynos 9611",
    gpu: "Mali-G72 MP3",
    display_type: "Super AMOLED",
    screen_size: "6.4 inches",
    refresh_rate: "60Hz",
    brightness: "420 nits",
    cam_count: "Triple",
    cam_main_sensor: "48 MP, f/2.0, PDAF",
    video_recording: "4K@30fps, 1080p@30fps",
    battery_capacity: "6000 mAh",
    charging_wired: "15W wired",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "188 g",
    dimensions: "159 x 75.1 x 8.9 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Budget",
    performance_tier: "Basic",
    camera_tier: "Basic",
    battery_tier: "Endurance",
    internal_links: { same_brand: ["samsung-galaxy-m30", "samsung-galaxy-m31"] },
    ...commonSeoFields("Galaxy M30s", 220),
    overview: "The Galaxy M30s was the phone that truly put the M-series on the map. It was the very first Samsung device to introduce the monstrous 6000mAh battery, setting a new industry standard for budget battery endurance. It also debuted the Exynos 9611 processor, which would go on to power several subsequent Samsung budget phones. Combined with a brilliant Super AMOLED display and a very capable 48MP triple camera system, the M30s became an instant bestseller, offering an incredible balance of multimedia features and unstoppable battery life.",
    highlights: ["First Samsung with 6000mAh battery", "Super AMOLED Display", "48MP Triple Camera"],
    pros: ["Revolutionary battery life for its time", "Vibrant, sharp display", "Solid mid-range processor"],
    cons: ["Very slow charging", "Plastic back prone to scratching"],
    verdict: "A highly influential device that established Samsung's dominance in the 'battery king' budget smartphone market."
  },
  {
    name: "Galaxy M30",
    slug: "samsung-galaxy-m30",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Black", "Blue"],
    release_date: "2019-03-07",
    price_usd: 200,
    price_bdt: 22000,
    price_display_text: "BDT 22,000",
    processor: "Exynos 7904",
    gpu: "Mali-G71 MP2",
    display_type: "Super AMOLED",
    screen_size: "6.4 inches",
    refresh_rate: "60Hz",
    brightness: "400 nits",
    cam_count: "Triple",
    cam_main_sensor: "13 MP, f/1.9, PDAF",
    video_recording: "1080p@30fps",
    battery_capacity: "5000 mAh",
    charging_wired: "15W wired",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "174 g",
    dimensions: "159 x 75.1 x 8.5 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Budget",
    performance_tier: "Basic",
    camera_tier: "Basic",
    battery_tier: "Long-Lasting",
    internal_links: { same_brand: ["samsung-galaxy-m20", "samsung-galaxy-m30s"] },
    ...commonSeoFields("Galaxy M30", 200),
    overview: "The original Galaxy M30 was one of the founding members of the M-series lineup, aimed at fighting off aggressive competition from Chinese brands. Its primary selling point was offering Samsung's trademark Super AMOLED display at an incredibly aggressive price point. It featured a large 5000mAh battery and a versatile triple camera setup including an ultra-wide lens. However, it was powered by the relatively weak Exynos 7904 processor, which meant it was better suited for media consumption than gaming.",
    highlights: ["Super AMOLED Display", "5000mAh Battery", "Ultra-wide camera lens"],
    pros: ["Great display quality for the price", "Excellent battery endurance", "Lightweight design"],
    cons: ["Underwhelming processor performance", "Average camera quality"],
    verdict: "A solid first attempt at a budget multimedia phone, later perfected by the much superior M30s."
  },
  {
    name: "Galaxy M20",
    slug: "samsung-galaxy-m20",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Ocean Blue", "Charcoal Black"],
    release_date: "2019-02-05",
    price_usd: 150,
    price_bdt: 16500,
    price_display_text: "BDT 16,500",
    processor: "Exynos 7904",
    gpu: "Mali-G71 MP2",
    display_type: "PLS LCD",
    screen_size: "6.3 inches",
    refresh_rate: "60Hz",
    brightness: "400 nits",
    cam_count: "Dual",
    cam_main_sensor: "13 MP, f/1.9, PDAF",
    video_recording: "1080p@30fps",
    battery_capacity: "5000 mAh",
    charging_wired: "15W wired",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "186 g",
    dimensions: "156.4 x 74.5 x 8.8 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Entry-Level",
    performance_tier: "Basic",
    camera_tier: "Basic",
    battery_tier: "Long-Lasting",
    internal_links: { same_brand: ["samsung-galaxy-m10", "samsung-galaxy-m30"] },
    ...commonSeoFields("Galaxy M20", 150),
    overview: "Launched alongside the M10, the Galaxy M20 represented a massive shift in Samsung's budget strategy. It was one of the first Samsung phones to feature the 'Infinity-V' waterdrop notch display, modernizing the look of their budget lineup. It prioritized endurance above all else, packing a massive 5000mAh battery that delivered exceptional screen-on time. It featured a PLS LCD display instead of AMOLED to keep costs down, but it offered a full 1080p resolution, making it sharp and crisp. It was a highly practical, no-nonsense phone designed for the masses.",
    highlights: ["5000mAh Battery", "1080p Infinity-V Display", "Ultra-wide dual camera"],
    pros: ["Excellent battery life", "Sharp 1080p display", "Modern design for a budget phone"],
    cons: ["LCD screen lacks the punch of AMOLED", "Cameras were very basic"],
    verdict: "A highly practical budget workhorse that prioritized battery and screen sharpness over premium aesthetics."
  },
  {
    name: "Galaxy M10",
    slug: "samsung-galaxy-m10",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Ocean Blue", "Charcoal Black"],
    release_date: "2019-02-05",
    price_usd: 110,
    price_bdt: 12000,
    price_display_text: "BDT 12,000",
    processor: "Exynos 7870",
    gpu: "Mali-T830 MP1",
    display_type: "PLS LCD",
    screen_size: "6.22 inches",
    refresh_rate: "60Hz",
    brightness: "400 nits",
    cam_count: "Dual",
    cam_main_sensor: "13 MP, f/1.9, PDAF",
    video_recording: "1080p@30fps",
    battery_capacity: "3400 mAh",
    charging_wired: "Standard",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "163 g",
    dimensions: "155.6 x 75.6 x 7.7 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Entry-Level",
    performance_tier: "Basic",
    camera_tier: "Basic",
    battery_tier: "Basic",
    internal_links: { same_brand: ["samsung-galaxy-m20"] },
    ...commonSeoFields("Galaxy M10", 110),
    overview: "The Galaxy M10 was the absolute entry point to the new M-series revolution. It was designed to offer the absolute bare minimum for a functioning modern smartphone while maintaining the Samsung brand name. It featured a 720p PLS LCD display, an older Exynos 7870 processor, and a modest 3400mAh battery. The inclusion of an ultra-wide camera lens was its only standout feature at this price point. It was extremely lightweight and comfortable to hold, but performance was strictly limited to basic tasks like calling, WhatsApp, and light web browsing.",
    highlights: ["Very affordable entry price", "Ultra-wide camera lens", "Infinity-V display design"],
    pros: ["Sleek and lightweight", "Modern waterdrop notch design", "Ultra-wide lens is rare at this price"],
    cons: ["Extremely slow performance", "Small battery", "Low 720p resolution"],
    verdict: "A phone meant only for first-time smartphone buyers or as a secondary backup device."
  }
];

async function run() {
  try {
    await mongoose.connect(MONGODB_URI as string);
    console.log("✅ Connected to MongoDB");

    const Brand = mongoose.models.Brand || mongoose.model("Brand", new mongoose.Schema({}, { strict: false }));
    const samsungBrand = await Brand.findOne({ name: /Samsung/i });

    const PhoneSchema = new mongoose.Schema({}, { strict: false });
    const Phone = mongoose.models.Phone || mongoose.model("Phone", PhoneSchema);

    for (const phone of phonesData) {
      if (samsungBrand) (phone as any).brand_id = samsungBrand._id;
      phone.updated_at = new Date() as any;
      await Phone.findOneAndUpdate({ slug: phone.slug }, { $set: phone }, { upsert: true, new: true });
      console.log(`✅ Inserted/Updated: ${phone.name}`);
    }

    console.log("🎉 Samsung Batch 9 (Classic M Series) completed! Added 9 phones with strict specs.");

  } catch (err) {
    console.error("❌ Error:", (err as Error).message);
  } finally {
    await mongoose.disconnect();
  }
}

run();
