import mongoose from 'mongoose';
import * as dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.resolve(process.cwd(), '.env.local') });

const MONGODB_URI = process.env.MONGODB_URI;

const commonSeoFields = (name: string, price: number, keywordSuffix: string = 'price in bd') => ({
  meta_title: `Samsung ${name} Price in Bangladesh, Specs & Review`,
  meta_keywords: `samsung ${name.toLowerCase()}, ${name.toLowerCase()} price in bd, samsung bangladesh, ${name.toLowerCase()} specs, classic flagship`,
  meta_description: `Official and Unofficial Samsung ${name} price in Bangladesh. Discover its premium features, stylus support, display quality, and full specifications.`,
  canonical_url: `https://www.techtweak.tech/phones/samsung/samsung-${name.toLowerCase().replace(/ /g, '-')}`,
  primary_keyword: `samsung ${name.toLowerCase()} ${keywordSuffix}`,
  secondary_keywords: [`samsung ${name.toLowerCase()} price`, `samsung ${name.toLowerCase()} specs`, `samsung ${name.toLowerCase()} review`],
  question_keywords: [
    `what is the price of samsung ${name.toLowerCase()} in bangladesh?`,
    `does samsung ${name.toLowerCase()} support s pen?`,
    `is samsung ${name.toLowerCase()} good for gaming?`
  ],
  faq_schema: [
    { question: `What is the price of Samsung ${name} in Bangladesh?`, answer: `The Samsung ${name} was originally priced around BDT ${price * 115}. Currently, it may only be available in the used or refurbished market.` },
    { question: `Does the Samsung ${name} have an S Pen?`, answer: `Please refer to the hardware specifications below. Generally, all Galaxy Note models and modern S Ultra/Fold models support the S Pen.` },
    { question: `Is the Samsung ${name} waterproof?`, answer: `Yes, most Samsung premium flagships carry an IP68 water and dust resistance rating, though this protection diminishes over time.` }
  ]
});

const phonesData = [
  {
    name: "Galaxy Note 20 Ultra 5G",
    slug: "samsung-galaxy-note-20-ultra-5g",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Mystic Bronze", "Mystic Black", "Mystic White"],
    release_date: "2020-08-21",
    price_usd: 1299,
    price_bdt: 135000,
    price_display_text: "BDT 135,000",
    processor: "Exynos 990 / Snapdragon 865 5G+",
    gpu: "Mali-G77 MP11 / Adreno 650",
    display_type: "Dynamic AMOLED 2X, 120Hz",
    screen_size: "6.9 inches",
    refresh_rate: "120Hz",
    brightness: "1500 nits (peak)",
    cam_count: "Triple",
    cam_main_sensor: "108 MP, f/1.8, OIS, Laser AF",
    video_recording: "8K@24fps, 4K@30/60fps",
    battery_capacity: "4500 mAh",
    charging_wired: "25W wired",
    wireless_charging: "15W wireless, 4.5W reverse wireless",
    ip_rating: "IP68 dust/water resistant",
    weight: "208 g",
    dimensions: "164.8 x 77.2 x 8.1 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Ultra Premium",
    performance_tier: "Mainstream",
    camera_tier: "Pro",
    battery_tier: "Standard",
    internal_links: { same_brand: ["samsung-galaxy-note-10-plus", "samsung-galaxy-s21-ultra-5g"] },
    ...commonSeoFields("Galaxy Note 20 Ultra 5G", 1299),
    overview: "The Samsung Galaxy Note 20 Ultra 5G is the ultimate power user's smartphone, and sadly, the very last device to bear the iconic 'Note' moniker before Samsung merged the lineup into the S Ultra series. It introduced a striking, sharp-cornered design adorned in a beautiful Mystic Bronze matte finish. The massive 6.9-inch Dynamic AMOLED 2X display runs at a buttery 120Hz and integrates a vastly improved S Pen with ultra-low latency, making writing feel almost like real paper. On the back, an enormous 108MP camera dominates the module, capable of stunning zoom and 8K video recording. Powered by flagship silicon and featuring Dex support, it is basically a pocket-sized computer.",
    highlights: ["Ultra-low latency S Pen", "Massive 6.9-inch 120Hz display", "108MP Camera with 50x Space Zoom"],
    pros: ["The best S Pen experience", "Gorgeous matte design", "Stunningly massive display"],
    cons: ["Battery life is mediocre", "Exynos variant thermal throttles heavily"],
    verdict: "A legendary final entry for the Note series. It remains a fantastic choice for productivity enthusiasts who absolutely need an integrated stylus."
  },
  {
    name: "Galaxy Note 20",
    slug: "samsung-galaxy-note-20",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Mystic Green", "Mystic Bronze", "Mystic Gray"],
    release_date: "2020-08-21",
    price_usd: 999,
    price_bdt: 95000,
    price_display_text: "BDT 95,000",
    processor: "Exynos 990 / Snapdragon 865 5G+",
    gpu: "Mali-G77 MP11 / Adreno 650",
    display_type: "Super AMOLED",
    screen_size: "6.7 inches",
    refresh_rate: "60Hz",
    brightness: "1200 nits (peak)",
    cam_count: "Triple",
    cam_main_sensor: "12 MP, f/1.8, OIS",
    video_recording: "8K@24fps, 4K@30/60fps",
    battery_capacity: "4300 mAh",
    charging_wired: "25W wired",
    wireless_charging: "15W wireless, 4.5W reverse wireless",
    ip_rating: "IP68 dust/water resistant",
    weight: "192 g",
    dimensions: "161.6 x 75.2 x 8.3 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Flagship",
    performance_tier: "Mainstream",
    camera_tier: "Excellent",
    battery_tier: "Basic",
    internal_links: { same_brand: ["samsung-galaxy-note-20-ultra-5g", "samsung-galaxy-note-10"] },
    ...commonSeoFields("Galaxy Note 20", 999),
    overview: "The standard Samsung Galaxy Note 20 launched as a slightly controversial sibling to the Ultra model. While it retains the core productivity features like the S Pen and top-tier processor, Samsung made noticeable compromises to hit a lower price point. Most notably, it features a 60Hz flat display and a 'glasstic' (plastic) back panel instead of premium glass. Despite these downgrades, the Note 20 is still a highly capable machine. The triple camera system performs excellently in all conditions, and the flat screen is actually preferred by many S Pen users as it prevents the pen from slipping off the edges while drawing or writing.",
    highlights: ["Integrated S Pen", "Flagship Processor", "Excellent Triple Camera Setup"],
    pros: ["Flat screen is great for writing", "Reliable camera performance", "Lighter than the Ultra"],
    cons: ["Only a 60Hz display", "Plastic back at a premium price point"],
    verdict: "A solid productivity phone, but it lacked the premium materials and 120Hz screen expected at its flagship launch price."
  },
  {
    name: "Galaxy Note 10+",
    slug: "samsung-galaxy-note-10-plus",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Aura Glow", "Aura White", "Aura Black", "Aura Blue"],
    release_date: "2019-08-23",
    price_usd: 1099,
    price_bdt: 110000,
    price_display_text: "BDT 110,000",
    processor: "Exynos 9825 / Snapdragon 855",
    gpu: "Mali-G76 MP12 / Adreno 640",
    display_type: "Dynamic AMOLED",
    screen_size: "6.8 inches",
    refresh_rate: "60Hz",
    brightness: "1200 nits (peak)",
    cam_count: "Quad",
    cam_main_sensor: "12 MP, f/1.5-2.4 (variable), OIS",
    video_recording: "4K@30/60fps, 1080p@30/60/240fps",
    battery_capacity: "4300 mAh",
    charging_wired: "45W wired",
    wireless_charging: "15W wireless, 4.5W reverse wireless",
    ip_rating: "IP68 dust/water resistant",
    weight: "196 g",
    dimensions: "162.3 x 77.2 x 7.9 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Flagship",
    performance_tier: "Basic",
    camera_tier: "Excellent",
    battery_tier: "Basic",
    internal_links: { same_brand: ["samsung-galaxy-note-10", "samsung-galaxy-note-9"] },
    ...commonSeoFields("Galaxy Note 10+", 1099),
    overview: "The Galaxy Note 10+ is widely considered one of the most beautiful smartphones Samsung has ever crafted, largely thanks to the mesmerizing, iridescent 'Aura Glow' colorway. It introduced a near bezel-less 6.8-inch Dynamic AMOLED display with a tiny, centered hole-punch camera. This generation brought Air Actions to the S Pen, allowing users to control the phone with magic-wand-like gestures. It also featured a cutting-edge dual-aperture 12MP main camera that physically adjusted its lens to adapt to lighting conditions. With 45W fast charging and an incredibly sleek 7.9mm profile, the Note 10+ set the gold standard for premium aesthetics in 2019.",
    highlights: ["Stunning Aura Glow finish", "S Pen with Air Actions", "Dual-aperture main camera"],
    pros: ["One of the best-looking phones ever made", "Extremely thin and light for its size", "Great display"],
    cons: ["First Note to remove the headphone jack", "Battery life was average"],
    verdict: "A masterpiece of smartphone design. The Note 10+ remains an iconic device that perfected the modern phablet aesthetic."
  },
  {
    name: "Galaxy Note 10",
    slug: "samsung-galaxy-note-10",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Aura Glow", "Aura White", "Aura Black", "Aura Pink", "Aura Red"],
    release_date: "2019-08-23",
    price_usd: 949,
    price_bdt: 90000,
    price_display_text: "BDT 90,000",
    processor: "Exynos 9825 / Snapdragon 855",
    gpu: "Mali-G76 MP12 / Adreno 640",
    display_type: "Dynamic AMOLED",
    screen_size: "6.3 inches",
    refresh_rate: "60Hz",
    brightness: "1200 nits (peak)",
    cam_count: "Triple",
    cam_main_sensor: "12 MP, f/1.5-2.4, OIS",
    video_recording: "4K@30/60fps, 1080p@30/60/240fps",
    battery_capacity: "3500 mAh",
    charging_wired: "25W wired",
    wireless_charging: "12W wireless, 4.5W reverse wireless",
    ip_rating: "IP68 dust/water resistant",
    weight: "168 g",
    dimensions: "151 x 71.8 x 7.9 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Premium Mid-Range",
    performance_tier: "Basic",
    camera_tier: "Good",
    battery_tier: "Basic",
    internal_links: { same_brand: ["samsung-galaxy-note-10-plus", "samsung-galaxy-note-10-lite"] },
    ...commonSeoFields("Galaxy Note 10", 949),
    overview: "The Galaxy Note 10 was a unique experiment by Samsung: cramming the full Note experience into a compact, one-handed form factor. At just 6.3 inches and 168 grams, it is arguably the most comfortable Note device ever built. Despite its small size, it retains the full-featured S Pen, the powerful flagship processor, and the versatile triple camera system from the Plus model. However, the compact size required significant sacrifices: it features a much smaller 3500mAh battery and a lower-resolution 1080p display. Even with these drawbacks, it offered a rare blend of stylus productivity in a genuinely pocketable design.",
    highlights: ["Compact 6.3-inch design", "Full S Pen capabilities", "Stunning aesthetic build"],
    pros: ["Extremely comfortable to hold", "Beautiful display despite 1080p resolution", "Great cameras"],
    cons: ["Very poor battery life", "No microSD card slot"],
    verdict: "The perfect device for those who always wanted an S Pen but hated dealing with massive, bulky smartphones."
  },
  {
    name: "Galaxy Note 10 Lite",
    slug: "samsung-galaxy-note-10-lite",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Aura Glow", "Aura Black", "Aura Red"],
    release_date: "2020-01-21",
    price_usd: 500,
    price_bdt: 45000,
    price_display_text: "BDT 45,000",
    processor: "Exynos 9810",
    gpu: "Mali-G72 MP18",
    display_type: "Super AMOLED",
    screen_size: "6.7 inches",
    refresh_rate: "60Hz",
    brightness: "800 nits",
    cam_count: "Triple",
    cam_main_sensor: "12 MP, f/1.7, Dual Pixel PDAF, OIS",
    video_recording: "4K@30/60fps, 1080p@30/60/240fps",
    battery_capacity: "4500 mAh",
    charging_wired: "25W wired",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "199 g",
    dimensions: "163.7 x 76.1 x 8.7 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Mid-Range",
    performance_tier: "Basic",
    camera_tier: "Basic",
    battery_tier: "Standard",
    internal_links: { same_brand: ["samsung-galaxy-note-10", "samsung-galaxy-s10-lite"] },
    ...commonSeoFields("Galaxy Note 10 Lite", 500),
    overview: "The Galaxy Note 10 Lite was designed to bring the highly coveted S Pen experience to a more accessible price bracket. To achieve this, Samsung utilized the older Exynos 9810 processor (from the Galaxy S9 era) and wrapped the device in a plastic body. However, where it truly matters, the Note 10 Lite delivers: it features a large, flat 6.7-inch Super AMOLED screen that is perfect for drawing and note-taking, and a robust 4500mAh battery that easily outlasts the standard Note 10. Crucially, it also retains the 3.5mm headphone jack, a feature noticeably absent from its more premium siblings.",
    highlights: ["Affordable S Pen access", "Large 4500mAh battery", "Retains the 3.5mm headphone jack"],
    pros: ["Best value for S Pen users", "Flat screen is ideal for writing", "Good battery life"],
    cons: ["Uses a highly outdated processor", "No water resistance"],
    verdict: "An excellent budget-friendly entry point into the Note ecosystem, prioritizing the S Pen and battery life over raw processing power."
  },
  {
    name: "Galaxy Note 9",
    slug: "samsung-galaxy-note-9",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Metallic Copper", "Lavender Purple", "Ocean Blue", "Midnight Black"],
    release_date: "2018-08-24",
    price_usd: 999,
    price_bdt: 85000,
    price_display_text: "BDT 85,000",
    processor: "Exynos 9810 / Snapdragon 845",
    gpu: "Mali-G72 MP18 / Adreno 630",
    display_type: "Super AMOLED",
    screen_size: "6.4 inches",
    refresh_rate: "60Hz",
    brightness: "1050 nits",
    cam_count: "Dual",
    cam_main_sensor: "12 MP, f/1.5-2.4 (variable), OIS",
    video_recording: "4K@30/60fps, 1080p@30/60/240fps",
    battery_capacity: "4000 mAh",
    charging_wired: "15W wired",
    wireless_charging: "15W wireless",
    ip_rating: "IP68 dust/water resistant",
    weight: "201 g",
    dimensions: "161.9 x 76.4 x 8.8 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Premium Mid-Range",
    performance_tier: "Basic",
    camera_tier: "Basic",
    battery_tier: "Standard",
    internal_links: { same_brand: ["samsung-galaxy-note-10-plus", "samsung-galaxy-note-8"] },
    ...commonSeoFields("Galaxy Note 9", 999),
    overview: "Many hardcore Samsung fans still consider the Galaxy Note 9 as the ultimate 'no compromises' smartphone. It was the last major Samsung flagship to include everything without removing features: it boasts a brilliant 1440p AMOLED display without any notches or hole-punches, a massive (for the time) 4000mAh battery, a headphone jack, an iris scanner, a heart rate monitor, and expandable storage. Furthermore, it introduced Bluetooth connectivity to the S Pen, transforming the stylus into a remote control for the camera and presentations. It was thick, heavy, and built like an absolute tank.",
    highlights: ["Bluetooth S Pen", "No-notch display design", "Includes headphone jack & MicroSD"],
    pros: ["A true 'everything-included' flagship", "Excellent dual-aperture camera", "Great battery upgrade over Note 8"],
    cons: ["Very thick and heavy", "Bixby button is poorly placed"],
    verdict: "Widely regarded as the peak of traditional smartphone design before the era of removed features and giant camera bumps began."
  },
  {
    name: "Galaxy Note 8",
    slug: "samsung-galaxy-note-8",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Midnight Black", "Maple Gold", "Orchid Gray", "Deep Sea Blue"],
    release_date: "2017-09-15",
    price_usd: 929,
    price_bdt: 75000,
    price_display_text: "BDT 75,000",
    processor: "Exynos 8895 / Snapdragon 835",
    gpu: "Mali-G71 MP20 / Adreno 540",
    display_type: "Super AMOLED",
    screen_size: "6.3 inches",
    refresh_rate: "60Hz",
    brightness: "1200 nits",
    cam_count: "Dual",
    cam_main_sensor: "12 MP, f/1.7, Dual Pixel PDAF, OIS",
    video_recording: "4K@30fps, 1080p@30/60fps",
    battery_capacity: "3300 mAh",
    charging_wired: "15W wired",
    wireless_charging: "15W wireless",
    ip_rating: "IP68 dust/water resistant",
    weight: "195 g",
    dimensions: "162.5 x 74.8 x 8.6 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Mid-Range",
    performance_tier: "Basic",
    camera_tier: "Basic",
    battery_tier: "Basic",
    internal_links: { same_brand: ["samsung-galaxy-note-9"] },
    ...commonSeoFields("Galaxy Note 8", 929),
    overview: "The Galaxy Note 8 bore the massive responsibility of redeeming the Note brand following the disastrous Note 7 recall, and it succeeded brilliantly. It adopted the stunning 'Infinity Display' design from the S8, stretching the 6.3-inch screen to the very edges of the device. Crucially, it was the first Samsung flagship to introduce a dual-camera system, adding a dedicated telephoto lens for lossless optical zoom and beautiful 'Live Focus' portrait shots. Due to safety precautions, Samsung equipped it with a conservative 3300mAh battery, which impacted its daily endurance, but the device proved incredibly reliable and safe.",
    highlights: ["First Samsung dual-camera", "Infinity Display design", "Highly reliable safety record"],
    pros: ["Redeemed the Note brand successfully", "Excellent telephoto zoom lens", "Premium glass-and-metal build"],
    cons: ["Fingerprint scanner is placed terribly", "Small battery resulted in poor battery life"],
    verdict: "The comeback king that saved the Note brand, offering a gorgeous display and dual cameras, albeit with weak battery life."
  },
  {
    name: "Galaxy Z Fold 3 5G",
    slug: "samsung-galaxy-z-fold-3-5g",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Phantom Black", "Phantom Green", "Phantom Silver"],
    release_date: "2021-08-27",
    price_usd: 1799,
    price_bdt: 160000,
    price_display_text: "BDT 160,000",
    processor: "Snapdragon 888 5G",
    gpu: "Adreno 660",
    display_type: "Foldable Dynamic AMOLED 2X, 120Hz",
    screen_size: "7.6 inches (Unfolded)",
    refresh_rate: "120Hz",
    brightness: "1200 nits",
    cam_count: "Triple",
    cam_main_sensor: "12 MP, f/1.8, OIS",
    video_recording: "4K@60fps",
    battery_capacity: "4400 mAh",
    charging_wired: "25W wired",
    wireless_charging: "11W wireless, 4.5W reverse wireless",
    ip_rating: "IPX8 water resistant",
    weight: "271 g",
    dimensions: "Unfolded: 158.2 x 128.1 x 6.4 mm / Folded: 158.2 x 67.1 x 14.4-16 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Ultra Premium",
    performance_tier: "High-End",
    camera_tier: "Excellent",
    battery_tier: "Standard",
    internal_links: { same_brand: ["samsung-galaxy-z-fold-4", "samsung-galaxy-z-fold-2-5g"] },
    ...commonSeoFields("Galaxy Z Fold 3 5G", 1799),
    overview: "The Galaxy Z Fold 3 5G was a monumental leap forward for foldable smartphones, finally bringing mainstream durability to the form factor. It was the world's first foldable to achieve an IPX8 water resistance rating, meaning it could survive accidental drops in water. Furthermore, it introduced S Pen support to the massive 7.6-inch inner display, transforming it into the ultimate portable tablet for productivity. Samsung also debuted its first Under-Display Camera (UDC) on the inner screen, creating an uninterrupted viewing experience, though the camera quality itself was noticeably muddy.",
    highlights: ["First water-resistant foldable (IPX8)", "S Pen support on inner screen", "Under-Display Camera"],
    pros: ["Massive leap in durability", "Excellent 120Hz screens inside and out", "Great software multitasking"],
    cons: ["Under-display camera is low quality", "Still very bulky when folded"],
    verdict: "The device that proved foldables were ready for the mainstream, fixing the durability issues of its predecessors while adding water resistance."
  },
  {
    name: "Galaxy Z Fold 2 5G",
    slug: "samsung-galaxy-z-fold-2-5g",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Mystic Bronze", "Mystic Black"],
    release_date: "2020-09-18",
    price_usd: 1999,
    price_bdt: 180000,
    price_display_text: "BDT 180,000",
    processor: "Snapdragon 865 5G+",
    gpu: "Adreno 650",
    display_type: "Foldable Dynamic AMOLED 2X, 120Hz",
    screen_size: "7.6 inches (Unfolded)",
    refresh_rate: "120Hz",
    brightness: "1200 nits",
    cam_count: "Triple",
    cam_main_sensor: "12 MP, f/1.8, OIS",
    video_recording: "4K@60fps",
    battery_capacity: "4500 mAh",
    charging_wired: "25W wired",
    wireless_charging: "11W wireless, 4.5W reverse wireless",
    ip_rating: "None",
    weight: "282 g",
    dimensions: "Unfolded: 159.2 x 128.2 x 6.9 mm / Folded: 159.2 x 68 x 16.8 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Ultra Premium",
    performance_tier: "Mainstream",
    camera_tier: "Excellent",
    battery_tier: "Standard",
    internal_links: { same_brand: ["samsung-galaxy-z-fold-3-5g"] },
    ...commonSeoFields("Galaxy Z Fold 2 5G", 1999),
    overview: "After the rocky launch of the original Fold, the Galaxy Z Fold 2 arrived as a massive course correction that showed the true potential of the foldable concept. It completely redesigned the hinge, introducing the 'Flex Mode' which allowed the phone to sit open like a tiny laptop. More importantly, it ditched the tiny cover screen of the original for a much more usable 6.2-inch outer display. The fragile plastic inner screen was replaced with Ultra-Thin Glass (UTG), making the 7.6-inch 120Hz inner display look and feel significantly more premium.",
    highlights: ["Massive outer display upgrade", "Ultra-Thin Glass (UTG)", "Flex Mode hinge"],
    pros: ["Huge improvement over the original Fold", "Beautiful Mystic Bronze aesthetic", "Great multitasking"],
    cons: ["No water or dust resistance", "Extremely expensive at launch"],
    verdict: "The phone that established the modern blueprint for the book-style foldable, turning a fragile concept into a highly usable luxury device."
  },
  {
    name: "Galaxy Z Flip 3 5G",
    slug: "samsung-galaxy-z-flip-3-5g",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Phantom Black", "Green", "Lavender", "Cream"],
    release_date: "2021-08-27",
    price_usd: 999,
    price_bdt: 95000,
    price_display_text: "BDT 95,000",
    processor: "Snapdragon 888 5G",
    gpu: "Adreno 660",
    display_type: "Foldable Dynamic AMOLED 2X, 120Hz",
    screen_size: "6.7 inches (Unfolded)",
    refresh_rate: "120Hz",
    brightness: "1200 nits",
    cam_count: "Dual",
    cam_main_sensor: "12 MP, f/1.8, OIS",
    video_recording: "4K@60fps",
    battery_capacity: "3300 mAh",
    charging_wired: "15W wired",
    wireless_charging: "10W wireless, 4.5W reverse wireless",
    ip_rating: "IPX8 water resistant",
    weight: "183 g",
    dimensions: "Unfolded: 166 x 72.2 x 6.9 mm / Folded: 86.4 x 72.2 x 15.9-17.1 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Flagship",
    performance_tier: "High-End",
    camera_tier: "Good",
    battery_tier: "Basic",
    internal_links: { same_brand: ["samsung-galaxy-z-flip-4", "samsung-galaxy-z-fold-3-5g"] },
    ...commonSeoFields("Galaxy Z Flip 3 5G", 999),
    overview: "The Galaxy Z Flip 3 5G is the device that made foldable phones cool and accessible. Dropping the starting price below the $1000 mark for the first time, it offered a chic, compact clamshell design adorned in trendy two-tone colors. It featured a newly expanded outer cover screen that was actually useful for reading notifications and controlling music without opening the phone. Like its Fold sibling, it achieved an IPX8 water resistance rating. While its tiny 3300mAh battery struggled to make it through a full day, the device was wildly popular for its nostalgic yet futuristic form factor.",
    highlights: ["First foldable under $1000", "IPX8 water resistant", "Expanded cover screen"],
    pros: ["Extremely stylish and compact", "Water resistance adds peace of mind", "Fun to use"],
    cons: ["Terrible battery life", "Cameras are just average"],
    verdict: "A fashion-forward clamshell that brought foldables to the masses by nailing the price and the aesthetic, despite its battery woes."
  }
];

async function run() {
  try {
    await mongoose.connect(MONGODB_URI as string);
    console.log("✅ Connected to MongoDB");

    const Brand = mongoose.models.Brand || mongoose.model("Brand", new mongoose.Schema({}, { strict: false }));
    const samsungBrand = await Brand.findOne({ name: /Samsung/i });

    const PhoneSchema = new mongoose.Schema({}, { strict: false });
    const Phone = mongoose.models.Phone || mongoose.model("Phone", PhoneSchema);

    for (const phone of phonesData) {
      if (samsungBrand) (phone as any).brand_id = samsungBrand._id;
      phone.updated_at = new Date() as any;
      await Phone.findOneAndUpdate({ slug: phone.slug }, { $set: phone }, { upsert: true, new: true });
      console.log(`✅ Inserted/Updated: ${phone.name}`);
    }

    console.log("🎉 Samsung Batch 7 (Note Series & Foldables) completed! Added 10 phones with 100% strict spec adherence.");

  } catch (err) {
    console.error("❌ Error:", (err as Error).message);
  } finally {
    await mongoose.disconnect();
  }
}

run();
