import mongoose from 'mongoose';
import * as dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.resolve(process.cwd(), '.env.local') });

const MONGODB_URI = process.env.MONGODB_URI;

const commonSeoFields = (name: string, price: number, keywordSuffix: string = 'price in bd') => ({
  meta_title: `Samsung ${name} Price in Bangladesh, Specs & Review`,
  meta_keywords: `samsung ${name.toLowerCase()}, ${name.toLowerCase()} price in bd, samsung bangladesh, ${name.toLowerCase()} specs, classic budget phone`,
  meta_description: `Official and Unofficial Samsung ${name} price in Bangladesh. Discover its full specifications, nostalgic review, and detailed hardware info.`,
  canonical_url: `https://www.techtweak.tech/phones/samsung/samsung-${name.toLowerCase().replace(/ /g, '-')}`,
  primary_keyword: `samsung ${name.toLowerCase()} ${keywordSuffix}`,
  secondary_keywords: [`samsung ${name.toLowerCase()} price`, `samsung ${name.toLowerCase()} specs`, `samsung ${name.toLowerCase()} review`],
  question_keywords: [
    `what is the price of samsung ${name.toLowerCase()} in bangladesh?`,
    `is samsung ${name.toLowerCase()} still a good phone?`,
    `does samsung ${name.toLowerCase()} support 4g?`
  ],
  faq_schema: [
    { question: `What is the price of Samsung ${name} in Bangladesh?`, answer: `The Samsung ${name} originally launched at around BDT ${price * 115}. Currently, it is mostly available in the second-hand market.` },
    { question: `Is the Samsung ${name} good for gaming?`, answer: `This is a classic/older device. While it was capable of casual gaming at launch, it will heavily struggle with modern, intensive 3D games.` },
    { question: `Does the Samsung ${name} support 4G LTE?`, answer: `Please check the network specifications below. Most classic J-series and newer models support at least 4G LTE.` }
  ]
});

const phonesData = [
  {
    name: "Galaxy J7 Pro",
    slug: "samsung-galaxy-j7-pro",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Black", "Gold", "Light Blue", "Rose Gold"],
    release_date: "2017-07-01",
    price_usd: 280,
    price_bdt: 25000,
    price_display_text: "BDT 25,000",
    processor: "Exynos 7870",
    gpu: "Mali-T830 MP1",
    display_type: "Super AMOLED",
    screen_size: "5.5 inches",
    refresh_rate: "60Hz",
    brightness: "400 nits",
    cam_count: "Single",
    cam_main_sensor: "13 MP, f/1.7, AF",
    video_recording: "1080p@30fps",
    battery_capacity: "3600 mAh",
    charging_wired: "Standard",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "181 g",
    dimensions: "152.5 x 74.8 x 8 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Budget",
    performance_tier: "Basic",
    camera_tier: "Basic",
    battery_tier: "Standard",
    internal_links: { same_brand: ["samsung-galaxy-j7-prime", "samsung-galaxy-j5-pro"] },
    ...commonSeoFields("Galaxy J7 Pro", 280),
    overview: "The Galaxy J7 Pro was a massive hit in the mid-range market, beloved for bringing premium aesthetics to a highly affordable price bracket. It featured a stunning full-metal unibody design with unique U-shaped antenna bands that made it instantly recognizable. Crucially, it included a high-quality 5.5-inch Super AMOLED display and the highly requested 'Always On Display' feature, which was previously reserved for S-series flagships. While the Exynos 7870 processor wasn't a powerhouse, the phone’s premium feel, great battery life, and excellent front and rear 13MP cameras made it a favorite.",
    highlights: ["Premium metal unibody", "Super AMOLED Display", "Always On Display feature"],
    pros: ["Fantastic build quality", "Vibrant screen colors", "Good battery endurance"],
    cons: ["Processor struggled with heavy games", "Relatively heavy"],
    verdict: "A legendary mid-ranger that proved Samsung could make beautifully crafted metal phones for budget-conscious consumers."
  },
  {
    name: "Galaxy J7 Prime",
    slug: "samsung-galaxy-j7-prime",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Black", "Gold", "Rose Gold"],
    release_date: "2016-09-01",
    price_usd: 240,
    price_bdt: 20000,
    price_display_text: "BDT 20,000",
    processor: "Exynos 7870",
    gpu: "Mali-T830 MP1",
    display_type: "PLS LCD",
    screen_size: "5.5 inches",
    refresh_rate: "60Hz",
    brightness: "400 nits",
    cam_count: "Single",
    cam_main_sensor: "13 MP, f/1.9, AF",
    video_recording: "1080p@30fps",
    battery_capacity: "3300 mAh",
    charging_wired: "Standard",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "167 g",
    dimensions: "151.7 x 75 x 8 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Budget",
    performance_tier: "Basic",
    camera_tier: "Basic",
    battery_tier: "Basic",
    internal_links: { same_brand: ["samsung-galaxy-j7-pro", "samsung-galaxy-j5-prime"] },
    ...commonSeoFields("Galaxy J7 Prime", 240),
    overview: "The Galaxy J7 Prime holds an iconic status in the South Asian smartphone market. It was Samsung's direct response to the aggressive rise of Chinese budget brands, and it succeeded wildly. It replaced the plastic body of older J-series models with a sleek, premium aluminum back. It was also one of the first budget Samsung phones to feature a reliable front-mounted fingerprint scanner. While it used a PLS LCD screen instead of an AMOLED, the 1080p resolution kept things sharp, and the Exynos 7870 provided incredibly power-efficient daily performance.",
    highlights: ["Premium aluminum body", "Front fingerprint scanner", "Very power-efficient processor"],
    pros: ["Extremely durable metal build", "Reliable battery life", "Sharp 1080p display"],
    cons: ["Lack of an AMOLED screen", "Average camera performance in low light"],
    verdict: "A truly iconic device that offered durability and reliability, cementing Samsung's grip on the budget market."
  },
  {
    name: "Galaxy J6",
    slug: "samsung-galaxy-j6",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Black", "Gold", "Blue"],
    release_date: "2018-05-01",
    price_usd: 180,
    price_bdt: 16000,
    price_display_text: "BDT 16,000",
    processor: "Exynos 7870",
    gpu: "Mali-T830 MP1",
    display_type: "Super AMOLED",
    screen_size: "5.6 inches",
    refresh_rate: "60Hz",
    brightness: "400 nits",
    cam_count: "Single",
    cam_main_sensor: "13 MP, f/1.9, AF",
    video_recording: "1080p@30fps",
    battery_capacity: "3000 mAh",
    charging_wired: "Standard",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "154 g",
    dimensions: "149.3 x 70.2 x 8.2 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Entry-Level",
    performance_tier: "Basic",
    camera_tier: "Basic",
    battery_tier: "Basic",
    internal_links: { same_brand: ["samsung-galaxy-j8"] },
    ...commonSeoFields("Galaxy J6", 180),
    overview: "The Galaxy J6 represented a significant design shift for Samsung's budget lineup. It was the first J-series phone to adopt the modern 18.5:9 'Infinity Display' aspect ratio, stretching the beautiful Super AMOLED screen taller while shrinking the top and bottom bezels. This made the phone incredibly comfortable to hold and use with one hand. Because the front was mostly screen, the fingerprint scanner was moved to the back, just below the 13MP camera. While it still utilized the aging Exynos 7870 processor, its modern looks and vibrant screen made it very popular.",
    highlights: ["Infinity Display design", "Super AMOLED screen", "Rear fingerprint scanner"],
    pros: ["Very comfortable, modern form factor", "Excellent display colors", "Lightweight build"],
    cons: ["Aging processor", "Small 3000mAh battery"],
    verdict: "The phone that modernized the J-series design language, prioritizing screen aesthetics and ergonomics over raw performance."
  },
  {
    name: "Galaxy J2 Prime",
    slug: "samsung-galaxy-j2-prime",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Black", "Gold", "Silver", "Pink"],
    release_date: "2016-11-01",
    price_usd: 100,
    price_bdt: 10000,
    price_display_text: "BDT 10,000",
    processor: "Mediatek MT6737T",
    gpu: "Mali-T720MP2",
    display_type: "PLS LCD",
    screen_size: "5.0 inches",
    refresh_rate: "60Hz",
    brightness: "350 nits",
    cam_count: "Single",
    cam_main_sensor: "8 MP, f/2.2, AF",
    video_recording: "720p@30fps",
    battery_capacity: "2600 mAh (Removable)",
    charging_wired: "Standard",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "160 g",
    dimensions: "144.8 x 72.1 x 8.9 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Entry-Level",
    performance_tier: "Basic",
    camera_tier: "Basic",
    battery_tier: "Basic",
    internal_links: { same_brand: ["samsung-galaxy-grand-prime"] },
    ...commonSeoFields("Galaxy J2 Prime", 100),
    overview: "The Galaxy J2 Prime was a ubiquitous entry-level smartphone designed to get millions of people onto the 4G network for the first time. It featured a highly textured, grippy plastic back cover and a removable 2600mAh battery—a feature that was already becoming rare. It had a very basic 5.0-inch PLS LCD screen and a modest 8MP camera. Most notably, it included an LED flash on the front selfie camera, which was a huge selling point for budget-conscious teenagers. Performance was strictly for basic communication and extremely light web browsing.",
    highlights: ["Front-facing LED flash", "Removable 2600mAh battery", "Textured, grippy plastic back"],
    pros: ["Very cheap and accessible", "Removable battery was convenient", "Front flash was a fun addition"],
    cons: ["Very poor performance", "Low resolution display", "Only 8GB of base storage"],
    verdict: "A strictly utilitarian device meant to provide basic 4G connectivity and a Samsung logo at rock-bottom prices."
  },
  {
    name: "Galaxy Grand Prime",
    slug: "samsung-galaxy-grand-prime",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["White", "Gray", "Gold"],
    release_date: "2014-10-01",
    price_usd: 150,
    price_bdt: 14000,
    price_display_text: "BDT 14,000",
    processor: "Snapdragon 410",
    gpu: "Adreno 306",
    display_type: "TFT",
    screen_size: "5.0 inches",
    refresh_rate: "60Hz",
    brightness: "350 nits",
    cam_count: "Single",
    cam_main_sensor: "8 MP, f/2.2, AF",
    video_recording: "1080p@30fps",
    battery_capacity: "2600 mAh (Removable)",
    charging_wired: "Standard",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "156 g",
    dimensions: "144.8 x 72.1 x 8.6 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Entry-Level",
    performance_tier: "Basic",
    camera_tier: "Basic",
    battery_tier: "Basic",
    internal_links: { same_brand: ["samsung-galaxy-j2-prime"] },
    ...commonSeoFields("Galaxy Grand Prime", 150),
    overview: "The Galaxy Grand Prime is a nostalgic classic that dominated the entry-level market in the mid-2010s. Marketed heavily towards the selfie-obsessed crowd, it featured an impressive (for its time) 5MP wide-angle front camera, allowing users to fit more friends into a single shot. The 5.0-inch TFT display was surrounded by thick bezels and the iconic physical home button. It was powered by the Snapdragon 410, which handled Android KitKat reasonably well. Its durable plastic build and removable battery made it incredibly popular as a reliable, affordable daily driver.",
    highlights: ["5MP wide-angle selfie camera", "Removable 2600mAh battery", "Iconic physical home button"],
    pros: ["Great selfie camera for its era", "Durable and reliable", "Removable battery"],
    cons: ["TFT display had poor viewing angles", "Very prone to lagging over time"],
    verdict: "A nostalgic classic that successfully capitalized on the selfie trend of the mid-2010s while remaining highly affordable."
  },
  {
    name: "Galaxy S21 FE 5G (Snapdragon)",
    slug: "samsung-galaxy-s21-fe-5g-snapdragon",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["White", "Graphite", "Lavender", "Olive"],
    release_date: "2022-01-07",
    price_usd: 699,
    price_bdt: 75000,
    price_display_text: "BDT 75,000",
    processor: "Snapdragon 888 5G",
    gpu: "Adreno 660",
    display_type: "Dynamic AMOLED 2X, 120Hz",
    screen_size: "6.4 inches",
    refresh_rate: "120Hz",
    brightness: "1200 nits (peak)",
    cam_count: "Triple",
    cam_main_sensor: "12 MP, f/1.8, OIS",
    video_recording: "4K@30/60fps, 1080p@30/60/240fps",
    battery_capacity: "4500 mAh",
    charging_wired: "25W wired",
    wireless_charging: "15W wireless, reverse wireless",
    ip_rating: "IP68 dust/water resistant",
    weight: "177 g",
    dimensions: "155.7 x 74.5 x 7.9 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Flagship",
    performance_tier: "High-End",
    camera_tier: "Excellent",
    battery_tier: "Standard",
    internal_links: { same_brand: ["samsung-galaxy-s21-5g", "samsung-galaxy-s20-fe-5g"] },
    ...commonSeoFields("Galaxy S21 FE 5G (Snapdragon)", 699),
    overview: "The Galaxy S21 FE (Fan Edition) arrived slightly late to the market but still packed a massive punch. It essentially took everything great about the standard S21 and made it slightly larger and more affordable. The highly sought-after Snapdragon 888 variant offered blistering performance and excellent thermal management compared to the Exynos version. It featured a stunning, flat 6.4-inch 120Hz Dynamic AMOLED display and retained all flagship perks like IP68 water resistance and wireless charging. Its matte plastic ('glasstic') back was actually preferred by many for its durability and resistance to fingerprints.",
    highlights: ["Snapdragon 888 processor", "6.4-inch 120Hz AMOLED", "IP68 and Wireless Charging"],
    pros: ["Flawless flagship performance", "Excellent, reliable camera system", "Lightweight and durable"],
    cons: ["Battery life could have been better", "Arrived too close to the S22 launch"],
    verdict: "A superb 'value flagship' that hit the sweet spot between screen size, performance, and price, especially with the Snapdragon chip."
  },
  {
    name: "Galaxy S20 FE 5G",
    slug: "samsung-galaxy-s20-fe-5g",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Cloud Navy", "Cloud White", "Cloud Pink", "Cloud Red", "Cloud Blue", "Cloud Mint"],
    release_date: "2020-10-02",
    price_usd: 699,
    price_bdt: 70000,
    price_display_text: "BDT 70,000",
    processor: "Snapdragon 865 5G",
    gpu: "Adreno 650",
    display_type: "Super AMOLED, 120Hz",
    screen_size: "6.5 inches",
    refresh_rate: "120Hz",
    brightness: "800 nits",
    cam_count: "Triple",
    cam_main_sensor: "12 MP, f/1.8, OIS",
    video_recording: "4K@30/60fps, 1080p@30/60fps",
    battery_capacity: "4500 mAh",
    charging_wired: "25W wired",
    wireless_charging: "15W wireless, reverse wireless",
    ip_rating: "IP68 dust/water resistant",
    weight: "190 g",
    dimensions: "159.8 x 74.5 x 8.4 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Flagship",
    performance_tier: "High-End",
    camera_tier: "Excellent",
    battery_tier: "Standard",
    internal_links: { same_brand: ["samsung-galaxy-s20", "samsung-galaxy-s21-fe-5g"] },
    ...commonSeoFields("Galaxy S20 FE 5G", 699),
    overview: "The Galaxy S20 FE 5G is widely considered one of the best value propositions Samsung ever created. In a year where standard S20 models were incredibly expensive, the S20 FE stripped away the expensive curved glass and high-res screen but kept the absolute essentials: the incredibly powerful Snapdragon 865 processor, a super-smooth 120Hz flat AMOLED display, and a highly versatile triple camera setup including a 3x optical zoom telephoto lens. It was a massive commercial success, proving that consumers loved flat screens, plastic backs (for durability), and flagship chips at lower prices.",
    highlights: ["Snapdragon 865 Processor", "120Hz flat AMOLED screen", "3x optical zoom lens"],
    pros: ["Unbeatable value for money at launch", "Excellent, stable performance", "Great camera versatility"],
    cons: ["Ghost touch issues reported on early units", "Plastic back feels less premium"],
    verdict: "A legendary 'Fan Edition' that successfully delivered a true flagship experience for hundreds of dollars less than the main S-series."
  },
  {
    name: "Galaxy S20+ 5G",
    slug: "samsung-galaxy-s20-plus-5g",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Cosmic Black", "Cosmic Grey", "Cloud Blue", "Aura Red"],
    release_date: "2020-03-06",
    price_usd: 1199,
    price_bdt: 125000,
    price_display_text: "BDT 125,000",
    processor: "Exynos 990 / Snapdragon 865 5G",
    gpu: "Mali-G77 MP11 / Adreno 650",
    display_type: "Dynamic AMOLED 2X, 120Hz",
    screen_size: "6.7 inches",
    refresh_rate: "120Hz",
    brightness: "1200 nits (peak)",
    cam_count: "Quad",
    cam_main_sensor: "12 MP, f/1.8, OIS",
    video_recording: "8K@24fps, 4K@30/60fps",
    battery_capacity: "4500 mAh",
    charging_wired: "25W wired",
    wireless_charging: "15W wireless, 4.5W reverse wireless",
    ip_rating: "IP68 dust/water resistant",
    weight: "186 g",
    dimensions: "161.9 x 73.7 x 7.8 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Ultra Premium",
    performance_tier: "Mainstream",
    camera_tier: "Excellent",
    battery_tier: "Standard",
    internal_links: { same_brand: ["samsung-galaxy-s20", "samsung-galaxy-s20-ultra-5g"] },
    ...commonSeoFields("Galaxy S20+ 5G", 1199),
    overview: "The Galaxy S20+ 5G hit the perfect middle ground between the compact S20 and the massive, unwieldy S20 Ultra. It featured a gorgeous 6.7-inch Dynamic AMOLED 2X display that was the first in the S-series to support a buttery smooth 120Hz refresh rate (though limited to 1080p resolution). The camera system was highly reliable, avoiding the autofocus issues that plagued the Ultra model, and offering an excellent 3x hybrid zoom. Wrapped in a very sleek, premium glass-and-metal build, it was the most sensible choice for premium buyers in 2020.",
    highlights: ["First 120Hz S-series display", "Excellent, reliable camera system", "Sleek and lightweight for its size"],
    pros: ["Stunningly fluid 120Hz screen", "Great ergonomics despite the large size", "Fantastic overall camera"],
    cons: ["Exynos variant suffered from thermal throttling", "Could not use 120Hz at 1440p resolution"],
    verdict: "The most balanced and reliable phone in the S20 lineup, offering a gorgeous high-refresh screen without the bulk of the Ultra."
  },
  {
    name: "Galaxy S10 5G",
    slug: "samsung-galaxy-s10-5g",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Crown Silver", "Majestic Black", "Royal Gold"],
    release_date: "2019-04-05",
    price_usd: 1299,
    price_bdt: 130000,
    price_display_text: "BDT 130,000",
    processor: "Exynos 9820 / Snapdragon 855",
    gpu: "Mali-G76 MP12 / Adreno 640",
    display_type: "Dynamic AMOLED",
    screen_size: "6.7 inches",
    refresh_rate: "60Hz",
    brightness: "1200 nits (peak)",
    cam_count: "Quad",
    cam_main_sensor: "12 MP, f/1.5-2.4 (variable), OIS",
    video_recording: "4K@30/60fps, 1080p@30/60/240fps",
    battery_capacity: "4500 mAh",
    charging_wired: "25W wired",
    wireless_charging: "15W wireless, 4.5W reverse wireless",
    ip_rating: "IP68 dust/water resistant",
    weight: "198 g",
    dimensions: "162.6 x 77.1 x 7.9 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Ultra Premium",
    performance_tier: "Basic",
    camera_tier: "Excellent",
    battery_tier: "Standard",
    internal_links: { same_brand: ["samsung-galaxy-s10-plus", "samsung-galaxy-s20-plus-5g"] },
    ...commonSeoFields("Galaxy S10 5G", 1299),
    overview: "The Galaxy S10 5G was a monumental device, acting as a bridge between the S10 generation and the future. It was larger and more powerful than the S10+, featuring a massive 6.7-inch display and an enormous 4500mAh battery. More importantly, it was Samsung's first true 5G smartphone. It also added a Time-of-Flight (ToF) 3D depth sensor to both the front and rear camera setups, allowing for advanced augmented reality applications and superior 'Live Focus' video blurring. It was the absolute pinnacle of Samsung's engineering capabilities in 2019.",
    highlights: ["First Samsung 5G phone", "Massive 6.7-inch Dynamic AMOLED", "3D ToF sensors front and back"],
    pros: ["Incredibly feature-rich", "Stunningly beautiful screen", "Great battery life"],
    cons: ["Pill-shaped front camera cutout was huge", "Extremely expensive"],
    verdict: "A pioneer for the 5G era that offered every conceivable feature in a beautifully massive, ultra-premium package."
  },
  {
    name: "Galaxy Core Prime",
    slug: "samsung-galaxy-core-prime",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Black", "White", "Silver"],
    release_date: "2014-11-01",
    price_usd: 130,
    price_bdt: 12000,
    price_display_text: "BDT 12,000",
    processor: "Snapdragon 410",
    gpu: "Adreno 306",
    display_type: "PLS LCD",
    screen_size: "4.5 inches",
    refresh_rate: "60Hz",
    brightness: "350 nits",
    cam_count: "Single",
    cam_main_sensor: "5 MP, f/2.6, AF",
    video_recording: "720p@30fps",
    battery_capacity: "2000 mAh (Removable)",
    charging_wired: "Standard",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "130 g",
    dimensions: "130.8 x 67.9 x 8.8 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Entry-Level",
    performance_tier: "Basic",
    camera_tier: "Basic",
    battery_tier: "Basic",
    internal_links: { same_brand: ["samsung-galaxy-grand-prime"] },
    ...commonSeoFields("Galaxy Core Prime", 130),
    overview: "The Galaxy Core Prime is a deep cut into Samsung's history, representing the quintessential entry-level smartphone of the early 4G era. With a tiny 4.5-inch screen and a very basic 5MP camera, it was designed for users transitioning from feature phones to smartphones for the very first time. It was incredibly lightweight at just 130 grams and featured a removable 2000mAh battery. While its specifications are archaic by modern standards, it was a highly reliable, incredibly popular, and almost indestructible starter phone for millions of people.",
    highlights: ["Compact 4.5-inch design", "Removable 2000mAh battery", "Very lightweight at 130g"],
    pros: ["Extremely affordable", "Durable and reliable for basic tasks", "Fits in any pocket"],
    cons: ["Very poor screen resolution", "Cameras were barely usable", "Tiny amount of storage"],
    verdict: "A nostalgic piece of history; a tough, reliable starter smartphone that introduced millions to the Android ecosystem."
  }
];

async function run() {
  try {
    await mongoose.connect(MONGODB_URI as string);
    console.log("✅ Connected to MongoDB");

    const Brand = mongoose.models.Brand || mongoose.model("Brand", new mongoose.Schema({}, { strict: false }));
    const samsungBrand = await Brand.findOne({ name: /Samsung/i });

    const PhoneSchema = new mongoose.Schema({}, { strict: false });
    const Phone = mongoose.models.Phone || mongoose.model("Phone", PhoneSchema);

    for (const phone of phonesData) {
      if (samsungBrand) (phone as any).brand_id = samsungBrand._id;
      phone.updated_at = new Date() as any;
      await Phone.findOneAndUpdate({ slug: phone.slug }, { $set: phone }, { upsert: true, new: true });
      console.log(`✅ Inserted/Updated: ${phone.name}`);
    }

    console.log("🎉 Samsung Batch 11 (J Series & Classics) completed! Added 10 phones with strict specs.");

  } catch (err) {
    console.error("❌ Error:", (err as Error).message);
  } finally {
    await mongoose.disconnect();
  }
}

run();
