require("dotenv").config({ path: "./.env.local" });
const mongoose = require("mongoose");

const MONGODB_URI = process.env.MONGODB_URI;
if (!MONGODB_URI) { console.error("No MONGODB_URI"); process.exit(1); }

const PhoneSchema = new mongoose.Schema({}, { strict: false });
const BrandSchema = new mongoose.Schema({}, { strict: false });

async function run() {
  await mongoose.connect(MONGODB_URI);
  console.log("Connected");

  const Phone = mongoose.models.Phone || mongoose.model("Phone", PhoneSchema);
  const Brand = mongoose.models.Brand || mongoose.model("Brand", BrandSchema);

  const apple = await Brand.findOne({ name: /apple/i }).lean();
  if (!apple) { console.error("Apple brand not found"); process.exit(1); }
  const bid = apple._id;

  const phones = [
    {
      name: "iPhone X",
      slug: "iphone-x",
      brand_id: bid,
      is_published: true,
      is_official: true,
      release_date: "2017-11-03",
      model_number: "A1865, A1901, A1902",
      colors: ["Silver", "Space Gray"],
      made_in: "China",
      phone_variants: "64GB, 256GB",
      price_bdt: 89999,
      price_official: 89999,
      price_unofficial: 65000,
      chipset_highlight: "Apple A11 Bionic (10nm)",
      camera_highlight: "Dual 12MP (Wide + Telephoto)",
      display_highlight: "5.8\" Super Retina OLED 458ppi",
      battery_highlight: "2,716 mAh",
      benchmark_highlight: "AnTuTu ~220,000",
      processor: "Apple A11 Bionic",
      cpu: "Apple A11 Bionic (10nm) — 2+4 core",
      gpu: "Apple A11 GPU (3-core)",
      fabrication: "10 nm TSMC",
      ram_variants: "3 GB LPDDR4X",
      storage_variants: "64 GB, 256 GB",
      storage_type: "NVMe",
      antutu_score: 220000,
      weight: "174 g",
      dimensions: "143.6 × 70.9 × 7.7 mm",
      build_material: "Surgical-grade stainless steel frame, glass front and back",
      sim_type: "Nano-SIM (no eSIM)",
      water_resistance: "IP67 — 1 meter for 30 minutes",
      display_type: "Super Retina HD OLED, True Tone",
      screen_size: "5.8 inches",
      resolution: "2436 × 1125 pixels",
      refresh_rate: "60 Hz",
      brightness: "625 nits typical",
      hdr: "HDR10, Dolby Vision",
      protection: "Ion-strengthened glass",
      pixel_density: "458 ppi",
      cam_count: "Dual",
      cam_main_sensor: "12 MP, f/1.8, 28mm, OIS",
      cam_telephoto: "12 MP, f/2.4, 52mm, 2x optical zoom, OIS",
      cam_ois: "Yes (both lenses)",
      cam_flash: "True Tone Flash, Slow Sync",
      cam_video: "4K@60fps, 1080p@240fps",
      cam_front_resolution: "7 MP TrueDepth, f/2.2",
      cam_front_portrait: "Portrait mode, Portrait Lighting",
      cam_front_video: "1080p@30fps",
      battery_capacity: "2,716 mAh",
      charging_wired: "18W Fast Charging (Lightning)",
      charging_wireless: "7.5W Qi Wireless",
      charging_reverse: "No",
      charger_included: false,
      usb_type: "Lightning",
      has_5g: false,
      wifi_version: "Wi-Fi 802.11a/b/g/n/ac",
      bluetooth_version: "Bluetooth 5.0",
      has_nfc: true,
      gps_specs: "GPS, GLONASS, Galileo, BeiDou",
      has_ir_blaster: false,
      has_audio_jack: false,
      usb_version: "USB 2.0",
      sensor_fingerprint: "Face ID (3D Facial Recognition)",
      has_gyroscope: true,
      has_compass: true,
      has_accelerometer: true,
      has_face_unlock: true,
      android_version: "iOS 11",
      ui_version: "iOS 11 (up to iOS 16)",
      update_policy: "Supported up to iOS 16",
      ai_features: ["Animoji", "Face ID"],
      has_ai_assistant: true,
      meta_title: "Apple iPhone X Full Specifications & Price | TechTweak",
      meta_description: "Full specs of Apple iPhone X — A11 Bionic, 5.8\" OLED, Dual 12MP camera, Face ID, 2716mAh. Price in Bangladesh.",
      pros: ["First iPhone with Face ID and all-screen OLED", "Dual OIS cameras with Portrait mode", "Premium stainless steel build"],
      cons: ["No charger in box", "No headphone jack", "IP67 only"],
      faqs: [
        { question: "Does iPhone X support 5G?", answer: "No, it supports 4G LTE only." },
        { question: "What chip does iPhone X use?", answer: "Apple A11 Bionic (10nm)." }
      ],
      updated_at: new Date()
    },
    {
      name: "iPhone XR",
      slug: "iphone-xr",
      brand_id: bid,
      is_published: true,
      is_official: true,
      release_date: "2018-10-26",
      model_number: "A1984, A2105, A2106, A2107",
      colors: ["Black", "White", "Blue", "Yellow", "Coral", "Product Red"],
      made_in: "China",
      phone_variants: "64GB, 128GB, 256GB",
      price_bdt: 69999,
      price_official: 69999,
      price_unofficial: 45000,
      chipset_highlight: "Apple A12 Bionic (7nm)",
      camera_highlight: "Single 12MP f/1.8 with Portrait mode",
      display_highlight: "6.1\" Liquid Retina LCD 326ppi",
      battery_highlight: "2,942 mAh all-day life",
      processor: "Apple A12 Bionic",
      cpu: "Apple A12 Bionic (7nm TSMC) — 2+4 core",
      gpu: "Apple A12 GPU (4-core)",
      fabrication: "7 nm TSMC",
      ram_variants: "3 GB",
      storage_variants: "64 GB, 128 GB, 256 GB",
      storage_type: "NVMe",
      antutu_score: 350000,
      weight: "194 g",
      dimensions: "150.9 × 75.7 × 8.3 mm",
      build_material: "Aluminum 7000 series frame, glass front and back",
      sim_type: "Nano-SIM + eSIM",
      water_resistance: "IP67 — 1 meter for 30 minutes",
      display_type: "Liquid Retina HD LCD, True Tone",
      screen_size: "6.1 inches",
      resolution: "1792 × 828 pixels",
      refresh_rate: "60 Hz",
      brightness: "625 nits typical",
      hdr: "No HDR",
      protection: "Ion-strengthened glass",
      pixel_density: "326 ppi",
      cam_count: "Single",
      cam_main_sensor: "12 MP, f/1.8, 28mm, OIS",
      cam_ois: "Yes",
      cam_flash: "True Tone Flash",
      cam_video: "4K@60fps, 1080p@240fps",
      cam_front_resolution: "7 MP TrueDepth, f/2.2",
      cam_front_portrait: "Portrait mode",
      cam_front_video: "1080p@30fps",
      battery_capacity: "2,942 mAh",
      charging_wired: "18W Fast Charging (Lightning)",
      charging_wireless: "7.5W Qi Wireless",
      charging_reverse: "No",
      charger_included: false,
      usb_type: "Lightning",
      has_5g: false,
      wifi_version: "Wi-Fi 802.11a/b/g/n/ac",
      bluetooth_version: "Bluetooth 5.0",
      has_nfc: true,
      has_ir_blaster: false,
      has_audio_jack: false,
      usb_version: "USB 2.0",
      sensor_fingerprint: "Face ID",
      has_gyroscope: true,
      has_compass: true,
      has_accelerometer: true,
      has_face_unlock: true,
      android_version: "iOS 12",
      ui_version: "iOS 12 (up to iOS 17)",
      update_policy: "Supported up to iOS 17",
      meta_title: "Apple iPhone XR Full Specifications & Price | TechTweak",
      meta_description: "Complete specs of Apple iPhone XR — A12 Bionic, 6.1\" LCD, 12MP camera, Face ID. Price in Bangladesh.",
      pros: ["Excellent battery life for its class", "Vibrant LCD display", "Multiple color options"],
      cons: ["LCD not OLED", "Single rear camera", "IP67 only"],
      faqs: [{ question: "Does iPhone XR have OLED?", answer: "No, it uses an LCD Liquid Retina display." }],
      updated_at: new Date()
    },
    {
      name: "iPhone XS",
      slug: "iphone-xs",
      brand_id: bid,
      is_published: true,
      is_official: true,
      release_date: "2018-09-21",
      model_number: "A1920, A2097, A2098, A2100",
      colors: ["Gold", "Silver", "Space Gray"],
      made_in: "China",
      phone_variants: "64GB, 256GB, 512GB",
      price_bdt: 89999,
      price_official: 89999,
      price_unofficial: 55000,
      chipset_highlight: "Apple A12 Bionic (7nm)",
      camera_highlight: "Dual 12MP (Wide + Telephoto)",
      display_highlight: "5.8\" Super Retina OLED 458ppi",
      battery_highlight: "2,658 mAh",
      processor: "Apple A12 Bionic",
      cpu: "Apple A12 Bionic (7nm TSMC)",
      gpu: "Apple A12 GPU (4-core)",
      fabrication: "7 nm TSMC",
      ram_variants: "4 GB",
      storage_variants: "64 GB, 256 GB, 512 GB",
      storage_type: "NVMe",
      antutu_score: 350000,
      weight: "177 g",
      dimensions: "143.6 × 70.9 × 7.7 mm",
      build_material: "Surgical-grade stainless steel, glass front and back",
      sim_type: "Nano-SIM + eSIM",
      water_resistance: "IP68 — 2 meters for 30 minutes",
      display_type: "Super Retina HD OLED, True Tone",
      screen_size: "5.8 inches",
      resolution: "2436 × 1125 pixels",
      refresh_rate: "60 Hz",
      brightness: "625 nits typical",
      hdr: "HDR10, Dolby Vision",
      protection: "Ion-strengthened glass",
      pixel_density: "458 ppi",
      cam_count: "Dual",
      cam_main_sensor: "12 MP, f/1.8, 26mm, OIS",
      cam_telephoto: "12 MP, f/2.4, 52mm, 2x optical zoom",
      cam_ois: "Yes",
      cam_flash: "True Tone Flash",
      cam_video: "4K@60fps, 1080p@240fps",
      cam_front_resolution: "7 MP TrueDepth, f/2.2",
      cam_front_portrait: "Portrait mode, Portrait Lighting",
      cam_front_video: "1080p@30fps",
      battery_capacity: "2,658 mAh",
      charging_wired: "18W Fast Charging (Lightning)",
      charging_wireless: "7.5W Qi Wireless",
      charging_reverse: "No",
      charger_included: false,
      usb_type: "Lightning",
      has_5g: false,
      wifi_version: "Wi-Fi 802.11a/b/g/n/ac",
      bluetooth_version: "Bluetooth 5.0",
      has_nfc: true,
      has_ir_blaster: false,
      has_audio_jack: false,
      usb_version: "USB 2.0",
      sensor_fingerprint: "Face ID",
      has_gyroscope: true,
      has_compass: true,
      has_accelerometer: true,
      has_face_unlock: true,
      android_version: "iOS 12",
      ui_version: "iOS 12 (up to iOS 17)",
      meta_title: "Apple iPhone XS Full Specifications & Price | TechTweak",
      meta_description: "Full specs of Apple iPhone XS — A12 Bionic, 5.8\" OLED, Dual 12MP, IP68, Face ID. Price in Bangladesh.",
      pros: ["IP68 water resistance", "Dual OIS cameras", "Premium stainless build"],
      cons: ["Small battery", "No charger included", "No headphone jack"],
      faqs: [{ question: "Does iPhone XS have IP68?", answer: "Yes, rated IP68 up to 2 meters for 30 minutes." }],
      updated_at: new Date()
    },
    {
      name: "iPhone XS Max",
      slug: "iphone-xs-max",
      brand_id: bid,
      is_published: true,
      is_official: true,
      release_date: "2018-09-21",
      model_number: "A1921, A2101, A2102, A2104",
      colors: ["Gold", "Silver", "Space Gray"],
      made_in: "China",
      phone_variants: "64GB, 256GB, 512GB",
      price_bdt: 109999,
      price_official: 109999,
      price_unofficial: 68000,
      chipset_highlight: "Apple A12 Bionic (7nm)",
      camera_highlight: "Dual 12MP (Wide + Telephoto)",
      display_highlight: "6.5\" Super Retina OLED 458ppi",
      battery_highlight: "3,174 mAh",
      processor: "Apple A12 Bionic",
      cpu: "Apple A12 Bionic (7nm TSMC)",
      gpu: "Apple A12 GPU (4-core)",
      fabrication: "7 nm TSMC",
      ram_variants: "4 GB",
      storage_variants: "64 GB, 256 GB, 512 GB",
      storage_type: "NVMe",
      antutu_score: 350000,
      weight: "208 g",
      dimensions: "157.5 × 77.4 × 7.7 mm",
      build_material: "Surgical-grade stainless steel, glass front and back",
      sim_type: "Nano-SIM + eSIM",
      water_resistance: "IP68 — 2 meters for 30 minutes",
      display_type: "Super Retina HD OLED, True Tone",
      screen_size: "6.5 inches",
      resolution: "2688 × 1242 pixels",
      refresh_rate: "60 Hz",
      brightness: "625 nits typical",
      hdr: "HDR10, Dolby Vision",
      protection: "Ion-strengthened glass",
      pixel_density: "458 ppi",
      cam_count: "Dual",
      cam_main_sensor: "12 MP, f/1.8, 26mm, OIS",
      cam_telephoto: "12 MP, f/2.4, 52mm, 2x optical zoom",
      cam_ois: "Yes",
      cam_flash: "True Tone Flash",
      cam_video: "4K@60fps, 1080p@240fps",
      cam_front_resolution: "7 MP TrueDepth, f/2.2",
      cam_front_portrait: "Portrait mode, Portrait Lighting",
      cam_front_video: "1080p@30fps",
      battery_capacity: "3,174 mAh",
      charging_wired: "18W Fast Charging (Lightning)",
      charging_wireless: "7.5W Qi Wireless",
      charging_reverse: "No",
      charger_included: false,
      usb_type: "Lightning",
      has_5g: false,
      wifi_version: "Wi-Fi 802.11a/b/g/n/ac",
      bluetooth_version: "Bluetooth 5.0",
      has_nfc: true,
      has_ir_blaster: false,
      has_audio_jack: false,
      usb_version: "USB 2.0",
      sensor_fingerprint: "Face ID",
      has_gyroscope: true,
      has_compass: true,
      has_accelerometer: true,
      has_face_unlock: true,
      android_version: "iOS 12",
      ui_version: "iOS 12 (up to iOS 17)",
      meta_title: "Apple iPhone XS Max Full Specifications & Price | TechTweak",
      meta_description: "Full specs Apple iPhone XS Max — A12, 6.5\" OLED, Dual 12MP, IP68. Bangladesh price.",
      pros: ["Large 6.5\" OLED screen", "Better battery than XS", "IP68 water resistance"],
      cons: ["Heavy at 208g", "No charger included", "No 5G"],
      faqs: [{ question: "How large is iPhone XS Max screen?", answer: "6.5-inch Super Retina HD OLED at 458 ppi." }],
      updated_at: new Date()
    }
  ];

  for (const p of phones) {
    const exists = await Phone.findOne({ slug: p.slug });
    if (exists) {
      await Phone.updateOne({ slug: p.slug }, { $set: p });
      console.log(`Updated: ${p.name}`);
    } else {
      await Phone.create(p);
      console.log(`Created: ${p.name}`);
    }
  }

  await mongoose.disconnect();
  console.log("Done. Part 1 complete.");
}

run().catch(e => { console.error(e); process.exit(1); });
