require("dotenv").config({ path: "./.env.local" });
const mongoose = require("mongoose");

const MONGODB_URI = process.env.MONGODB_URI;
if (!MONGODB_URI) { console.error("No MONGODB_URI"); process.exit(1); }

const PhoneSchema = new mongoose.Schema({}, { strict: false });
const BrandSchema = new mongoose.Schema({}, { strict: false });

async function run() {
  await mongoose.connect(MONGODB_URI);
  console.log("Connected to MongoDB");

  const Phone = mongoose.models.Phone || mongoose.model("Phone", PhoneSchema);
  const Brand = mongoose.models.Brand || mongoose.model("Brand", BrandSchema);

  const apple = await Brand.findOne({ name: /apple/i }).lean();
  if (!apple) { console.error("Apple brand not found"); process.exit(1); }
  const bid = apple._id;

  const phones = [
    {
      name: "iPhone 11",
      slug: "iphone-11",
      brand_id: bid,
      is_published: true,
      is_official: true,
      release_date: "2019-09-20",
      model_number: "A2111, A2221, A2223",
      colors: ["Black", "Green", "Yellow", "Purple", "White", "Product Red"],
      made_in: "China / India",
      phone_variants: "64GB, 128GB, 256GB",
      price_bdt: 55000,
      price_official: 55000,
      price_unofficial: 42000,
      chipset_highlight: "Apple A13 Bionic (7nm+)",
      camera_highlight: "Dual 12MP (Wide + Ultra Wide)",
      display_highlight: "6.1\" Liquid Retina HD LCD",
      battery_highlight: "3,110 mAh",
      benchmark_highlight: "AnTuTu ~450,000",
      processor: "Apple A13 Bionic",
      cpu: "Apple A13 Bionic (7nm+) — Hexa-core",
      gpu: "Apple GPU (4-core graphics)",
      fabrication: "7 nm+",
      ram_variants: "4 GB",
      storage_variants: "64 GB, 128 GB, 256 GB",
      storage_type: "NVMe",
      antutu_score: 450000,
      weight: "194 g",
      dimensions: "150.9 × 75.7 × 8.3 mm",
      build_material: "Glass front, glass back, aluminum frame (7000 series)",
      sim_type: "Nano-SIM and/or eSIM",
      water_resistance: "IP68 — up to 2m for 30 mins",
      display_type: "Liquid Retina IPS LCD",
      screen_size: "6.1 inches",
      resolution: "1792 × 828 pixels",
      refresh_rate: "60 Hz",
      brightness: "625 nits typical",
      hdr: "No",
      protection: "Scratch-resistant glass",
      pixel_density: "326 ppi",
      cam_count: "Dual",
      cam_main_sensor: "12 MP, f/1.8, 26mm, OIS",
      cam_ultrawide: "12 MP, f/2.4, 13mm",
      cam_ois: "Yes (Wide)",
      cam_flash: "Dual-LED dual-tone flash",
      cam_video: "4K@60fps, 1080p@240fps",
      cam_front_resolution: "12 MP, f/2.2, 23mm",
      cam_front_portrait: "Yes",
      cam_front_video: "4K@60fps",
      battery_capacity: "3,110 mAh",
      charging_wired: "18W Fast Charging (Lightning)",
      charging_wireless: "Qi Wireless",
      charging_reverse: "No",
      charger_included: false,
      usb_type: "Lightning",
      has_5g: false,
      wifi_version: "Wi-Fi 6 (802.11ax)",
      bluetooth_version: "Bluetooth 5.0",
      has_nfc: true,
      gps_specs: "GPS, GLONASS, GALILEO, QZSS",
      has_ir_blaster: false,
      has_audio_jack: false,
      usb_version: "USB 2.0",
      sensor_fingerprint: "Face ID",
      has_gyroscope: true,
      has_compass: true,
      has_accelerometer: true,
      has_face_unlock: true,
      android_version: "iOS 13",
      ui_version: "iOS 13 (upgradable)",
      update_policy: "Standard Apple support",
      meta_title: "Apple iPhone 11 Full Specifications & Price | TechTweak",
      meta_description: "Full specs of Apple iPhone 11 — A13 Bionic, 6.1\" LCD, Dual 12MP camera. Price in Bangladesh.",
      pros: ["Great performance with A13 Bionic", "Excellent battery life", "Ultra Wide camera is very useful"],
      cons: ["HD resolution only (not Full HD)", "LCD display instead of OLED", "No charger in box"],
      faqs: [
        { question: "Is iPhone 11 waterproof?", answer: "Yes, it is IP68 rated (up to 2m for 30 mins)." },
        { question: "Does iPhone 11 support 5G?", answer: "No, it supports 4G LTE only." }
      ],
      updated_at: new Date()
    },
    {
      name: "iPhone 11 Pro",
      slug: "iphone-11-pro",
      brand_id: bid,
      is_published: true,
      is_official: true,
      release_date: "2019-09-20",
      model_number: "A2160, A2215, A2217",
      colors: ["Space Gray", "Silver", "Gold", "Midnight Green"],
      made_in: "China",
      phone_variants: "64GB, 256GB, 512GB",
      price_bdt: 85000,
      price_official: 85000,
      price_unofficial: 60000,
      chipset_highlight: "Apple A13 Bionic (7nm+)",
      camera_highlight: "Triple 12MP (Wide + Telephoto + Ultra Wide)",
      display_highlight: "5.8\" Super Retina XDR OLED",
      battery_highlight: "3,046 mAh",
      benchmark_highlight: "AnTuTu ~460,000",
      processor: "Apple A13 Bionic",
      cpu: "Apple A13 Bionic (7nm+) — Hexa-core",
      gpu: "Apple GPU (4-core graphics)",
      fabrication: "7 nm+",
      ram_variants: "4 GB",
      storage_variants: "64 GB, 256 GB, 512 GB",
      storage_type: "NVMe",
      antutu_score: 460000,
      weight: "188 g",
      dimensions: "144 × 71.4 × 8.1 mm",
      build_material: "Glass front, glass back, stainless steel frame",
      sim_type: "Nano-SIM and/or eSIM",
      water_resistance: "IP68 — up to 4m for 30 mins",
      display_type: "Super Retina XDR OLED",
      screen_size: "5.8 inches",
      resolution: "2436 × 1125 pixels",
      refresh_rate: "60 Hz",
      brightness: "800 nits typical, 1200 nits peak (HDR)",
      hdr: "HDR10, Dolby Vision",
      protection: "Scratch-resistant glass",
      pixel_density: "458 ppi",
      cam_count: "Triple",
      cam_main_sensor: "12 MP, f/1.8, 26mm, OIS",
      cam_telephoto: "12 MP, f/2.0, 52mm, 2x optical zoom, OIS",
      cam_ultrawide: "12 MP, f/2.4, 13mm",
      cam_ois: "Yes (Wide + Telephoto)",
      cam_flash: "Dual-LED dual-tone flash",
      cam_video: "4K@60fps, 1080p@240fps",
      cam_front_resolution: "12 MP, f/2.2, 23mm",
      cam_front_portrait: "Yes",
      cam_front_video: "4K@60fps",
      battery_capacity: "3,046 mAh",
      charging_wired: "18W Fast Charging (Lightning)",
      charging_wireless: "Qi Wireless",
      charging_reverse: "No",
      charger_included: false,
      usb_type: "Lightning",
      has_5g: false,
      wifi_version: "Wi-Fi 6 (802.11ax)",
      bluetooth_version: "Bluetooth 5.0",
      has_nfc: true,
      gps_specs: "GPS, GLONASS, GALILEO, QZSS",
      has_ir_blaster: false,
      has_audio_jack: false,
      usb_version: "USB 2.0",
      sensor_fingerprint: "Face ID",
      has_gyroscope: true,
      has_compass: true,
      has_accelerometer: true,
      has_face_unlock: true,
      android_version: "iOS 13",
      ui_version: "iOS 13 (upgradable)",
      meta_title: "Apple iPhone 11 Pro Full Specifications & Price | TechTweak",
      meta_description: "Full specs of Apple iPhone 11 Pro — A13 Bionic, 5.8\" OLED, Triple 12MP camera. Price in Bangladesh.",
      pros: ["Stunning Super Retina XDR display", "Versatile triple camera system", "Premium stainless steel design"],
      cons: ["64GB base storage is low for a Pro model", "No high refresh rate (only 60Hz)", "Heavy for its size"],
      faqs: [
        { question: "Does iPhone 11 Pro have a telephoto lens?", answer: "Yes, it has a 12MP telephoto lens with 2x optical zoom." }
      ],
      updated_at: new Date()
    },
    {
      name: "iPhone 11 Pro Max",
      slug: "iphone-11-pro-max",
      brand_id: bid,
      is_published: true,
      is_official: true,
      release_date: "2019-09-20",
      model_number: "A2161, A2218, A2220",
      colors: ["Space Gray", "Silver", "Gold", "Midnight Green"],
      made_in: "China",
      phone_variants: "64GB, 256GB, 512GB",
      price_bdt: 95000,
      price_official: 95000,
      price_unofficial: 68000,
      chipset_highlight: "Apple A13 Bionic (7nm+)",
      camera_highlight: "Triple 12MP (Wide + Telephoto + Ultra Wide)",
      display_highlight: "6.5\" Super Retina XDR OLED",
      battery_highlight: "3,969 mAh",
      benchmark_highlight: "AnTuTu ~470,000",
      processor: "Apple A13 Bionic",
      cpu: "Apple A13 Bionic (7nm+) — Hexa-core",
      gpu: "Apple GPU (4-core graphics)",
      fabrication: "7 nm+",
      ram_variants: "4 GB",
      storage_variants: "64 GB, 256 GB, 512 GB",
      storage_type: "NVMe",
      antutu_score: 470000,
      weight: "226 g",
      dimensions: "158 × 77.8 × 8.1 mm",
      build_material: "Glass front, glass back, stainless steel frame",
      sim_type: "Nano-SIM and/or eSIM",
      water_resistance: "IP68 — up to 4m for 30 mins",
      display_type: "Super Retina XDR OLED",
      screen_size: "6.5 inches",
      resolution: "2688 × 1242 pixels",
      refresh_rate: "60 Hz",
      brightness: "800 nits typical, 1200 nits peak (HDR)",
      hdr: "HDR10, Dolby Vision",
      protection: "Scratch-resistant glass",
      pixel_density: "458 ppi",
      cam_count: "Triple",
      cam_main_sensor: "12 MP, f/1.8, 26mm, OIS",
      cam_telephoto: "12 MP, f/2.0, 52mm, 2x optical zoom, OIS",
      cam_ultrawide: "12 MP, f/2.4, 13mm",
      cam_ois: "Yes (Wide + Telephoto)",
      cam_flash: "Dual-LED dual-tone flash",
      cam_video: "4K@60fps, 1080p@240fps",
      cam_front_resolution: "12 MP, f/2.2, 23mm",
      cam_front_portrait: "Yes",
      cam_front_video: "4K@60fps",
      battery_capacity: "3,969 mAh",
      charging_wired: "18W Fast Charging (Lightning)",
      charging_wireless: "Qi Wireless",
      charging_reverse: "No",
      charger_included: false,
      usb_type: "Lightning",
      has_5g: false,
      wifi_version: "Wi-Fi 6 (802.11ax)",
      bluetooth_version: "Bluetooth 5.0",
      has_nfc: true,
      gps_specs: "GPS, GLONASS, GALILEO, QZSS",
      has_ir_blaster: false,
      has_audio_jack: false,
      usb_version: "USB 2.0",
      sensor_fingerprint: "Face ID",
      has_gyroscope: true,
      has_compass: true,
      has_accelerometer: true,
      has_face_unlock: true,
      android_version: "iOS 13",
      ui_version: "iOS 13 (upgradable)",
      meta_title: "Apple iPhone 11 Pro Max Full Specifications & Price | TechTweak",
      meta_description: "Full specs of Apple iPhone 11 Pro Max — A13 Bionic, 6.5\" OLED, Triple 12MP camera. Price in Bangladesh.",
      pros: ["Massive battery life improvement", "Huge, beautiful display", "Top-tier camera system"],
      cons: ["Very heavy at 226g", "Large notch still present", "Slow charging compared to Android rivals"],
      faqs: [
        { question: "How long does iPhone 11 Pro Max battery last?", answer: "It offers one of the best battery lives in its generation, lasting well over a day." }
      ],
      updated_at: new Date()
    }
  ];

  for (const p of phones) {
    const exists = await Phone.findOne({ slug: p.slug });
    if (exists) {
      await Phone.updateOne({ slug: p.slug }, { $set: p });
      console.log(`Updated: ${p.name}`);
    } else {
      await Phone.create(p);
      console.log(`Created: ${p.name}`);
    }
  }

  await mongoose.disconnect();
  console.log("Disconnected from MongoDB. Part 2 complete.");
}

run().catch(e => { console.error(e); process.exit(1); });
