import mongoose from 'mongoose';
import * as dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.resolve(process.cwd(), '.env.local') });

const MONGODB_URI = process.env.MONGODB_URI;

const commonSeoFields = (name: string, price: number, keywordSuffix: string = 'price in bd') => ({
  meta_title: `Samsung ${name} Price in Bangladesh, Specs & Review`,
  meta_keywords: `samsung ${name.toLowerCase()}, ${name.toLowerCase()} price in bd, samsung bangladesh, ${name.toLowerCase()} specs, popular mid-range`,
  meta_description: `Official and Unofficial Samsung ${name} price in Bangladesh. Read full specifications, performance review, camera details, and more.`,
  canonical_url: `https://www.techtweak.tech/phones/samsung/samsung-${name.toLowerCase().replace(/ /g, '-')}`,
  primary_keyword: `samsung ${name.toLowerCase()} ${keywordSuffix}`,
  secondary_keywords: [`samsung ${name.toLowerCase()} price`, `samsung ${name.toLowerCase()} specs`, `samsung ${name.toLowerCase()} review`],
  question_keywords: [
    `what is the price of samsung ${name.toLowerCase()} in bangladesh?`,
    `is samsung ${name.toLowerCase()} good for gaming?`,
    `does samsung ${name.toLowerCase()} have an amoled screen?`
  ],
  faq_schema: [
    { question: `What is the price of Samsung ${name} in Bangladesh?`, answer: `The expected original price of the Samsung ${name} in Bangladesh was around BDT ${price * 115}. Pricing may vary significantly in the current used market.` },
    { question: `Does the Samsung ${name} support 5G?`, answer: `Please refer to the detailed specs below; '5G' models explicitly support next-gen networks, while older A-series models are generally 4G only.` },
    { question: `Is the Samsung ${name} a good phone?`, answer: `The Samsung A-series is widely regarded as one of the most reliable and premium-feeling mid-range smartphone lineups globally.` }
  ]
});

const phonesData = [
  {
    name: "Galaxy A73 5G",
    slug: "samsung-galaxy-a73-5g",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Awesome Gray", "Awesome Mint", "Awesome White"],
    release_date: "2022-04-22",
    price_usd: 500,
    price_bdt: 58000,
    price_display_text: "BDT 58,000",
    processor: "Snapdragon 778G 5G",
    gpu: "Adreno 642L",
    display_type: "Super AMOLED Plus, 120Hz",
    screen_size: "6.7 inches",
    refresh_rate: "120Hz",
    brightness: "800 nits",
    cam_count: "Quad",
    cam_main_sensor: "108 MP, f/1.8, OIS",
    video_recording: "4K@30fps, 1080p@30/60fps",
    battery_capacity: "5000 mAh",
    charging_wired: "25W wired",
    wireless_charging: "No",
    ip_rating: "IP67 dust/water resistant",
    weight: "181 g",
    dimensions: "163.7 x 76.1 x 7.6 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Premium Mid-Range",
    performance_tier: "Mainstream",
    camera_tier: "Excellent",
    battery_tier: "Standard",
    internal_links: { same_brand: ["samsung-galaxy-a53-5g", "samsung-galaxy-s21-fe-5g"] },
    ...commonSeoFields("Galaxy A73 5G", 500),
    overview: "The Galaxy A73 5G sits right at the top of Samsung's mid-range A-series, offering a near-flagship experience. It features a massive and brilliant 6.7-inch 120Hz Super AMOLED Plus display that is perfect for media consumption. Under the hood, the Snapdragon 778G 5G provides incredibly reliable and smooth performance without overheating. The star of the show is the 108MP main camera with OIS, which captures stunning, highly detailed photos that rival much more expensive devices. With IP67 water resistance, a sleek 7.6mm profile, and long-term software support, it bridges the gap between the A-series and the S-series perfectly.",
    highlights: ["108MP OIS Camera", "Snapdragon 778G 5G", "IP67 Water Resistance"],
    pros: ["Extremely reliable performance", "Fantastic main camera", "Very thin and lightweight"],
    cons: ["No charger included in the box", "Plastic back feels slightly cheap"],
    verdict: "An exceptional premium mid-ranger that offers flagships specs where they matter most: camera, screen, and reliability."
  },
  {
    name: "Galaxy A33 5G",
    slug: "samsung-galaxy-a33-5g",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Awesome Black", "Awesome White", "Awesome Blue", "Awesome Peach"],
    release_date: "2022-04-20",
    price_usd: 350,
    price_bdt: 38000,
    price_display_text: "BDT 38,000",
    processor: "Exynos 1280",
    gpu: "Mali-G68",
    display_type: "Super AMOLED, 90Hz",
    screen_size: "6.4 inches",
    refresh_rate: "90Hz",
    brightness: "800 nits",
    cam_count: "Quad",
    cam_main_sensor: "48 MP, f/1.8, OIS",
    video_recording: "4K@30fps, 1080p@30/120fps",
    battery_capacity: "5000 mAh",
    charging_wired: "25W wired",
    wireless_charging: "No",
    ip_rating: "IP67 dust/water resistant",
    weight: "186 g",
    dimensions: "159.7 x 74 x 8.1 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Mid-Range",
    performance_tier: "Basic",
    camera_tier: "Good",
    battery_tier: "Long-Lasting",
    internal_links: { same_brand: ["samsung-galaxy-a53-5g", "samsung-galaxy-a32"] },
    ...commonSeoFields("Galaxy A33 5G", 350),
    overview: "The Galaxy A33 5G represented a major leap forward for Samsung's lower mid-range lineup. For the first time, Samsung brought premium features like IP67 water and dust resistance and Optical Image Stabilization (OIS) on the camera down to this accessible price tier. The 6.4-inch Super AMOLED display runs at a smooth 90Hz, and the Exynos 1280 processor handles daily tasks admirably, though it isn't meant for hardcore gaming. It also features stereo speakers and a robust 5000mAh battery, making it a highly reliable daily driver for the average consumer.",
    highlights: ["IP67 Water Resistance", "48MP Camera with OIS", "90Hz Super AMOLED Display"],
    pros: ["Incredible durability for the price", "Vibrant, smooth display", "Great software update promise"],
    cons: ["Thick bezels around the screen", "Exynos 1280 can stutter occasionally"],
    verdict: "A highly practical and durable smartphone that brings essential premium features to a budget-friendly audience."
  },
  {
    name: "Galaxy A23",
    slug: "samsung-galaxy-a23",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Black", "White", "Peach", "Blue"],
    release_date: "2022-03-25",
    price_usd: 200,
    price_bdt: 23000,
    price_display_text: "BDT 23,000",
    processor: "Snapdragon 680 4G",
    gpu: "Adreno 610",
    display_type: "PLS LCD, 90Hz",
    screen_size: "6.6 inches",
    refresh_rate: "90Hz",
    brightness: "400 nits",
    cam_count: "Quad",
    cam_main_sensor: "50 MP, f/1.8, PDAF, OIS",
    video_recording: "1080p@30fps",
    battery_capacity: "5000 mAh",
    charging_wired: "25W wired",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "195 g",
    dimensions: "164.5 x 76.9 x 8.4 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Budget",
    performance_tier: "Basic",
    camera_tier: "Basic",
    battery_tier: "Long-Lasting",
    internal_links: { same_brand: ["samsung-galaxy-a13", "samsung-galaxy-a33-5g"] },
    ...commonSeoFields("Galaxy A23", 200),
    overview: "The Galaxy A23 focuses on delivering a reliable Samsung experience on a tight budget. Its standout feature is the inclusion of OIS (Optical Image Stabilization) on its 50MP main camera, a rarity in the entry-level segment that helps significantly with taking sharp photos and stable videos. It is powered by the highly efficient Snapdragon 680 processor, which, combined with the 5000mAh battery, results in phenomenal multi-day battery life. The 90Hz PLS LCD display is smooth, though it lacks the vibrant colors of Samsung's signature AMOLED panels.",
    highlights: ["50MP Camera with OIS", "Snapdragon 680 Processor", "5000mAh Battery"],
    pros: ["Great battery efficiency", "OIS helps with photo clarity", "Smooth 90Hz display"],
    cons: ["LCD screen instead of AMOLED", "Noticeably slow charging"],
    verdict: "A solid entry-level choice that prioritizes battery life and camera stability over raw processing speed."
  },
  {
    name: "Galaxy A13",
    slug: "samsung-galaxy-a13",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Black", "White", "Peach", "Blue"],
    release_date: "2022-03-23",
    price_usd: 150,
    price_bdt: 18000,
    price_display_text: "BDT 18,000",
    processor: "Exynos 850",
    gpu: "Mali-G52",
    display_type: "PLS LCD",
    screen_size: "6.6 inches",
    refresh_rate: "60Hz",
    brightness: "400 nits",
    cam_count: "Quad",
    cam_main_sensor: "50 MP, f/1.8, PDAF",
    video_recording: "1080p@30fps",
    battery_capacity: "5000 mAh",
    charging_wired: "15W wired",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "195 g",
    dimensions: "165.1 x 76.4 x 8.8 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Entry-Level",
    performance_tier: "Basic",
    camera_tier: "Basic",
    battery_tier: "Long-Lasting",
    internal_links: { same_brand: ["samsung-galaxy-a23"] },
    ...commonSeoFields("Galaxy A13", 150),
    overview: "The Galaxy A13 is Samsung's quintessential entry-level smartphone, designed for users who just need the basics. It features a large 6.6-inch 1080p display, which is sharp enough for media consumption, though it utilizes basic LCD technology. It runs on the older Exynos 850 processor, which handles calls, texts, and light browsing perfectly fine, but will struggle noticeably with heavy multitasking or gaming. The 50MP main camera takes acceptable daylight shots, and the 5000mAh battery provides excellent endurance, making it a reliable backup phone or a first smartphone for teenagers.",
    highlights: ["Large 6.6-inch 1080p Display", "5000mAh Battery", "50MP Main Camera"],
    pros: ["Affordable Samsung entry point", "Good battery life", "Sharp 1080p resolution"],
    cons: ["Very slow performance", "Thick, somewhat outdated design"],
    verdict: "A strictly basic smartphone; buy it only if you need Samsung's One UI software on the absolute lowest budget."
  },
  {
    name: "Galaxy A80",
    slug: "samsung-galaxy-a80",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Angel Gold", "Ghost White", "Phantom Black"],
    release_date: "2019-05-29",
    price_usd: 600,
    price_bdt: 55000,
    price_display_text: "BDT 55,000",
    processor: "Snapdragon 730",
    gpu: "Adreno 618",
    display_type: "Super AMOLED",
    screen_size: "6.7 inches",
    refresh_rate: "60Hz",
    brightness: "600 nits",
    cam_count: "Triple (Rotating)",
    cam_main_sensor: "48 MP, f/2.0, PDAF",
    video_recording: "4K@30fps, 1080p@30/60fps",
    battery_capacity: "3700 mAh",
    charging_wired: "25W wired",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "220 g",
    dimensions: "165.2 x 76.5 x 9.3 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Premium Mid-Range",
    performance_tier: "Mainstream",
    camera_tier: "Good",
    battery_tier: "Basic",
    internal_links: { same_brand: ["samsung-galaxy-a70", "samsung-galaxy-a90-5g"] },
    ...commonSeoFields("Galaxy A80", 600),
    overview: "The Galaxy A80 is easily one of the most unique and ambitious smartphones Samsung has ever built. To achieve a completely uninterrupted, bezel-less 6.7-inch display, Samsung engineered a motorized slide-up, rotating camera mechanism. This meant the high-quality 48MP rear camera system flipped over to become the selfie camera, resulting in the best selfie quality available on any phone at the time. However, this complex moving part made the phone extremely heavy (220g) and resulted in a relatively small 3700mAh battery, limiting its overall practicality despite the undeniable cool factor.",
    highlights: ["Motorized rotating camera", "Completely bezel-less display", "Snapdragon 730 Processor"],
    pros: ["Incredible, uninterrupted screen", "Top-tier selfie quality", "Great conversation starter"],
    cons: ["Very heavy and bulky", "Moving parts are prone to failure", "Small battery"],
    verdict: "A fascinating piece of smartphone history that prioritized futuristic design over everyday practicality."
  },
  {
    name: "Galaxy A70s",
    slug: "samsung-galaxy-a70s",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Prism Crush Red", "Prism Crush White", "Prism Crush Black"],
    release_date: "2019-09-27",
    price_usd: 400,
    price_bdt: 40000,
    price_display_text: "BDT 40,000",
    processor: "Snapdragon 675",
    gpu: "Adreno 612",
    display_type: "Super AMOLED",
    screen_size: "6.7 inches",
    refresh_rate: "60Hz",
    brightness: "600 nits",
    cam_count: "Triple",
    cam_main_sensor: "64 MP, f/1.8, PDAF",
    video_recording: "4K@30fps, 1080p@30/240fps",
    battery_capacity: "4500 mAh",
    charging_wired: "25W wired",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "187 g",
    dimensions: "164.3 x 76.7 x 7.9 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Mid-Range",
    performance_tier: "Basic",
    camera_tier: "Good",
    battery_tier: "Standard",
    internal_links: { same_brand: ["samsung-galaxy-a70", "samsung-galaxy-a50s"] },
    ...commonSeoFields("Galaxy A70s", 400),
    overview: "The Galaxy A70s was a minor but effective refresh of the popular A70. It introduced a striking geometric 'Prism Crush' design on the back panel that caught the light beautifully. The major upgrade was the main camera, jumping from 32MP to a much sharper 64MP sensor, allowing for better daylight photography and improved low-light performance. It retained the excellent 6.7-inch Super AMOLED screen, the reliable Snapdragon 675 processor, and the 4500mAh battery with 25W fast charging, making it a fantastic multimedia device for consuming video content.",
    highlights: ["Upgraded 64MP Camera", "6.7-inch Super AMOLED Display", "Striking geometric design"],
    pros: ["Massive, beautiful screen", "Good battery life with fast charging", "Solid camera upgrade"],
    cons: ["Processor remained the same as the A70", "No water resistance"],
    verdict: "A solid iterative update that offered a better camera and a flashier design to an already great multimedia phone."
  },
  {
    name: "Galaxy A50s",
    slug: "samsung-galaxy-a50s",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Prism Crush Black", "Prism Crush White", "Prism Crush Green", "Prism Crush Violet"],
    release_date: "2019-09-11",
    price_usd: 300,
    price_bdt: 30000,
    price_display_text: "BDT 30,000",
    processor: "Exynos 9611",
    gpu: "Mali-G72 MP3",
    display_type: "Super AMOLED",
    screen_size: "6.4 inches",
    refresh_rate: "60Hz",
    brightness: "600 nits",
    cam_count: "Triple",
    cam_main_sensor: "48 MP, f/2.0, PDAF",
    video_recording: "4K@30fps, 1080p@30fps",
    battery_capacity: "4000 mAh",
    charging_wired: "15W wired",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "169 g",
    dimensions: "158.5 x 74.5 x 7.7 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Budget",
    performance_tier: "Basic",
    camera_tier: "Basic",
    battery_tier: "Standard",
    internal_links: { same_brand: ["samsung-galaxy-a50", "samsung-galaxy-a51"] },
    ...commonSeoFields("Galaxy A50s", 300),
    overview: "The Galaxy A50s took the incredibly successful blueprint of the A50 and applied necessary polish. It upgraded the camera system to a 48MP main sensor, providing significantly sharper photos, and bumped the front camera to 32MP for much better selfies. It also introduced the slightly more capable Exynos 9611 processor. Visually, it adopted the new geometric 'Prism Crush' back design, making it stand out in a crowd. It retained the incredibly sleek and lightweight 7.7mm profile, making it one of the most comfortable phones to hold in its class.",
    highlights: ["48MP Main Camera", "Geometric Prism Crush Design", "Sleek and lightweight build"],
    pros: ["Comfortable, ergonomic design", "Beautiful Super AMOLED screen", "Good camera upgrade over the A50"],
    cons: ["In-display fingerprint scanner was slow", "15W charging is outdated"],
    verdict: "A perfect refinement of a classic. It improved the cameras and design while keeping the excellent form factor."
  },
  {
    name: "Galaxy A30s",
    slug: "samsung-galaxy-a30s",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Prism Crush Black", "Prism Crush White", "Prism Crush Green", "Prism Crush Violet"],
    release_date: "2019-09-11",
    price_usd: 220,
    price_bdt: 22000,
    price_display_text: "BDT 22,000",
    processor: "Exynos 7904",
    gpu: "Mali-G71 MP2",
    display_type: "Super AMOLED",
    screen_size: "6.4 inches",
    refresh_rate: "60Hz",
    brightness: "400 nits",
    cam_count: "Triple",
    cam_main_sensor: "25 MP, f/1.7, PDAF",
    video_recording: "1080p@30fps",
    battery_capacity: "4000 mAh",
    charging_wired: "15W wired",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "169 g",
    dimensions: "158.5 x 74.7 x 7.8 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Budget",
    performance_tier: "Basic",
    camera_tier: "Basic",
    battery_tier: "Standard",
    internal_links: { same_brand: ["samsung-galaxy-a30", "samsung-galaxy-a50s"] },
    ...commonSeoFields("Galaxy A30s", 220),
    overview: "The Galaxy A30s was a mixed bag of upgrades and downgrades compared to the original A30. It upgraded the design with the new holographic pattern and added an in-display fingerprint scanner (which felt modern but was quite slow). It also improved the main camera to a 25MP sensor and added a dedicated depth sensor. However, to accommodate these changes, Samsung downgraded the screen resolution from 1080p to 720p. While the Super AMOLED panel still provided vibrant colors, the drop in sharpness was noticeable, making it a polarizing device among fans.",
    highlights: ["In-display fingerprint scanner", "25MP Triple Camera", "Prism Crush Design"],
    pros: ["Looks very premium", "Vibrant colors from the AMOLED panel", "Good battery life"],
    cons: ["Screen resolution downgraded to 720p", "Fingerprint scanner was frustratingly slow"],
    verdict: "A stylish phone that unfortunately sacrificed screen sharpness to include modern gimmicks like an in-display scanner."
  },
  {
    name: "Galaxy A20s",
    slug: "samsung-galaxy-a20s",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Black", "Blue", "Red", "Green"],
    release_date: "2019-10-05",
    price_usd: 170,
    price_bdt: 18000,
    price_display_text: "BDT 18,000",
    processor: "Snapdragon 450",
    gpu: "Adreno 506",
    display_type: "IPS LCD",
    screen_size: "6.5 inches",
    refresh_rate: "60Hz",
    brightness: "400 nits",
    cam_count: "Triple",
    cam_main_sensor: "13 MP, f/1.8, PDAF",
    video_recording: "1080p@30fps",
    battery_capacity: "4000 mAh",
    charging_wired: "15W wired",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "183 g",
    dimensions: "163.3 x 77.5 x 8 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Budget",
    performance_tier: "Basic",
    camera_tier: "Basic",
    battery_tier: "Standard",
    internal_links: { same_brand: ["samsung-galaxy-a20", "samsung-galaxy-a10s"] },
    ...commonSeoFields("Galaxy A20s", 170),
    overview: "The Galaxy A20s is an entry-level smartphone that opted for size over display quality. Unlike the standard A20 which had a Super AMOLED screen, the A20s switched to a larger 6.5-inch IPS LCD panel. While the screen was bigger, the colors were less vibrant. It was powered by the entry-level Snapdragon 450 processor, which provided very basic performance. It did, however, upgrade to a triple-camera setup by adding an ultra-wide lens, giving budget users more versatility in their photography.",
    highlights: ["Large 6.5-inch display", "Triple camera setup", "Snapdragon processor"],
    pros: ["Good screen size for media", "Ultra-wide camera is useful", "Reliable basic performance"],
    cons: ["Lost the AMOLED screen of the A20", "Very slow processor"],
    verdict: "A basic phone that sacrificed the excellent AMOLED screen of its predecessor in favor of a slightly larger footprint."
  },
  {
    name: "Galaxy A10s",
    slug: "samsung-galaxy-a10s",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Blue", "Green", "Red", "Black"],
    release_date: "2019-08-27",
    price_usd: 130,
    price_bdt: 14000,
    price_display_text: "BDT 14,000",
    processor: "Mediatek MT6762 Helio P22",
    gpu: "PowerVR GE8320",
    display_type: "PLS LCD",
    screen_size: "6.2 inches",
    refresh_rate: "60Hz",
    brightness: "400 nits",
    cam_count: "Dual",
    cam_main_sensor: "13 MP, f/1.8, AF",
    video_recording: "1080p@30fps",
    battery_capacity: "4000 mAh",
    charging_wired: "Standard",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "168 g",
    dimensions: "156.9 x 75.8 x 7.8 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Entry-Level",
    performance_tier: "Basic",
    camera_tier: "Basic",
    battery_tier: "Standard",
    internal_links: { same_brand: ["samsung-galaxy-a10"] },
    ...commonSeoFields("Galaxy A10s", 130),
    overview: "The Galaxy A10s was an incremental update to Samsung's cheapest A-series phone. The most significant upgrade over the original A10 was the addition of a rear-mounted fingerprint scanner, providing much-needed biometric security. It also bumped the battery capacity up to 4000mAh, significantly improving longevity, and added a secondary depth sensor to the camera for basic portrait mode effects. Powered by a MediaTek Helio P22 chip, performance was strictly meant for casual usage like messaging and social media.",
    highlights: ["Rear fingerprint scanner", "4000mAh Battery", "Dual camera setup"],
    pros: ["Much better battery than the A10", "Added biometric security", "Very affordable"],
    cons: ["Performance is very sluggish", "Low-resolution screen"],
    verdict: "A necessary update that added basic security and battery life to Samsung's absolute cheapest smartphone offering."
  },
  {
    name: "Galaxy A9 (2018)",
    slug: "samsung-galaxy-a9-2018",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Caviar Black", "Lemonade Blue", "Bubblegum Pink"],
    release_date: "2018-11-01",
    price_usd: 500,
    price_bdt: 45000,
    price_display_text: "BDT 45,000",
    processor: "Snapdragon 660",
    gpu: "Adreno 512",
    display_type: "Super AMOLED",
    screen_size: "6.3 inches",
    refresh_rate: "60Hz",
    brightness: "600 nits",
    cam_count: "Quad",
    cam_main_sensor: "24 MP, f/1.7, PDAF",
    video_recording: "4K@30fps, 1080p@30fps",
    battery_capacity: "3800 mAh",
    charging_wired: "18W wired",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "183 g",
    dimensions: "162.5 x 77 x 7.8 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Premium Mid-Range",
    performance_tier: "Basic",
    camera_tier: "Good",
    battery_tier: "Basic",
    internal_links: { same_brand: ["samsung-galaxy-a7-2018"] },
    ...commonSeoFields("Galaxy A9 (2018)", 500),
    overview: "The Galaxy A9 (2018) holds a special place in history as the world's first smartphone to feature a quad-camera setup on the rear. Samsung threw every lens imaginable onto the back: a high-res main camera, an ultra-wide lens, a telephoto lens for optical zoom, and a depth sensor. It featured a beautiful glass design with striking gradient colors. Powered by the reliable Snapdragon 660, it was a solid performer, though the excessive number of cameras was largely seen as a marketing gimmick since the image processing software struggled to keep up.",
    highlights: ["World's first Quad Camera phone", "Striking gradient design", "Super AMOLED Display"],
    pros: ["Highly versatile camera system", "Beautiful AMOLED screen", "Solid build quality"],
    cons: ["Camera quality didn't match the quantity", "A bit overpriced at launch"],
    verdict: "A fascinating piece of Samsung history that pioneered the multi-camera trend we see on every modern smartphone today."
  },
  {
    name: "Galaxy A7 (2018)",
    slug: "samsung-galaxy-a7-2018",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Black", "Blue", "Gold", "Pink"],
    release_date: "2018-10-01",
    price_usd: 350,
    price_bdt: 32000,
    price_display_text: "BDT 32,000",
    processor: "Exynos 7885",
    gpu: "Mali-G71",
    display_type: "Super AMOLED",
    screen_size: "6.0 inches",
    refresh_rate: "60Hz",
    brightness: "600 nits",
    cam_count: "Triple",
    cam_main_sensor: "24 MP, f/1.7, PDAF",
    video_recording: "1080p@30fps",
    battery_capacity: "3300 mAh",
    charging_wired: "15W wired",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "168 g",
    dimensions: "159.8 x 76.8 x 7.5 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Mid-Range",
    performance_tier: "Basic",
    camera_tier: "Good",
    battery_tier: "Basic",
    internal_links: { same_brand: ["samsung-galaxy-a9-2018"] },
    ...commonSeoFields("Galaxy A7 (2018)", 350),
    overview: "The Galaxy A7 (2018) was Samsung's first foray into the triple-camera world, paving the way for the massive camera arrays we see today. It introduced an ultra-wide-angle lens to the mid-range segment, allowing users to capture sweeping landscapes. It also featured an innovative side-mounted fingerprint scanner integrated into the power button, a design choice that proved highly popular and ergonomic. With its flat 6.0-inch Super AMOLED display and a very slim 7.5mm profile, it was a stylish and highly capable multimedia device.",
    highlights: ["First Samsung triple-camera", "Side-mounted fingerprint scanner", "Very slim 7.5mm profile"],
    pros: ["Ultra-wide camera was a game-changer", "Ergonomic fingerprint placement", "Vibrant display"],
    cons: ["Battery was quite small", "Still used microUSB instead of Type-C"],
    verdict: "A stylish trailblazer that introduced the ultra-wide lens to the masses and popularized the side-mounted fingerprint scanner."
  }
];

async function run() {
  try {
    await mongoose.connect(MONGODB_URI as string);
    console.log("✅ Connected to MongoDB");

    const Brand = mongoose.models.Brand || mongoose.model("Brand", new mongoose.Schema({}, { strict: false }));
    const samsungBrand = await Brand.findOne({ name: /Samsung/i });

    const PhoneSchema = new mongoose.Schema({}, { strict: false });
    const Phone = mongoose.models.Phone || mongoose.model("Phone", PhoneSchema);

    for (const phone of phonesData) {
      if (samsungBrand) (phone as any).brand_id = samsungBrand._id;
      phone.updated_at = new Date() as any;
      await Phone.findOneAndUpdate({ slug: phone.slug }, { $set: phone }, { upsert: true, new: true });
      console.log(`✅ Inserted/Updated: ${phone.name}`);
    }

    console.log("🎉 Samsung Batch 10 (A Series Expansion) completed! Added 12 phones with strict specs.");

  } catch (err) {
    console.error("❌ Error:", (err as Error).message);
  } finally {
    await mongoose.disconnect();
  }
}

run();
