import mongoose from 'mongoose';
import * as dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.resolve(process.cwd(), '.env.local') });

const MONGODB_URI = process.env.MONGODB_URI;

const commonSeoFields = (name: string, price: number, keywordSuffix: string = 'price in bd') => ({
  meta_title: `Samsung ${name} Price in Bangladesh, Specs & Review`,
  meta_keywords: `samsung ${name.toLowerCase()}, ${name.toLowerCase()} price in bd, samsung bangladesh, ${name.toLowerCase()} specs, m series`,
  meta_description: `Official and Unofficial Samsung ${name} price in Bangladesh. Uncover its massive battery life, processing power, and full hardware specifications.`,
  canonical_url: `https://www.techtweak.tech/phones/samsung/samsung-${name.toLowerCase().replace(/ /g, '-')}`,
  primary_keyword: `samsung ${name.toLowerCase()} ${keywordSuffix}`,
  secondary_keywords: [`samsung ${name.toLowerCase()} price`, `samsung ${name.toLowerCase()} specs`, `samsung ${name.toLowerCase()} battery test`],
  question_keywords: [
    `what is the price of samsung ${name.toLowerCase()} in bangladesh?`,
    `is samsung ${name.toLowerCase()} good for gaming?`,
    `what is the battery capacity of samsung ${name.toLowerCase()}?`
  ],
  faq_schema: [
    { question: `What is the price of Samsung ${name} in Bangladesh?`, answer: `The expected launch price of the Samsung ${name} in Bangladesh was around BDT ${price * 115}. Check local stores for exact current pricing.` },
    { question: `Does the Samsung ${name} have an AMOLED display?`, answer: `Please refer to the display specifications below. Most higher-end M-series models feature Super AMOLED screens.` },
    { question: `Is the Samsung ${name} water-resistant?`, answer: `Generally, Samsung's M-series focuses on battery and performance rather than premium features like IP water resistance.` }
  ]
});

const phonesData = [
  {
    name: "Galaxy M54",
    slug: "samsung-galaxy-m54",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Dark Blue", "Silver"],
    release_date: "2023-04-18",
    price_usd: 380,
    price_bdt: 45000,
    price_display_text: "BDT 45,000",
    processor: "Exynos 1380",
    gpu: "Mali-G68 MP5",
    display_type: "Super AMOLED Plus, 120Hz",
    screen_size: "6.7 inches",
    refresh_rate: "120Hz",
    brightness: "800 nits",
    cam_count: "Triple",
    cam_main_sensor: "108 MP, f/1.8, OIS",
    video_recording: "4K@30fps, 1080p@30/60fps",
    battery_capacity: "6000 mAh",
    charging_wired: "25W wired",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "199 g",
    dimensions: "164.9 x 77.3 x 8.4 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Premium Mid-Range",
    performance_tier: "Mainstream",
    camera_tier: "Excellent",
    battery_tier: "Endurance",
    internal_links: { same_brand: ["samsung-galaxy-m53", "samsung-galaxy-a54-5g"] },
    ...commonSeoFields("Galaxy M54", 380),
    overview: "The Galaxy M54 is the pinnacle of Samsung's 'Battery King' philosophy, paired with surprisingly premium camera hardware. It features a stunning 108MP main camera with Optical Image Stabilization (OIS), bringing near-flagship photography to the M-series. The massive 6.7-inch 120Hz Super AMOLED Plus screen is a joy to use, providing vibrant colors and smooth scrolling. Its 6000mAh battery guarantees multi-day usage, making it an absolute powerhouse for heavy media consumers. The only notable drawbacks are the lack of water resistance and stereo speakers, features Samsung reserves for the similarly priced A54.",
    highlights: ["108MP Camera with OIS", "6000mAh Battery", "6.7-inch 120Hz Super AMOLED Plus"],
    pros: ["Fantastic battery life", "Extremely sharp camera", "Beautiful large display"],
    cons: ["No IP water resistance", "No stereo speakers", "Exynos 1380 can struggle with 3D gaming"],
    verdict: "An exceptional multimedia and photography device that prioritizes battery endurance and screen size over premium build materials."
  },
  {
    name: "Galaxy M53",
    slug: "samsung-galaxy-m53",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Green", "Blue", "Brown"],
    release_date: "2022-04-22",
    price_usd: 350,
    price_bdt: 40000,
    price_display_text: "BDT 40,000",
    processor: "MediaTek Dimensity 900",
    gpu: "Mali-G68 MC4",
    display_type: "Super AMOLED Plus, 120Hz",
    screen_size: "6.7 inches",
    refresh_rate: "120Hz",
    brightness: "420 nits",
    cam_count: "Quad",
    cam_main_sensor: "108 MP, f/1.8, PDAF",
    video_recording: "4K@30fps, 1080p@30/60fps",
    battery_capacity: "5000 mAh",
    charging_wired: "25W wired",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "176 g",
    dimensions: "164.7 x 77 x 7.4 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Mid-Range",
    performance_tier: "Mainstream",
    camera_tier: "Excellent",
    battery_tier: "Long-Lasting",
    internal_links: { same_brand: ["samsung-galaxy-m52-5g", "samsung-galaxy-m54"] },
    ...commonSeoFields("Galaxy M53", 350),
    overview: "The Galaxy M53 took a very unusual design approach for an M-series phone: it prioritized thinness over battery size. Instead of the massive 6000mAh or 7000mAh batteries of its predecessors, it opted for a standard 5000mAh battery to achieve an incredibly sleek 7.4mm profile, weighing only 176 grams. It was the first M-series phone to introduce a 108MP camera, though it lacked the OIS found on later models. Powered by the MediaTek Dimensity 900, it offered very stable and cool performance, paired with a gorgeous 6.7-inch 120Hz Super AMOLED screen.",
    highlights: ["Incredibly thin 7.4mm profile", "108MP Quad Camera", "120Hz Super AMOLED Plus"],
    pros: ["Extremely lightweight and comfortable", "Stunning display", "Stable Dimensity processor"],
    cons: ["Battery life is a downgrade from older M-series", "No OIS on the camera", "No headphone jack"],
    verdict: "A beautifully thin and lightweight mid-ranger that sacrificed the legendary M-series battery life for premium aesthetics."
  },
  {
    name: "Galaxy M52 5G",
    slug: "samsung-galaxy-m52-5g",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Icy Blue", "Blazing Black", "White"],
    release_date: "2021-10-03",
    price_usd: 320,
    price_bdt: 36000,
    price_display_text: "BDT 36,000",
    processor: "Snapdragon 778G 5G",
    gpu: "Adreno 642L",
    display_type: "Super AMOLED Plus, 120Hz",
    screen_size: "6.7 inches",
    refresh_rate: "120Hz",
    brightness: "800 nits",
    cam_count: "Triple",
    cam_main_sensor: "64 MP, f/1.8, PDAF",
    video_recording: "4K@30fps, 1080p@30/60fps",
    battery_capacity: "5000 mAh",
    charging_wired: "25W wired",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "173 g",
    dimensions: "164.2 x 76.4 x 7.4 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Mid-Range",
    performance_tier: "Mainstream",
    camera_tier: "Good",
    battery_tier: "Long-Lasting",
    internal_links: { same_brand: ["samsung-galaxy-m53", "samsung-galaxy-m51"] },
    ...commonSeoFields("Galaxy M52 5G", 320),
    overview: "The Galaxy M52 5G is widely considered a fan favorite among mid-range gamers because it utilized the phenomenal Snapdragon 778G processor. This chip provided incredible, highly stable performance without the thermal throttling issues associated with contemporary Exynos chips. Similar to the M53, it opted for a sleek 7.4mm design and a 5000mAh battery instead of the bulky 7000mAh monster found in the M51. The 120Hz Super AMOLED Plus screen was incredibly fluid, and while the camera system lacked OIS, it still captured great daylight photos.",
    highlights: ["Phenomenal Snapdragon 778G", "Ultra-slim 7.4mm design", "120Hz Super AMOLED Plus"],
    pros: ["Fantastic performance for gaming", "Incredibly sleek and lightweight", "Gorgeous display"],
    cons: ["Battery is much smaller than the M51", "No headphone jack", "No OIS"],
    verdict: "The undisputed performance king of the M-series, prioritizing the flawless Snapdragon 778G chip and a sleek design over pure battery size."
  },
  {
    name: "Galaxy M34 5G",
    slug: "samsung-galaxy-m34-5g",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Midnight Blue", "Prism Silver", "Waterfall Blue"],
    release_date: "2023-07-15",
    price_usd: 230,
    price_bdt: 26000,
    price_display_text: "BDT 26,000",
    processor: "Exynos 1280",
    gpu: "Mali-G68",
    display_type: "Super AMOLED, 120Hz",
    screen_size: "6.5 inches",
    refresh_rate: "120Hz",
    brightness: "1000 nits (peak)",
    cam_count: "Triple",
    cam_main_sensor: "50 MP, f/1.8, PDAF, OIS",
    video_recording: "4K@30fps, 1080p@30fps",
    battery_capacity: "6000 mAh",
    charging_wired: "25W wired",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "208 g",
    dimensions: "161.7 x 77.2 x 8.8 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Budget",
    performance_tier: "Basic",
    camera_tier: "Good",
    battery_tier: "Endurance",
    internal_links: { same_brand: ["samsung-galaxy-m33", "samsung-galaxy-f34-5g"] },
    ...commonSeoFields("Galaxy M34 5G", 230),
    overview: "The Galaxy M34 5G is the quintessential budget workhorse. It brought a massively improved display to the M30 lineage, featuring a 6.5-inch 120Hz Super AMOLED panel that can reach 1000 nits of peak brightness. Crucially, it added Optical Image Stabilization (OIS) to its 50MP camera, a massive advantage for a budget phone that helps eliminate blurry photos. Powered by the Exynos 1280 and fueled by a 6000mAh battery, it offers tremendous battery life. The only real downside is the heavily dated waterdrop notch design on the front screen.",
    highlights: ["120Hz Super AMOLED (1000 nits)", "50MP Camera with OIS", "6000mAh Battery"],
    pros: ["Incredible screen quality for the price", "OIS drastically improves camera reliability", "Outstanding battery life"],
    cons: ["Outdated teardrop notch", "Noticeably thick bezels", "Processor is decent but not meant for gaming"],
    verdict: "A perfect blend of display quality, battery life, and camera stability for those who don't mind an outdated front design."
  },
  {
    name: "Galaxy M33",
    slug: "samsung-galaxy-m33",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Green", "Blue", "Brown"],
    release_date: "2022-04-08",
    price_usd: 210,
    price_bdt: 24000,
    price_display_text: "BDT 24,000",
    processor: "Exynos 1280",
    gpu: "Mali-G68",
    display_type: "TFT LCD, 120Hz",
    screen_size: "6.6 inches",
    refresh_rate: "120Hz",
    brightness: "400 nits",
    cam_count: "Quad",
    cam_main_sensor: "50 MP, f/1.8, PDAF",
    video_recording: "4K@30fps, 1080p@30fps",
    battery_capacity: "6000 mAh",
    charging_wired: "25W wired",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "215 g",
    dimensions: "165.4 x 76.9 x 9.4 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Budget",
    performance_tier: "Basic",
    camera_tier: "Basic",
    battery_tier: "Endurance",
    internal_links: { same_brand: ["samsung-galaxy-m32", "samsung-galaxy-m34-5g"] },
    ...commonSeoFields("Galaxy M33", 210),
    overview: "The Galaxy M33 made a highly controversial downgrade that upset many Samsung fans: it ditched the beloved Super AMOLED display of the M32 in favor of a standard TFT LCD screen. While the screen was bumped to a 120Hz refresh rate, the loss of vibrant colors and deep blacks was noticeable. However, it made up for this by upgrading the processor to the 5G-capable Exynos 1280, providing a significant performance boost over its predecessor. It retained the massive 6000mAh battery (in certain regions), making it a reliable, albeit unexciting, budget 5G phone.",
    highlights: ["120Hz TFT LCD Display", "Exynos 1280 5G Processor", "Massive 6000mAh battery"],
    pros: ["Solid entry-level 5G performance", "Outstanding battery life", "Smooth 120Hz refresh rate"],
    cons: ["LCD screen was a massive downgrade from AMOLED", "Very thick and heavy device", "No charger included"],
    verdict: "A sturdy, battery-focused 5G budget phone that unfortunately sacrificed Samsung's signature AMOLED screen."
  },
  {
    name: "Galaxy M32",
    slug: "samsung-galaxy-m32",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Black", "Light Blue", "White"],
    release_date: "2021-06-28",
    price_usd: 190,
    price_bdt: 22000,
    price_display_text: "BDT 22,000",
    processor: "Mediatek Helio G80",
    gpu: "Mali-G52 MC2",
    display_type: "Super AMOLED, 90Hz",
    screen_size: "6.4 inches",
    refresh_rate: "90Hz",
    brightness: "800 nits",
    cam_count: "Quad",
    cam_main_sensor: "64 MP, f/1.8, PDAF",
    video_recording: "1080p@30fps",
    battery_capacity: "6000 mAh",
    charging_wired: "25W wired",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "196 g",
    dimensions: "159.3 x 74 x 9.3 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Budget",
    performance_tier: "Basic",
    camera_tier: "Good",
    battery_tier: "Endurance",
    internal_links: { same_brand: ["samsung-galaxy-m31", "samsung-galaxy-m32-5g"] },
    ...commonSeoFields("Galaxy M32", 190),
    overview: "The Galaxy M32 was heavily focused on delivering the best possible screen experience in the budget category. It featured a gorgeous 6.4-inch Super AMOLED display with a 90Hz refresh rate and an impressive 800 nits of peak brightness. This made it vastly superior to almost every other phone in its price bracket for media consumption. However, the trade-off was the incredibly sluggish MediaTek Helio G80 processor, which struggled with multitasking and any form of gaming. The 6000mAh battery provided legendary endurance, but users had to be patient with the phone's speed.",
    highlights: ["90Hz Super AMOLED (800 nits)", "6000mAh Battery", "64MP Quad Camera"],
    pros: ["Best-in-class display for the price", "Unbelievable battery life", "Good daylight camera performance"],
    cons: ["Helio G80 processor is very slow", "Noticeable UI lag", "No 4K video recording"],
    verdict: "A phone designed purely for binge-watching Netflix and scrolling social media, held back only by a weak processor."
  },
  {
    name: "Galaxy M32 5G",
    slug: "samsung-galaxy-m32-5g",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Slate Black", "Sky Blue"],
    release_date: "2021-09-02",
    price_usd: 210,
    price_bdt: 24000,
    price_display_text: "BDT 24,000",
    processor: "MediaTek Dimensity 720",
    gpu: "Mali-G57 MC3",
    display_type: "TFT LCD",
    screen_size: "6.5 inches",
    refresh_rate: "60Hz",
    brightness: "400 nits",
    cam_count: "Quad",
    cam_main_sensor: "48 MP, f/1.8, PDAF",
    video_recording: "4K@30fps, 1080p@30fps",
    battery_capacity: "5000 mAh",
    charging_wired: "15W wired",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "205 g",
    dimensions: "164.2 x 76.1 x 9.1 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Budget",
    performance_tier: "Basic",
    camera_tier: "Basic",
    battery_tier: "Long-Lasting",
    internal_links: { same_brand: ["samsung-galaxy-m32", "samsung-galaxy-m42-5g"] },
    ...commonSeoFields("Galaxy M32 5G", 210),
    overview: "The Galaxy M32 5G was a very confusing release from Samsung. To add 5G capabilities while keeping the price low, Samsung utilized the Dimensity 720 processor. However, they paid for it by completely ruining the display. It swapped the gorgeous 90Hz AMOLED of the standard M32 for an incredibly low-resolution (720p) TFT LCD screen with thick bezels. It also downgraded the battery to 5000mAh and reduced the charging speed to a painful 15W. It was essentially a completely different, much worse phone that only existed to say it had 5G.",
    highlights: ["Dimensity 720 5G Processor", "48MP Quad Camera", "5000mAh Battery"],
    pros: ["Brought 5G to a lower price point", "Decent processor performance", "Reliable battery"],
    cons: ["Terrible 720p TFT display", "Downgraded battery from the 4G model", "Very slow 15W charging"],
    verdict: "A deeply compromised device that sacrificed screen quality and battery just to include a 5G modem."
  },
  {
    name: "Galaxy M14 5G",
    slug: "samsung-galaxy-m14-5g",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Navy Blue", "Light Blue", "Silver"],
    release_date: "2023-03-08",
    price_usd: 160,
    price_bdt: 18000,
    price_display_text: "BDT 18,000",
    processor: "Exynos 1330",
    gpu: "Mali-G68 MP2",
    display_type: "PLS LCD, 90Hz",
    screen_size: "6.6 inches",
    refresh_rate: "90Hz",
    brightness: "400 nits",
    cam_count: "Triple",
    cam_main_sensor: "50 MP, f/1.8, PDAF",
    video_recording: "1080p@30fps",
    battery_capacity: "6000 mAh",
    charging_wired: "25W wired",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "206 g",
    dimensions: "166.8 x 77.2 x 9.4 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Entry-Level",
    performance_tier: "Basic",
    camera_tier: "Basic",
    battery_tier: "Endurance",
    internal_links: { same_brand: ["samsung-galaxy-f14-5g", "samsung-galaxy-m13"] },
    ...commonSeoFields("Galaxy M14 5G", 160),
    overview: "The Galaxy M14 5G is essentially identical to the F14 5G, designed to bring robust battery life and next-gen connectivity to the masses. It features the highly efficient 5nm Exynos 1330 processor, which handles the Android OS surprisingly well for an entry-level device. The massive 6000mAh battery is the star of the show, easily pushing two full days of usage. While the 6.6-inch PLS LCD screen isn't the most vibrant, its 90Hz refresh rate keeps scrolling feeling smooth. It is a thick, heavy, but incredibly reliable budget 5G option.",
    highlights: ["6000mAh Battery", "Exynos 1330 5G Processor", "90Hz PLS LCD Display"],
    pros: ["Phenomenal battery endurance", "Affordable 5G access", "Smooth 90Hz refresh rate"],
    cons: ["LCD screen lacks punchy colors", "Very thick and heavy design", "Basic camera performance"],
    verdict: "A practical, no-nonsense budget 5G phone that guarantees you will rarely need to reach for a charger."
  },
  {
    name: "Galaxy M12",
    slug: "samsung-galaxy-m12",
    phone_status: "released",
    is_published: true,
    is_official: true,
    colors: ["Black", "Light Blue", "Green"],
    release_date: "2021-04-30",
    price_usd: 140,
    price_bdt: 15500,
    price_display_text: "BDT 15,500",
    processor: "Exynos 850",
    gpu: "Mali-G52",
    display_type: "PLS LCD, 90Hz",
    screen_size: "6.5 inches",
    refresh_rate: "90Hz",
    brightness: "400 nits",
    cam_count: "Quad",
    cam_main_sensor: "48 MP, f/2.0, PDAF",
    video_recording: "1080p@30fps",
    battery_capacity: "6000 mAh",
    charging_wired: "15W wired",
    wireless_charging: "No",
    ip_rating: "None",
    weight: "212 g",
    dimensions: "164 x 75.9 x 9.7 mm",
    images: ["/placeholder.jpg"],
    price_segment: "Entry-Level",
    performance_tier: "Basic",
    camera_tier: "Basic",
    battery_tier: "Endurance",
    internal_links: { same_brand: ["samsung-galaxy-m11", "samsung-galaxy-m13"] },
    ...commonSeoFields("Galaxy M12", 140),
    overview: "The Galaxy M12 was an incredibly popular entry-level phone because it brought a 90Hz high-refresh-rate display to a rock-bottom price point. It also featured a massive 6000mAh battery (in the Indian variant) and a highly textured, grippy back panel that felt surprisingly durable. However, to hit this price, Samsung used the incredibly sluggish Exynos 850 processor and a low-resolution 720p PLS LCD screen. While it was fantastic for battery life and basic media consumption, the slow processor meant that opening apps and multitasking often required patience.",
    highlights: ["90Hz Display on a budget", "Massive 6000mAh Battery", "48MP Main Camera"],
    pros: ["Extremely affordable", "Battery lasts forever", "90Hz screen makes UI feel slightly smoother"],
    cons: ["Exynos 850 is painfully slow", "Low 720p screen resolution", "Very heavy and thick"],
    verdict: "A great starter phone or secondary device that offers incredible battery life, provided you don't mind slow performance."
  }
];

async function run() {
  try {
    await mongoose.connect(MONGODB_URI as string);
    console.log("✅ Connected to MongoDB");

    const Brand = mongoose.models.Brand || mongoose.model("Brand", new mongoose.Schema({}, { strict: false }));
    const samsungBrand = await Brand.findOne({ name: /Samsung/i });

    const PhoneSchema = new mongoose.Schema({}, { strict: false });
    const Phone = mongoose.models.Phone || mongoose.model("Phone", PhoneSchema);

    for (const phone of phonesData) {
      if (samsungBrand) (phone as any).brand_id = samsungBrand._id;
      phone.updated_at = new Date() as any;
      await Phone.findOneAndUpdate({ slug: phone.slug }, { $set: phone }, { upsert: true, new: true });
      console.log(`✅ Inserted/Updated: ${phone.name}`);
    }

    console.log("🎉 Samsung Batch 15 (Popular M-Series) completed! Added 9 phones.");

  } catch (err) {
    console.error("❌ Error:", (err as Error).message);
  } finally {
    await mongoose.disconnect();
  }
}

run();
