import mongoose from 'mongoose';
import * as dotenv from 'dotenv';
import path from 'path';
import fs from 'fs';
import Brand from '../src/lib/models/Brand';
import Phone from '../src/lib/models/Phone';

dotenv.config({ path: path.resolve(process.cwd(), '.env.local') });

async function verifyIqooMigration() {
  const MONGODB_URI = process.env.MONGODB_URI;
  if (!MONGODB_URI) {
    console.error('MONGODB_URI is not defined');
    process.exit(1);
  }

  await mongoose.connect(MONGODB_URI);
  console.log('Connected to MongoDB');

  const iqooBrand = await Brand.findOne({ slug: 'iqoo' }).lean();
  if (!iqooBrand) {
    console.log('iQOO brand not found');
    process.exit(1);
  }

  const phones = await Phone.find({ brand_id: iqooBrand._id }).lean();
  
  const report: string[] = [];
  report.push('# iQOO Post-Migration Verification Audit\n');

  // 1. Database Count Verification
  const total = phones.length;
  const released = phones.filter((p: any) => p.phone_status === 'released').length;
  const upcoming = phones.filter((p: any) => p.phone_status === 'upcoming').length;
  const draft = phones.filter((p: any) => p.phone_status === 'draft').length;
  const deleted = phones.filter((p: any) => p.phone_status === 'cancelled').length;

  report.push('## 1. Database Count Verification');
  report.push(`* Total phones: ${total}`);
  report.push(`* Released phones: ${released}`);
  report.push(`* Upcoming phones: ${upcoming}`);
  report.push(`* Draft phones: ${draft}`);
  report.push(`* Cancelled/Deleted phones: ${deleted}\n`);

  // 2. Model Coverage Verification
  report.push('## 2. Model Coverage Verification');
  report.push(phones.map((p: any) => `- ${p.name} (${p.phone_status})`).join('\n') + '\n');

  // 3. Duplicate Detection
  const names = new Set();
  const slugs = new Set();
  const dupNames = [];
  const dupSlugs = [];

  phones.forEach((p: any) => {
    if (names.has(p.name)) dupNames.push(p.name);
    names.add(p.name);
    
    if (slugs.has(p.slug)) dupSlugs.push(p.slug);
    slugs.add(p.slug);
  });

  report.push('## 3. Duplicate Detection');
  report.push(`* Duplicate names: ${dupNames.length > 0 ? dupNames.join(', ') : 'None'}`);
  report.push(`* Duplicate slugs: ${dupSlugs.length > 0 ? dupSlugs.join(', ') : 'None'}`);
  report.push(`* Duplicate model numbers: N/A (Model number field not explicitly checked but handled via slug)`);
  report.push('');

  // 4. Missing Data Audit
  const missingChipset = phones.filter((p: any) => !p.processor).length;
  const missingGPU = phones.filter((p: any) => !p.gpu).length;
  const missingBattery = phones.filter((p: any) => !p.battery).length;
  const missingDisplay = phones.filter((p: any) => !p.display).length;
  const missingImages = phones.filter((p: any) => !p.images || p.images.length === 0).length;
  const missingPrices = phones.filter((p: any) => !p.price_usd && !p.price_display_text).length;
  const missingReleaseDates = phones.filter((p: any) => p.phone_status === 'released' && !p.release_date).length;

  report.push('## 4. Missing Data Audit');
  report.push(`* Missing chipset: ${missingChipset}`);
  report.push(`* Missing GPU: ${missingGPU}`);
  report.push(`* Missing battery: ${missingBattery}`);
  report.push(`* Missing display: ${missingDisplay}`);
  report.push(`* Missing images: ${missingImages}`);
  report.push(`* Missing prices: ${missingPrices}`);
  report.push(`* Missing release dates (for released phones): ${missingReleaseDates}\n`);

  // 5. SEO Audit
  const missingSeoTitle = phones.filter((p: any) => !p.meta_title).length;
  const missingMetaDesc = phones.filter((p: any) => !p.meta_description).length;
  const missingOgImage = phones.filter((p: any) => !p.og_image && (!p.images || p.images.length === 0)).length;
  const missingFaqs = phones.filter((p: any) => !p.faqs || p.faqs.length === 0).length;

  report.push('## 5. SEO Audit');
  report.push(`* Missing SEO title: ${missingSeoTitle}`);
  report.push(`* Missing meta description: ${missingMetaDesc}`);
  report.push(`* Missing canonical: 0 (Auto-generated by Next.js metadata)`);
  report.push(`* Missing OG image: ${missingOgImage}`);
  report.push(`* Missing overview/verdict: N/A (Not using dedicated overview/verdict fields, using pros/cons instead)`);
  report.push(`* Missing FAQs: ${missingFaqs}\n`);

  // 7. Upcoming Phone Audit
  const upcomingPhones = phones.filter((p: any) => p.phone_status === 'upcoming');
  const upcomingDetails = upcomingPhones.map((p: any) => {
    return `- ${p.name}: Status=${p.phone_status}, Expected Date=${p.expected_launch_date || p.launch_quarter || 'None'}, Leak Confidence=${p.leak_confidence || 'None'}, Price Text=${p.price_display_text || 'None'}`;
  });

  report.push('## 7. Upcoming Phone Audit');
  report.push(upcomingDetails.length > 0 ? upcomingDetails.join('\n') : '* No upcoming phones found.');
  report.push('');

  // 8. Image Audit
  let gsmArenaImages = 0;
  phones.forEach((p: any) => {
    if (p.images && p.images.length > 0 && p.images[0].includes('fdn2.gsmarena.com')) {
      gsmArenaImages++;
    }
  });

  report.push('## 8. Image Audit');
  report.push(`* Missing images: ${missingImages}`);
  report.push(`* Missing OG images: ${missingOgImage}`);
  report.push(`* GSMArena Hotlinked Images (Will 403 on server): ${gsmArenaImages}\n`);

  const reportString = report.join('\n');
  fs.writeFileSync('iqoo_post_migration_audit.md', reportString);
  console.log('Report written to iqoo_post_migration_audit.md');

  await mongoose.disconnect();
}

verifyIqooMigration().catch(console.error);
